/* Generated by Yosys 0.57+125 (git sha1 d5053033e, g++ 11.5.0 -fPIC -O3) */

module A_Q_Q_1(alu_out, load_A, Q, load_Q, rst, clk_in, en, Q_Q_1, out);
  input [15:0] alu_out;
  wire [15:0] alu_out;
  input load_A;
  wire load_A;
  input [15:0] Q;
  wire [15:0] Q;
  input load_Q;
  wire load_Q;
  input rst;
  wire rst;
  input clk_in;
  wire clk_in;
  input en;
  wire en;
  output [1:0] Q_Q_1;
  wire [1:0] Q_Q_1;
  output [31:0] out;
  wire [31:0] out;
  wire [15:0] A_reg_Q;
  wire [15:0] A_reg_in;
  wire AtoQ;
  wire [15:0] Q_reg_Q;
  wire [15:0] Q_reg_in;
  wire clk;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(A_reg_Q[0]),
    .A1(alu_out[0]),
    .S(load_A),
    .X(AtoQ)
  );
  sky130_fd_sc_hd__and2_0 _1_ (
    .A(clk_in),
    .B(en),
    .X(clk)
  );
  d_ff A0_reg (
    .D(A_reg_in[0]),
    .Q(A_reg_Q[0]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A0_sel (
    .i0(A_reg_Q[1]),
    .i1(alu_out[1]),
    .s(load_A),
    .y(A_reg_in[0])
  );
  d_ff A10_reg (
    .D(A_reg_in[10]),
    .Q(A_reg_Q[10]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A10_sel (
    .i0(A_reg_Q[11]),
    .i1(alu_out[11]),
    .s(load_A),
    .y(A_reg_in[10])
  );
  d_ff A11_reg (
    .D(A_reg_in[11]),
    .Q(A_reg_Q[11]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A11_sel (
    .i0(A_reg_Q[12]),
    .i1(alu_out[12]),
    .s(load_A),
    .y(A_reg_in[11])
  );
  d_ff A12_reg (
    .D(A_reg_in[12]),
    .Q(A_reg_Q[12]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A12_sel (
    .i0(A_reg_Q[13]),
    .i1(alu_out[13]),
    .s(load_A),
    .y(A_reg_in[12])
  );
  d_ff A13_reg (
    .D(A_reg_in[13]),
    .Q(A_reg_Q[13]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A13_sel (
    .i0(A_reg_Q[14]),
    .i1(alu_out[14]),
    .s(load_A),
    .y(A_reg_in[13])
  );
  d_ff A14_reg (
    .D(A_reg_in[14]),
    .Q(A_reg_Q[14]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A14_sel (
    .i0(A_reg_Q[15]),
    .i1(alu_out[15]),
    .s(load_A),
    .y(A_reg_in[14])
  );
  d_ff A15_reg (
    .D(A_reg_in[15]),
    .Q(A_reg_Q[15]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A15_sel (
    .i0(A_reg_Q[15]),
    .i1(alu_out[15]),
    .s(load_A),
    .y(A_reg_in[15])
  );
  d_ff A1_reg (
    .D(A_reg_in[1]),
    .Q(A_reg_Q[1]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A1_sel (
    .i0(A_reg_Q[2]),
    .i1(alu_out[2]),
    .s(load_A),
    .y(A_reg_in[1])
  );
  d_ff A2_reg (
    .D(A_reg_in[2]),
    .Q(A_reg_Q[2]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A2_sel (
    .i0(A_reg_Q[3]),
    .i1(alu_out[3]),
    .s(load_A),
    .y(A_reg_in[2])
  );
  d_ff A3_reg (
    .D(A_reg_in[3]),
    .Q(A_reg_Q[3]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A3_sel (
    .i0(A_reg_Q[4]),
    .i1(alu_out[4]),
    .s(load_A),
    .y(A_reg_in[3])
  );
  d_ff A4_reg (
    .D(A_reg_in[4]),
    .Q(A_reg_Q[4]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A4_sel (
    .i0(A_reg_Q[5]),
    .i1(alu_out[5]),
    .s(load_A),
    .y(A_reg_in[4])
  );
  d_ff A5_reg (
    .D(A_reg_in[5]),
    .Q(A_reg_Q[5]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A5_sel (
    .i0(A_reg_Q[6]),
    .i1(alu_out[6]),
    .s(load_A),
    .y(A_reg_in[5])
  );
  d_ff A6_reg (
    .D(A_reg_in[6]),
    .Q(A_reg_Q[6]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A6_sel (
    .i0(A_reg_Q[7]),
    .i1(alu_out[7]),
    .s(load_A),
    .y(A_reg_in[6])
  );
  d_ff A7_reg (
    .D(A_reg_in[7]),
    .Q(A_reg_Q[7]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A7_sel (
    .i0(A_reg_Q[8]),
    .i1(alu_out[8]),
    .s(load_A),
    .y(A_reg_in[7])
  );
  d_ff A8_reg (
    .D(A_reg_in[8]),
    .Q(A_reg_Q[8]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A8_sel (
    .i0(A_reg_Q[9]),
    .i1(alu_out[9]),
    .s(load_A),
    .y(A_reg_in[8])
  );
  d_ff A9_reg (
    .D(A_reg_in[9]),
    .Q(A_reg_Q[9]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 A9_sel (
    .i0(A_reg_Q[10]),
    .i1(alu_out[10]),
    .s(load_A),
    .y(A_reg_in[9])
  );
  d_ff Q0_reg (
    .D(Q_reg_in[0]),
    .Q(Q_reg_Q[0]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q0_sel (
    .i0(Q_reg_Q[1]),
    .i1(Q[0]),
    .s(load_Q),
    .y(Q_reg_in[0])
  );
  d_ff Q10_reg (
    .D(Q_reg_in[10]),
    .Q(Q_reg_Q[10]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q10_sel (
    .i0(Q_reg_Q[11]),
    .i1(Q[10]),
    .s(load_Q),
    .y(Q_reg_in[10])
  );
  d_ff Q11_reg (
    .D(Q_reg_in[11]),
    .Q(Q_reg_Q[11]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q11_sel (
    .i0(Q_reg_Q[12]),
    .i1(Q[11]),
    .s(load_Q),
    .y(Q_reg_in[11])
  );
  d_ff Q12_reg (
    .D(Q_reg_in[12]),
    .Q(Q_reg_Q[12]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q12_sel (
    .i0(Q_reg_Q[13]),
    .i1(Q[12]),
    .s(load_Q),
    .y(Q_reg_in[12])
  );
  d_ff Q13_reg (
    .D(Q_reg_in[13]),
    .Q(Q_reg_Q[13]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q13_sel (
    .i0(Q_reg_Q[14]),
    .i1(Q[13]),
    .s(load_Q),
    .y(Q_reg_in[13])
  );
  d_ff Q14_reg (
    .D(Q_reg_in[14]),
    .Q(Q_reg_Q[14]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q14_sel (
    .i0(Q_reg_Q[15]),
    .i1(Q[14]),
    .s(load_Q),
    .y(Q_reg_in[14])
  );
  d_ff Q15_reg (
    .D(Q_reg_in[15]),
    .Q(Q_reg_Q[15]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q15_sel (
    .i0(AtoQ),
    .i1(Q[15]),
    .s(load_Q),
    .y(Q_reg_in[15])
  );
  d_ff Q1_reg (
    .D(Q_reg_in[1]),
    .Q(Q_reg_Q[1]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q1_sel (
    .i0(Q_reg_Q[2]),
    .i1(Q[1]),
    .s(load_Q),
    .y(Q_reg_in[1])
  );
  d_ff Q2_reg (
    .D(Q_reg_in[2]),
    .Q(Q_reg_Q[2]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q2_sel (
    .i0(Q_reg_Q[3]),
    .i1(Q[2]),
    .s(load_Q),
    .y(Q_reg_in[2])
  );
  d_ff Q3_reg (
    .D(Q_reg_in[3]),
    .Q(Q_reg_Q[3]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q3_sel (
    .i0(Q_reg_Q[4]),
    .i1(Q[3]),
    .s(load_Q),
    .y(Q_reg_in[3])
  );
  d_ff Q4_reg (
    .D(Q_reg_in[4]),
    .Q(Q_reg_Q[4]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q4_sel (
    .i0(Q_reg_Q[5]),
    .i1(Q[4]),
    .s(load_Q),
    .y(Q_reg_in[4])
  );
  d_ff Q5_reg (
    .D(Q_reg_in[5]),
    .Q(Q_reg_Q[5]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q5_sel (
    .i0(Q_reg_Q[6]),
    .i1(Q[5]),
    .s(load_Q),
    .y(Q_reg_in[5])
  );
  d_ff Q6_reg (
    .D(Q_reg_in[6]),
    .Q(Q_reg_Q[6]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q6_sel (
    .i0(Q_reg_Q[7]),
    .i1(Q[6]),
    .s(load_Q),
    .y(Q_reg_in[6])
  );
  d_ff Q7_reg (
    .D(Q_reg_in[7]),
    .Q(Q_reg_Q[7]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q7_sel (
    .i0(Q_reg_Q[8]),
    .i1(Q[7]),
    .s(load_Q),
    .y(Q_reg_in[7])
  );
  d_ff Q8_reg (
    .D(Q_reg_in[8]),
    .Q(Q_reg_Q[8]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q8_sel (
    .i0(Q_reg_Q[9]),
    .i1(Q[8]),
    .s(load_Q),
    .y(Q_reg_in[8])
  );
  d_ff Q9_reg (
    .D(Q_reg_in[9]),
    .Q(Q_reg_Q[9]),
    .clk(clk),
    .rst(rst)
  );
  mux2x1 Q9_sel (
    .i0(Q_reg_Q[10]),
    .i1(Q[9]),
    .s(load_Q),
    .y(Q_reg_in[9])
  );
  d_ff Q_1_reg (
    .D(Q_reg_Q[0]),
    .Q(Q_Q_1[0]),
    .clk(clk),
    .rst(rst)
  );
  assign Q_Q_1[1] = Q_reg_Q[0];
  assign out = { A_reg_Q, Q_reg_Q };
endmodule

module M_register(Q, clk, rst, Data);
  output [15:0] Q;
  wire [15:0] Q;
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [15:0] Data;
  wire [15:0] Data;
  d_ff \genblk1[0].d_ureg0  (
    .D(Data[0]),
    .Q(Q[0]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[10].d_ureg0  (
    .D(Data[10]),
    .Q(Q[10]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[11].d_ureg0  (
    .D(Data[11]),
    .Q(Q[11]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[12].d_ureg0  (
    .D(Data[12]),
    .Q(Q[12]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[13].d_ureg0  (
    .D(Data[13]),
    .Q(Q[13]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[14].d_ureg0  (
    .D(Data[14]),
    .Q(Q[14]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[15].d_ureg0  (
    .D(Data[15]),
    .Q(Q[15]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[1].d_ureg0  (
    .D(Data[1]),
    .Q(Q[1]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[2].d_ureg0  (
    .D(Data[2]),
    .Q(Q[2]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[3].d_ureg0  (
    .D(Data[3]),
    .Q(Q[3]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[4].d_ureg0  (
    .D(Data[4]),
    .Q(Q[4]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[5].d_ureg0  (
    .D(Data[5]),
    .Q(Q[5]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[6].d_ureg0  (
    .D(Data[6]),
    .Q(Q[6]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[7].d_ureg0  (
    .D(Data[7]),
    .Q(Q[7]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[8].d_ureg0  (
    .D(Data[8]),
    .Q(Q[8]),
    .clk(clk),
    .rst(rst)
  );
  d_ff \genblk1[9].d_ureg0  (
    .D(Data[9]),
    .Q(Q[9]),
    .clk(clk),
    .rst(rst)
  );
endmodule

module add_sub(a, b, add_sub, out);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  input add_sub;
  wire add_sub;
  output [15:0] out;
  wire [15:0] out;
  wire [15:0] b_f;
  sky130_fd_sc_hd__xor2_1 _00_ (
    .A(add_sub),
    .B(b[0]),
    .X(b_f[0])
  );
  sky130_fd_sc_hd__xor2_1 _01_ (
    .A(add_sub),
    .B(b[1]),
    .X(b_f[1])
  );
  sky130_fd_sc_hd__xor2_1 _02_ (
    .A(add_sub),
    .B(b[2]),
    .X(b_f[2])
  );
  sky130_fd_sc_hd__xor2_1 _03_ (
    .A(add_sub),
    .B(b[3]),
    .X(b_f[3])
  );
  sky130_fd_sc_hd__xor2_1 _04_ (
    .A(add_sub),
    .B(b[4]),
    .X(b_f[4])
  );
  sky130_fd_sc_hd__xor2_1 _05_ (
    .A(add_sub),
    .B(b[5]),
    .X(b_f[5])
  );
  sky130_fd_sc_hd__xor2_1 _06_ (
    .A(add_sub),
    .B(b[6]),
    .X(b_f[6])
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(add_sub),
    .B(b[7]),
    .X(b_f[7])
  );
  sky130_fd_sc_hd__xor2_1 _08_ (
    .A(add_sub),
    .B(b[8]),
    .X(b_f[8])
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(add_sub),
    .B(b[9]),
    .X(b_f[9])
  );
  sky130_fd_sc_hd__xor2_1 _10_ (
    .A(add_sub),
    .B(b[10]),
    .X(b_f[10])
  );
  sky130_fd_sc_hd__xor2_1 _11_ (
    .A(add_sub),
    .B(b[11]),
    .X(b_f[11])
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(add_sub),
    .B(b[12]),
    .X(b_f[12])
  );
  sky130_fd_sc_hd__xor2_1 _13_ (
    .A(add_sub),
    .B(b[13]),
    .X(b_f[13])
  );
  sky130_fd_sc_hd__xor2_1 _14_ (
    .A(add_sub),
    .B(b[14]),
    .X(b_f[14])
  );
  sky130_fd_sc_hd__xor2_1 _15_ (
    .A(add_sub),
    .B(b[15]),
    .X(b_f[15])
  );
  kogge_stone_adder add_sub_module (
    .a(a),
    .b(b_f),
    .cin(add_sub),
    .sum(out)
  );
endmodule

module and_xor(a, b, g, p);
  input a;
  wire a;
  input b;
  wire b;
  output g;
  wire g;
  output p;
  wire p;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(b),
    .B(a),
    .X(g)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(b),
    .B(a),
    .X(p)
  );
endmodule

module black_cell(Gkj, Pik, Gik, Pkj, G, P);
  input Gkj;
  wire Gkj;
  input Pik;
  wire Pik;
  input Gik;
  wire Gik;
  input Pkj;
  wire Pkj;
  output G;
  wire G;
  output P;
  wire P;
  sky130_fd_sc_hd__a21o_1 _0_ (
    .A1(Pik),
    .A2(Gkj),
    .B1(Gik),
    .X(G)
  );
  sky130_fd_sc_hd__and2_0 _1_ (
    .A(Pik),
    .B(Pkj),
    .X(P)
  );
endmodule

module booth_multiplier(op, read, busy, multiplicand, multiplier, clk_in, mrst);
  output [31:0] op;
  wire [31:0] op;
  output read;
  wire read;
  output busy;
  wire busy;
  input [15:0] multiplicand;
  wire [15:0] multiplicand;
  input [15:0] multiplier;
  wire [15:0] multiplier;
  input clk_in;
  wire clk_in;
  input mrst;
  wire mrst;
  wire _0_;
  wire [15:0] M;
  wire [1:0] Q_Q_1;
  wire add0_sub1;
  wire [15:0] alu_out;
  wire c_rst;
  wire clk;
  wire [4:0] cntr_op;
  wire load_a;
  wire nrst;
  wire rst;
  wire start;
  sky130_fd_sc_hd__clkinv_1 _1_ (
    .A(mrst),
    .Y(nrst)
  );
  sky130_fd_sc_hd__clkinv_1 _2_ (
    .A(start),
    .Y(c_rst)
  );
  sky130_fd_sc_hd__or4_1 _3_ (
    .A(cntr_op[1]),
    .B(cntr_op[0]),
    .C(cntr_op[3]),
    .D(cntr_op[2]),
    .X(busy)
  );
  sky130_fd_sc_hd__nand2b_1 _4_ (
    .A_N(mrst),
    .B(start),
    .Y(rst)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _5_ (
    .A(clk_in),
    .SLEEP(cntr_op[4]),
    .X(clk)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _6_ (
    .A(Q_Q_1[1]),
    .SLEEP(Q_Q_1[0]),
    .X(add0_sub1)
  );
  sky130_fd_sc_hd__xor2_1 _7_ (
    .A(Q_Q_1[1]),
    .B(Q_Q_1[0]),
    .X(load_a)
  );
  sky130_fd_sc_hd__conb_1 _8_ (
    .HI(_0_)
  );
  A_Q_Q_1 AQQ_1_register (
    .Q(multiplier),
    .Q_Q_1(Q_Q_1),
    .alu_out(alu_out),
    .clk_in(clk),
    .en(_0_),
    .load_A(load_a),
    .load_Q(start),
    .out(op),
    .rst(rst)
  );
  M_register M_reg (
    .Data(multiplicand),
    .Q(M),
    .clk(start),
    .rst(rst)
  );
  add_sub alu (
    .a(op[31:16]),
    .add_sub(add0_sub1),
    .b(M),
    .out(alu_out)
  );
  counter c0 (
    .Q(cntr_op),
    .clk(clk),
    .rst(c_rst)
  );
  d_ff cntrl_gen0 (
    .D(nrst),
    .Q(start),
    .clk(clk_in)
  );
  assign read = cntr_op[4];
endmodule

module counter(clk, rst, Q);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [4:0] Q;
  wire [4:0] Q;
  wire [4:0] d_in;
  d_ff c0 (
    .D(d_in[0]),
    .Q(Q[0]),
    .Qb(d_in[0]),
    .clk(clk),
    .rst(rst)
  );
  d_ff c1 (
    .D(d_in[1]),
    .Q(Q[1]),
    .Qb(d_in[1]),
    .clk(Q[0]),
    .rst(rst)
  );
  d_ff c2 (
    .D(d_in[2]),
    .Q(Q[2]),
    .Qb(d_in[2]),
    .clk(Q[1]),
    .rst(rst)
  );
  d_ff c3 (
    .D(d_in[3]),
    .Q(Q[3]),
    .Qb(d_in[3]),
    .clk(Q[2]),
    .rst(rst)
  );
  d_ff c4 (
    .D(d_in[4]),
    .Q(Q[4]),
    .Qb(d_in[4]),
    .clk(Q[3]),
    .rst(rst)
  );
endmodule

module d_ff(Q, Qb, clk, rst, D);
  output Q;
  wire Q;
  output Qb;
  wire Qb;
  input clk;
  wire clk;
  input rst;
  wire rst;
  input D;
  wire D;
  wire _0_;
  wire _1_;
  sky130_fd_sc_hd__clkinv_1 _2_ (
    .A(D),
    .Y(_0_)
  );
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(clk),
    .Y(_1_)
  );
  sky130_fd_sc_hd__dfrtn_1 _4_ (
    .CLK_N(clk),
    .D(D),
    .Q(Q),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfstp_2 _5_ (
    .CLK(_1_),
    .D(_0_),
    .Q(Qb),
    .SET_B(rst)
  );
endmodule

module grey_cell(Gkj, Pik, Gik, G);
  input Gkj;
  wire Gkj;
  input Pik;
  wire Pik;
  input Gik;
  wire Gik;
  output G;
  wire G;
  sky130_fd_sc_hd__a21o_1 _0_ (
    .A1(Pik),
    .A2(Gkj),
    .B1(Gik),
    .X(G)
  );
endmodule

module kogge_stone_adder(a, b, cin, sum, cout);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  input cin;
  wire cin;
  output [15:0] sum;
  wire [15:0] sum;
  output cout;
  wire cout;
  wire [15:0] Ga;
  wire [15:0] Gb;
  wire [15:0] Gc;
  wire [15:0] Gd;
  wire [15:0] Gz;
  wire [15:0] Pa;
  wire [15:0] Pb;
  wire [15:0] Pc;
  wire [15:0] Pd;
  wire [15:0] Pz;
  sky130_fd_sc_hd__xor2_1 _00_ (
    .A(Pz[0]),
    .B(cin),
    .X(sum[0])
  );
  sky130_fd_sc_hd__xor2_1 _01_ (
    .A(Pz[1]),
    .B(Ga[0]),
    .X(sum[1])
  );
  sky130_fd_sc_hd__xor2_1 _02_ (
    .A(Pz[2]),
    .B(Gb[1]),
    .X(sum[2])
  );
  sky130_fd_sc_hd__xor2_1 _03_ (
    .A(Pz[3]),
    .B(Gb[2]),
    .X(sum[3])
  );
  sky130_fd_sc_hd__xor2_1 _04_ (
    .A(Pz[4]),
    .B(Gc[3]),
    .X(sum[4])
  );
  sky130_fd_sc_hd__xor2_1 _05_ (
    .A(Pz[5]),
    .B(Gc[4]),
    .X(sum[5])
  );
  sky130_fd_sc_hd__xor2_1 _06_ (
    .A(Pz[6]),
    .B(Gc[5]),
    .X(sum[6])
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(Pz[7]),
    .B(Gc[6]),
    .X(sum[7])
  );
  sky130_fd_sc_hd__xor2_1 _08_ (
    .A(Pz[8]),
    .B(Gd[7]),
    .X(sum[8])
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(Pz[9]),
    .B(Gd[8]),
    .X(sum[9])
  );
  sky130_fd_sc_hd__xor2_1 _10_ (
    .A(Pz[10]),
    .B(Gd[9]),
    .X(sum[10])
  );
  sky130_fd_sc_hd__xor2_1 _11_ (
    .A(Pz[11]),
    .B(Gd[10]),
    .X(sum[11])
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(Pz[12]),
    .B(Gd[11]),
    .X(sum[12])
  );
  sky130_fd_sc_hd__xor2_1 _13_ (
    .A(Pz[13]),
    .B(Gd[12]),
    .X(sum[13])
  );
  sky130_fd_sc_hd__xor2_1 _14_ (
    .A(Pz[14]),
    .B(Gd[13]),
    .X(sum[14])
  );
  sky130_fd_sc_hd__xor2_1 _15_ (
    .A(Pz[15]),
    .B(Gd[14]),
    .X(sum[15])
  );
  and_xor ax0 (
    .a(a[0]),
    .b(b[0]),
    .g(Gz[0]),
    .p(Pz[0])
  );
  and_xor ax1 (
    .a(a[1]),
    .b(b[1]),
    .g(Gz[1]),
    .p(Pz[1])
  );
  and_xor ax10 (
    .a(a[10]),
    .b(b[10]),
    .g(Gz[10]),
    .p(Pz[10])
  );
  and_xor ax11 (
    .a(a[11]),
    .b(b[11]),
    .g(Gz[11]),
    .p(Pz[11])
  );
  and_xor ax12 (
    .a(a[12]),
    .b(b[12]),
    .g(Gz[12]),
    .p(Pz[12])
  );
  and_xor ax13 (
    .a(a[13]),
    .b(b[13]),
    .g(Gz[13]),
    .p(Pz[13])
  );
  and_xor ax14 (
    .a(a[14]),
    .b(b[14]),
    .g(Gz[14]),
    .p(Pz[14])
  );
  and_xor ax15 (
    .a(a[15]),
    .b(b[15]),
    .g(Gz[15]),
    .p(Pz[15])
  );
  and_xor ax2 (
    .a(a[2]),
    .b(b[2]),
    .g(Gz[2]),
    .p(Pz[2])
  );
  and_xor ax3 (
    .a(a[3]),
    .b(b[3]),
    .g(Gz[3]),
    .p(Pz[3])
  );
  and_xor ax4 (
    .a(a[4]),
    .b(b[4]),
    .g(Gz[4]),
    .p(Pz[4])
  );
  and_xor ax5 (
    .a(a[5]),
    .b(b[5]),
    .g(Gz[5]),
    .p(Pz[5])
  );
  and_xor ax6 (
    .a(a[6]),
    .b(b[6]),
    .g(Gz[6]),
    .p(Pz[6])
  );
  and_xor ax7 (
    .a(a[7]),
    .b(b[7]),
    .g(Gz[7]),
    .p(Pz[7])
  );
  and_xor ax8 (
    .a(a[8]),
    .b(b[8]),
    .g(Gz[8]),
    .p(Pz[8])
  );
  and_xor ax9 (
    .a(a[9]),
    .b(b[9]),
    .g(Gz[9]),
    .p(Pz[9])
  );
  black_cell l1_bc0 (
    .G(Ga[1]),
    .Gik(Gz[1]),
    .Gkj(Gz[0]),
    .P(Pa[1]),
    .Pik(Pz[1]),
    .Pkj(Pz[0])
  );
  black_cell l1_bc1 (
    .G(Ga[2]),
    .Gik(Gz[2]),
    .Gkj(Gz[1]),
    .P(Pa[2]),
    .Pik(Pz[2]),
    .Pkj(Pz[1])
  );
  black_cell l1_bc10 (
    .G(Ga[11]),
    .Gik(Gz[11]),
    .Gkj(Gz[10]),
    .P(Pa[11]),
    .Pik(Pz[11]),
    .Pkj(Pz[10])
  );
  black_cell l1_bc11 (
    .G(Ga[12]),
    .Gik(Gz[12]),
    .Gkj(Gz[11]),
    .P(Pa[12]),
    .Pik(Pz[12]),
    .Pkj(Pz[11])
  );
  black_cell l1_bc12 (
    .G(Ga[13]),
    .Gik(Gz[13]),
    .Gkj(Gz[12]),
    .P(Pa[13]),
    .Pik(Pz[13]),
    .Pkj(Pz[12])
  );
  black_cell l1_bc13 (
    .G(Ga[14]),
    .Gik(Gz[14]),
    .Gkj(Gz[13]),
    .P(Pa[14]),
    .Pik(Pz[14]),
    .Pkj(Pz[13])
  );
  black_cell l1_bc14 (
    .G(Ga[15]),
    .Gik(Gz[15]),
    .Gkj(Gz[14]),
    .P(Pa[15]),
    .Pik(Pz[15]),
    .Pkj(Pz[14])
  );
  black_cell l1_bc2 (
    .G(Ga[3]),
    .Gik(Gz[3]),
    .Gkj(Gz[2]),
    .P(Pa[3]),
    .Pik(Pz[3]),
    .Pkj(Pz[2])
  );
  black_cell l1_bc3 (
    .G(Ga[4]),
    .Gik(Gz[4]),
    .Gkj(Gz[3]),
    .P(Pa[4]),
    .Pik(Pz[4]),
    .Pkj(Pz[3])
  );
  black_cell l1_bc4 (
    .G(Ga[5]),
    .Gik(Gz[5]),
    .Gkj(Gz[4]),
    .P(Pa[5]),
    .Pik(Pz[5]),
    .Pkj(Pz[4])
  );
  black_cell l1_bc5 (
    .G(Ga[6]),
    .Gik(Gz[6]),
    .Gkj(Gz[5]),
    .P(Pa[6]),
    .Pik(Pz[6]),
    .Pkj(Pz[5])
  );
  black_cell l1_bc6 (
    .G(Ga[7]),
    .Gik(Gz[7]),
    .Gkj(Gz[6]),
    .P(Pa[7]),
    .Pik(Pz[7]),
    .Pkj(Pz[6])
  );
  black_cell l1_bc7 (
    .G(Ga[8]),
    .Gik(Gz[8]),
    .Gkj(Gz[7]),
    .P(Pa[8]),
    .Pik(Pz[8]),
    .Pkj(Pz[7])
  );
  black_cell l1_bc8 (
    .G(Ga[9]),
    .Gik(Gz[9]),
    .Gkj(Gz[8]),
    .P(Pa[9]),
    .Pik(Pz[9]),
    .Pkj(Pz[8])
  );
  black_cell l1_bc9 (
    .G(Ga[10]),
    .Gik(Gz[10]),
    .Gkj(Gz[9]),
    .P(Pa[10]),
    .Pik(Pz[10]),
    .Pkj(Pz[9])
  );
  grey_cell l1_gc0 (
    .G(Ga[0]),
    .Gik(Gz[0]),
    .Gkj(cin),
    .Pik(Pz[0])
  );
  black_cell l2_bc0 (
    .G(Gb[3]),
    .Gik(Ga[3]),
    .Gkj(Ga[1]),
    .P(Pb[3]),
    .Pik(Pa[3]),
    .Pkj(Pa[1])
  );
  black_cell l2_bc1 (
    .G(Gb[4]),
    .Gik(Ga[4]),
    .Gkj(Ga[2]),
    .P(Pb[4]),
    .Pik(Pa[4]),
    .Pkj(Pa[2])
  );
  black_cell l2_bc10 (
    .G(Gb[13]),
    .Gik(Ga[13]),
    .Gkj(Ga[11]),
    .P(Pb[13]),
    .Pik(Pa[13]),
    .Pkj(Pa[11])
  );
  black_cell l2_bc11 (
    .G(Gb[14]),
    .Gik(Ga[14]),
    .Gkj(Ga[12]),
    .P(Pb[14]),
    .Pik(Pa[14]),
    .Pkj(Pa[12])
  );
  black_cell l2_bc12 (
    .G(Gb[15]),
    .Gik(Ga[15]),
    .Gkj(Ga[13]),
    .P(Pb[15]),
    .Pik(Pa[15]),
    .Pkj(Pa[13])
  );
  black_cell l2_bc2 (
    .G(Gb[5]),
    .Gik(Ga[5]),
    .Gkj(Ga[3]),
    .P(Pb[5]),
    .Pik(Pa[5]),
    .Pkj(Pa[3])
  );
  black_cell l2_bc3 (
    .G(Gb[6]),
    .Gik(Ga[6]),
    .Gkj(Ga[4]),
    .P(Pb[6]),
    .Pik(Pa[6]),
    .Pkj(Pa[4])
  );
  black_cell l2_bc4 (
    .G(Gb[7]),
    .Gik(Ga[7]),
    .Gkj(Ga[5]),
    .P(Pb[7]),
    .Pik(Pa[7]),
    .Pkj(Pa[5])
  );
  black_cell l2_bc5 (
    .G(Gb[8]),
    .Gik(Ga[8]),
    .Gkj(Ga[6]),
    .P(Pb[8]),
    .Pik(Pa[8]),
    .Pkj(Pa[6])
  );
  black_cell l2_bc6 (
    .G(Gb[9]),
    .Gik(Ga[9]),
    .Gkj(Ga[7]),
    .P(Pb[9]),
    .Pik(Pa[9]),
    .Pkj(Pa[7])
  );
  black_cell l2_bc7 (
    .G(Gb[10]),
    .Gik(Ga[10]),
    .Gkj(Ga[8]),
    .P(Pb[10]),
    .Pik(Pa[10]),
    .Pkj(Pa[8])
  );
  black_cell l2_bc8 (
    .G(Gb[11]),
    .Gik(Ga[11]),
    .Gkj(Ga[9]),
    .P(Pb[11]),
    .Pik(Pa[11]),
    .Pkj(Pa[9])
  );
  black_cell l2_bc9 (
    .G(Gb[12]),
    .Gik(Ga[12]),
    .Gkj(Ga[10]),
    .P(Pb[12]),
    .Pik(Pa[12]),
    .Pkj(Pa[10])
  );
  grey_cell l2_gc0 (
    .G(Gb[1]),
    .Gik(Ga[1]),
    .Gkj(cin),
    .Pik(Pa[1])
  );
  grey_cell l2_gc1 (
    .G(Gb[2]),
    .Gik(Ga[2]),
    .Gkj(Ga[0]),
    .Pik(Pa[2])
  );
  black_cell l3_bc0 (
    .G(Gc[7]),
    .Gik(Gb[7]),
    .Gkj(Gb[3]),
    .P(Pc[7]),
    .Pik(Pb[7]),
    .Pkj(Pb[3])
  );
  black_cell l3_bc1 (
    .G(Gc[8]),
    .Gik(Gb[8]),
    .Gkj(Gb[4]),
    .P(Pc[8]),
    .Pik(Pb[8]),
    .Pkj(Pb[4])
  );
  black_cell l3_bc2 (
    .G(Gc[9]),
    .Gik(Gb[9]),
    .Gkj(Gb[5]),
    .P(Pc[9]),
    .Pik(Pb[9]),
    .Pkj(Pb[5])
  );
  black_cell l3_bc3 (
    .G(Gc[10]),
    .Gik(Gb[10]),
    .Gkj(Gb[6]),
    .P(Pc[10]),
    .Pik(Pb[10]),
    .Pkj(Pb[6])
  );
  black_cell l3_bc4 (
    .G(Gc[11]),
    .Gik(Gb[11]),
    .Gkj(Gb[7]),
    .P(Pc[11]),
    .Pik(Pb[11]),
    .Pkj(Pb[7])
  );
  black_cell l3_bc5 (
    .G(Gc[12]),
    .Gik(Gb[12]),
    .Gkj(Gb[8]),
    .P(Pc[12]),
    .Pik(Pb[12]),
    .Pkj(Pb[8])
  );
  black_cell l3_bc6 (
    .G(Gc[13]),
    .Gik(Gb[13]),
    .Gkj(Gb[9]),
    .P(Pc[13]),
    .Pik(Pb[13]),
    .Pkj(Pb[9])
  );
  black_cell l3_bc7 (
    .G(Gc[14]),
    .Gik(Gb[14]),
    .Gkj(Gb[10]),
    .P(Pc[14]),
    .Pik(Pb[14]),
    .Pkj(Pb[10])
  );
  black_cell l3_bc8 (
    .G(Gc[15]),
    .Gik(Gb[15]),
    .Gkj(Gb[11]),
    .P(Pc[15]),
    .Pik(Pb[15]),
    .Pkj(Pb[11])
  );
  grey_cell l3_gc0 (
    .G(Gc[3]),
    .Gik(Gb[3]),
    .Gkj(cin),
    .Pik(Pb[3])
  );
  grey_cell l3_gc1 (
    .G(Gc[4]),
    .Gik(Gb[4]),
    .Gkj(Ga[0]),
    .Pik(Pb[4])
  );
  grey_cell l3_gc2 (
    .G(Gc[5]),
    .Gik(Gb[5]),
    .Gkj(Gb[1]),
    .Pik(Pb[5])
  );
  grey_cell l3_gc3 (
    .G(Gc[6]),
    .Gik(Gb[6]),
    .Gkj(Gb[2]),
    .Pik(Pb[6])
  );
  black_cell l4_bc0 (
    .G(Gd[15]),
    .Gik(Gc[15]),
    .Gkj(Gc[7]),
    .P(Pd[15]),
    .Pik(Pc[15]),
    .Pkj(Pc[7])
  );
  grey_cell l4_gc0 (
    .G(Gd[7]),
    .Gik(Gc[7]),
    .Gkj(cin),
    .Pik(Pc[7])
  );
  grey_cell l4_gc1 (
    .G(Gd[8]),
    .Gik(Gc[8]),
    .Gkj(Ga[0]),
    .Pik(Pc[8])
  );
  grey_cell l4_gc2 (
    .G(Gd[9]),
    .Gik(Gc[9]),
    .Gkj(Gb[1]),
    .Pik(Pc[9])
  );
  grey_cell l4_gc3 (
    .G(Gd[10]),
    .Gik(Gc[10]),
    .Gkj(Gb[2]),
    .Pik(Pc[10])
  );
  grey_cell l4_gc4 (
    .G(Gd[11]),
    .Gik(Gc[11]),
    .Gkj(Gc[3]),
    .Pik(Pc[11])
  );
  grey_cell l4_gc5 (
    .G(Gd[12]),
    .Gik(Gc[12]),
    .Gkj(Gc[4]),
    .Pik(Pc[12])
  );
  grey_cell l4_gc6 (
    .G(Gd[13]),
    .Gik(Gc[13]),
    .Gkj(Gc[5]),
    .Pik(Pc[13])
  );
  grey_cell l4_gc7 (
    .G(Gd[14]),
    .Gik(Gc[14]),
    .Gkj(Gc[6]),
    .Pik(Pc[14])
  );
  grey_cell l5_gc0 (
    .G(cout),
    .Gik(Gd[15]),
    .Gkj(cin),
    .Pik(Pd[15])
  );
  assign Gb[0] = 1'h0;
  assign Gc[2:0] = 3'h0;
  assign Gd[6:0] = 7'h00;
  assign Pa[0] = 1'h0;
  assign Pb[2:0] = 3'h0;
  assign Pc[6:0] = 7'h00;
  assign Pd[14:0] = 15'h0000;
endmodule

module mux2x1(y, s, i1, i0);
  output y;
  wire y;
  input s;
  wire s;
  input i1;
  wire i1;
  input i0;
  wire i0;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(i0),
    .A1(i1),
    .S(s),
    .X(y)
  );
endmodule
