/* Generated by Yosys 0.57+125 (git sha1 d5053033e, g++ 11.5.0 -fPIC -O3) */

module CLA4bit(A, B, Cin, VDD, VSS, S, Cout);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  input Cin;
  wire Cin;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  output [3:0] S;
  wire [3:0] S;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [3:0] Ci;
  sky130_fd_sc_hd__xnor2_1 _07_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__maj3_1 _08_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(B[1]),
    .B(A[1]),
    .C(_01_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _11_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _12_ (
    .A(B[2]),
    .B(A[2]),
    .C(_03_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _14_ (
    .A(B[3]),
    .B(A[3]),
    .C(_05_),
    .X(Cout)
  );
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(Cin),
    .B(_00_),
    .Y(S[0])
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(_01_),
    .B(_02_),
    .Y(S[1])
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(_03_),
    .B(_04_),
    .Y(S[2])
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(_05_),
    .B(_06_),
    .Y(S[3])
  );
  assign Ci[0] = Cin;
endmodule

module eb_adder(A, B, Cin, VDD, VSS, Y, Cout);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  input Cin;
  wire Cin;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  output [7:0] Y;
  wire [7:0] Y;
  output Cout;
  wire Cout;
  wire x;
  CLA4bit C1 (
    .A(A[3:0]),
    .B(B[3:0]),
    .Cin(Cin),
    .Cout(x),
    .S(Y[3:0]),
    .VDD(VDD),
    .VSS(VSS)
  );
  CLA4bit C2 (
    .A(A[7:4]),
    .B(B[7:4]),
    .Cin(x),
    .Cout(Cout),
    .S(Y[7:4]),
    .VDD(VDD),
    .VSS(VSS)
  );
endmodule

module eb_adder_top(A, B, Cin, VDD, VSS, Y, Cout);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  input Cin;
  wire Cin;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  output [7:0] Y;
  wire [7:0] Y;
  output Cout;
  wire Cout;
  eb_adder UUT (
    .A(A),
    .B(B),
    .Cin(Cin),
    .Cout(Cout),
    .VDD(VDD),
    .VSS(VSS),
    .Y(Y)
  );
endmodule
