/* Generated by Yosys 0.57+125 (git sha1 d5053033e, g++ 11.5.0 -fPIC -O3) */

(* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:26.1-41.10" *)
module CLA4bit(A, B, Cin, VDD, VSS, S, Cout);
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:27.14-27.15" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:27.16-27.17" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:28.9-28.12" *)
  input Cin;
  wire Cin;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:29.9-29.12" *)
  input VDD;
  wire VDD;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:29.13-29.16" *)
  input VSS;
  wire VSS;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:30.16-30.17" *)
  output [3:0] S;
  wire [3:0] S;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:31.10-31.14" *)
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:32.14-32.16" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] Ci;
  sky130_fd_sc_hd__xnor2_1 _07_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__maj3_1 _08_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(B[1]),
    .B(A[1]),
    .C(_01_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _11_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _12_ (
    .A(B[2]),
    .B(A[2]),
    .C(_03_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _14_ (
    .A(B[3]),
    .B(A[3]),
    .C(_05_),
    .X(Cout)
  );
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(Cin),
    .B(_00_),
    .Y(S[0])
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(_01_),
    .B(_02_),
    .Y(S[1])
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(_03_),
    .B(_04_),
    .Y(S[2])
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(_05_),
    .B(_06_),
    .Y(S[3])
  );
  assign Ci[0] = Cin;
endmodule

(* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:13.1-24.10" *)
module eb_adder(A, B, Cin, VDD, VSS, Y, Cout);
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:14.12-14.13" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:14.14-14.15" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:15.7-15.10" *)
  input Cin;
  wire Cin;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:16.7-16.10" *)
  input VDD;
  wire VDD;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:16.11-16.14" *)
  input VSS;
  wire VSS;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:17.13-17.14" *)
  output [7:0] Y;
  wire [7:0] Y;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:18.8-18.12" *)
  output Cout;
  wire Cout;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:19.6-19.7" *)
  wire x;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:21.9-21.47" *)
  CLA4bit C1 (
    .A(A[3:0]),
    .B(B[3:0]),
    .Cin(Cin),
    .Cout(x),
    .S(Y[3:0]),
    .VDD(VDD),
    .VSS(VSS)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:22.9-22.48" *)
  CLA4bit C2 (
    .A(A[7:4]),
    .B(B[7:4]),
    .Cin(x),
    .Cout(Cout),
    .S(Y[7:4]),
    .VDD(VDD),
    .VSS(VSS)
  );
endmodule

(* top =  1  *)
(* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:1.1-10.10" *)
module eb_adder_top(A, B, Cin, VDD, VSS, Y, Cout);
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:2.12-2.13" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:2.14-2.15" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:3.7-3.10" *)
  input Cin;
  wire Cin;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:4.7-4.10" *)
  input VDD;
  wire VDD;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:4.11-4.14" *)
  input VSS;
  wire VSS;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:5.13-5.14" *)
  output [7:0] Y;
  wire [7:0] Y;
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:6.8-6.12" *)
  output Cout;
  wire Cout;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/arumukamganesmoorthe/ME/digital_design/eight_bit_CLA/rtl/eight_bit_CLA.v:8.10-8.80" *)
  eb_adder UUT (
    .A(A),
    .B(B),
    .Cin(Cin),
    .Cout(Cout),
    .VDD(VDD),
    .VSS(VSS),
    .Y(Y)
  );
endmodule
