/* Generated by Yosys 0.57+125 (git sha1 d5053033e, g++ 11.5.0 -fPIC -O3) */

module \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000100000 (A, B, Cin, Sum, Cout);
  input [31:0] A;
  wire [31:0] A;
  input [31:0] B;
  wire [31:0] B;
  input Cin;
  wire Cin;
  output [31:0] Sum;
  wire [31:0] Sum;
  output Cout;
  wire Cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire [32:0] C;
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__xnor2_1 _164_ (
    .A(Cin),
    .B(_162_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _165_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_000_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _166_ (
    .A(B[1]),
    .SLEEP(A[1]),
    .X(_001_)
  );
  sky130_fd_sc_hd__and2_0 _167_ (
    .A(B[1]),
    .B(A[1]),
    .X(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _169_ (
    .A(_001_),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _170_ (
    .A(_000_),
    .B(_004_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xor2_1 _172_ (
    .A(B[2]),
    .B(A[2]),
    .X(_006_)
  );
  sky130_fd_sc_hd__a21oi_1 _173_ (
    .A1(_000_),
    .A2(_001_),
    .B1(_002_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _174_ (
    .A(_006_),
    .B(_007_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _176_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a221oi_1 _177_ (
    .A1(B[2]),
    .A2(A[2]),
    .B1(_000_),
    .B2(_001_),
    .C1(_002_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o21a_1 _178_ (
    .A1(_005_),
    .A2(_010_),
    .B1(_009_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nor3_1 _179_ (
    .A(_005_),
    .B(_009_),
    .C(_010_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(_011_),
    .B(_012_),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _181_ (
    .A(B[4]),
    .SLEEP(A[4]),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _184_ (
    .A1(B[3]),
    .A2(A[3]),
    .B1(_012_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xor2_1 _185_ (
    .A(_015_),
    .B(_016_),
    .X(Sum[4])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _186_ (
    .A(B[5]),
    .SLEEP(A[5]),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_0 _187_ (
    .A(B[5]),
    .B(A[5]),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(_017_),
    .B(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o311ai_0 _190_ (
    .A1(_005_),
    .A2(_009_),
    .A3(_010_),
    .B1(_014_),
    .C1(_008_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__and2_0 _191_ (
    .A(_013_),
    .B(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _192_ (
    .A(_020_),
    .B(_022_),
    .Y(Sum[5])
  );
  sky130_fd_sc_hd__a21oi_1 _193_ (
    .A1(_017_),
    .A2(_022_),
    .B1(_018_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__and2_0 _195_ (
    .A(B[6]),
    .B(A[6]),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _196_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _197_ (
    .A(_023_),
    .B(_026_),
    .Y(Sum[6])
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2b_1 _200_ (
    .A_N(_027_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a311oi_1 _201_ (
    .A1(_013_),
    .A2(_017_),
    .A3(_021_),
    .B1(_025_),
    .C1(_018_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _202_ (
    .A(_024_),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _203_ (
    .A(_029_),
    .B(_031_),
    .Y(Sum[7])
  );
  sky130_fd_sc_hd__nor2_1 _204_ (
    .A(B[8]),
    .B(A[8]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__and2_0 _205_ (
    .A(B[8]),
    .B(A[8]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(B[8]),
    .B(A[8]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o31a_1 _207_ (
    .A1(_024_),
    .A2(_027_),
    .A3(_030_),
    .B1(_028_),
    .X(_035_)
  );
  sky130_fd_sc_hd__or3_1 _208_ (
    .A(_032_),
    .B(_033_),
    .C(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__o21ai_0 _209_ (
    .A1(_032_),
    .A2(_033_),
    .B1(_035_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__and2_0 _210_ (
    .A(_036_),
    .B(_037_),
    .X(Sum[8])
  );
  sky130_fd_sc_hd__nor2_1 _211_ (
    .A(B[9]),
    .B(A[9]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(B[9]),
    .B(A[9]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2b_1 _213_ (
    .A(_038_),
    .B_N(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o311a_1 _214_ (
    .A1(_024_),
    .A2(_027_),
    .A3(_030_),
    .B1(_034_),
    .C1(_028_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(_032_),
    .B(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xor2_1 _216_ (
    .A(_040_),
    .B(_042_),
    .X(Sum[9])
  );
  sky130_fd_sc_hd__nor2_1 _217_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2b_1 _219_ (
    .A_N(_043_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a31oi_1 _220_ (
    .A1(_034_),
    .A2(_036_),
    .A3(_039_),
    .B1(_038_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2b_1 _221_ (
    .A_N(_045_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _222_ (
    .A(_045_),
    .B(_046_),
    .Y(Sum[10])
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2b_1 _225_ (
    .A_N(_048_),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o311a_1 _226_ (
    .A1(_032_),
    .A2(_038_),
    .A3(_041_),
    .B1(_044_),
    .C1(_039_),
    .X(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(_043_),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xnor2_1 _228_ (
    .A(_050_),
    .B(_052_),
    .Y(Sum[11])
  );
  sky130_fd_sc_hd__nor2_1 _229_ (
    .A(B[12]),
    .B(A[12]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(B[12]),
    .B(A[12]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2b_1 _231_ (
    .A(_053_),
    .B_N(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _232_ (
    .A(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a31oi_1 _233_ (
    .A1(_044_),
    .A2(_047_),
    .A3(_049_),
    .B1(_048_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _234_ (
    .A(_056_),
    .B(_057_),
    .Y(Sum[12])
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(B[13]),
    .B(A[13]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(B[13]),
    .B(A[13]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2b_1 _237_ (
    .A(_058_),
    .B_N(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21o_1 _238_ (
    .A1(_049_),
    .A2(_054_),
    .B1(_053_),
    .X(_061_)
  );
  sky130_fd_sc_hd__o41ai_1 _239_ (
    .A1(_043_),
    .A2(_050_),
    .A3(_051_),
    .A4(_056_),
    .B1(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xor2_1 _240_ (
    .A(_060_),
    .B(_062_),
    .X(Sum[13])
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(B[14]),
    .B(A[14]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(B[14]),
    .B(A[14]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2b_1 _243_ (
    .A(_063_),
    .B_N(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21ai_0 _244_ (
    .A1(_054_),
    .A2(_058_),
    .B1(_059_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a31oi_1 _245_ (
    .A1(_055_),
    .A2(_057_),
    .A3(_060_),
    .B1(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xnor2_1 _246_ (
    .A(_065_),
    .B(_067_),
    .Y(Sum[14])
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(B[15]),
    .B(A[15]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(B[15]),
    .B(A[15]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2b_1 _249_ (
    .A(_068_),
    .B_N(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a21oi_1 _250_ (
    .A1(_059_),
    .A2(_064_),
    .B1(_063_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a31oi_1 _251_ (
    .A1(_060_),
    .A2(_062_),
    .A3(_065_),
    .B1(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _252_ (
    .A(_070_),
    .B(_072_),
    .Y(Sum[15])
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(B[16]),
    .B(A[16]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(B[16]),
    .B(A[16]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2b_1 _255_ (
    .A(_073_),
    .B_N(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o211ai_1 _256_ (
    .A1(_063_),
    .A2(_067_),
    .B1(_069_),
    .C1(_064_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o21ai_0 _257_ (
    .A1(B[15]),
    .A2(A[15]),
    .B1(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _258_ (
    .A(_075_),
    .B(_077_),
    .Y(Sum[16])
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(B[17]),
    .B(A[17]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xnor2_1 _260_ (
    .A(B[17]),
    .B(A[17]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o211a_1 _261_ (
    .A1(_068_),
    .A2(_072_),
    .B1(_074_),
    .C1(_069_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _262_ (
    .A(_073_),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor3_1 _263_ (
    .A(_073_),
    .B(_079_),
    .C(_080_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xnor2_1 _264_ (
    .A(_079_),
    .B(_081_),
    .Y(Sum[17])
  );
  sky130_fd_sc_hd__nor2_1 _265_ (
    .A(B[18]),
    .B(A[18]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _266_ (
    .A(B[18]),
    .B(A[18]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2b_1 _267_ (
    .A(_083_),
    .B_N(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o31a_1 _268_ (
    .A1(_073_),
    .A2(_079_),
    .A3(_080_),
    .B1(_078_),
    .X(_086_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_085_),
    .B(_086_),
    .Y(Sum[18])
  );
  sky130_fd_sc_hd__nor2_1 _270_ (
    .A(B[19]),
    .B(A[19]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xor2_1 _271_ (
    .A(B[19]),
    .B(A[19]),
    .X(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(_078_),
    .B(_084_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o21ai_0 _273_ (
    .A1(_083_),
    .A2(_086_),
    .B1(_084_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o221ai_1 _274_ (
    .A1(B[18]),
    .A2(A[18]),
    .B1(_082_),
    .B2(_089_),
    .C1(_088_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xor2_1 _275_ (
    .A(_088_),
    .B(_090_),
    .X(Sum[19])
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(B[20]),
    .B(A[20]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(B[20]),
    .B(A[20]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2b_1 _278_ (
    .A_N(_092_),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _279_ (
    .A(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(_085_),
    .B(_088_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(_084_),
    .B(_087_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _282_ (
    .A1(B[19]),
    .A2(A[19]),
    .B1(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o21ai_0 _283_ (
    .A1(_086_),
    .A2(_096_),
    .B1(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__xnor2_1 _284_ (
    .A(_094_),
    .B(_099_),
    .Y(Sum[20])
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(B[21]),
    .B(A[21]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _286_ (
    .A(B[21]),
    .B(A[21]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2b_1 _287_ (
    .A(_100_),
    .B_N(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _288_ (
    .A(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a22oi_1 _289_ (
    .A1(B[19]),
    .A2(A[19]),
    .B1(B[20]),
    .B2(A[20]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a21oi_1 _290_ (
    .A1(_091_),
    .A2(_104_),
    .B1(_092_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(_102_),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a211oi_1 _292_ (
    .A1(_091_),
    .A2(_104_),
    .B1(_103_),
    .C1(_092_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_106_),
    .B(_107_),
    .Y(Sum[21])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _294_ (
    .A(B[22]),
    .SLEEP(A[22]),
    .X(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(B[22]),
    .B(A[22]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__and2_0 _296_ (
    .A(_108_),
    .B(_109_),
    .X(_110_)
  );
  sky130_fd_sc_hd__o21ai_0 _297_ (
    .A1(_093_),
    .A2(_100_),
    .B1(_101_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a31oi_1 _298_ (
    .A1(_095_),
    .A2(_099_),
    .A3(_102_),
    .B1(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _299_ (
    .A(_110_),
    .B(_112_),
    .Y(Sum[22])
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(B[23]),
    .B(A[23]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xor2_1 _301_ (
    .A(B[23]),
    .B(A[23]),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(_101_),
    .B(_109_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o21ai_0 _303_ (
    .A1(_107_),
    .A2(_115_),
    .B1(_108_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o211a_1 _304_ (
    .A1(_107_),
    .A2(_115_),
    .B1(_114_),
    .C1(_108_),
    .X(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _305_ (
    .A(_114_),
    .B(_116_),
    .Y(Sum[23])
  );
  sky130_fd_sc_hd__xor2_1 _306_ (
    .A(B[24]),
    .B(A[24]),
    .X(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(_110_),
    .B(_114_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _308_ (
    .A(_109_),
    .B(_113_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21oi_1 _309_ (
    .A1(B[23]),
    .A2(A[23]),
    .B1(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o21a_1 _310_ (
    .A1(_112_),
    .A2(_119_),
    .B1(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _311_ (
    .A(_118_),
    .B(_122_),
    .Y(Sum[24])
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(B[25]),
    .B(A[25]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xor2_1 _313_ (
    .A(B[25]),
    .B(A[25]),
    .X(_124_)
  );
  sky130_fd_sc_hd__a22o_1 _314_ (
    .A1(B[23]),
    .A2(A[23]),
    .B1(B[24]),
    .B2(A[24]),
    .X(_125_)
  );
  sky130_fd_sc_hd__o22ai_1 _315_ (
    .A1(B[24]),
    .A2(A[24]),
    .B1(_117_),
    .B2(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o221ai_1 _316_ (
    .A1(B[24]),
    .A2(A[24]),
    .B1(_117_),
    .B2(_125_),
    .C1(_124_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _317_ (
    .A(_124_),
    .B(_126_),
    .Y(Sum[25])
  );
  sky130_fd_sc_hd__o211ai_1 _318_ (
    .A1(B[25]),
    .A2(A[25]),
    .B1(B[24]),
    .C1(A[24]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _319_ (
    .A(_118_),
    .B(_124_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o211a_1 _320_ (
    .A1(_122_),
    .A2(_129_),
    .B1(_128_),
    .C1(_123_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nor2_1 _321_ (
    .A(B[26]),
    .B(A[26]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(B[26]),
    .B(A[26]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2b_1 _323_ (
    .A(_131_),
    .B_N(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xnor2_1 _324_ (
    .A(_130_),
    .B(_133_),
    .Y(Sum[26])
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(B[27]),
    .B(A[27]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _326_ (
    .A(B[27]),
    .B(A[27]),
    .X(_135_)
  );
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a31oi_1 _328_ (
    .A1(_123_),
    .A2(_127_),
    .A3(_132_),
    .B1(_131_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_135_),
    .B(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a311oi_1 _330_ (
    .A1(_123_),
    .A2(_127_),
    .A3(_132_),
    .B1(_136_),
    .C1(_131_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_138_),
    .B(_139_),
    .Y(Sum[27])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _332_ (
    .A(B[28]),
    .SLEEP(A[28]),
    .X(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(B[28]),
    .B(A[28]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(_132_),
    .B(_134_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21ai_0 _336_ (
    .A1(B[27]),
    .A2(A[27]),
    .B1(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(_133_),
    .B(_135_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _338_ (
    .A1(_130_),
    .A2(_145_),
    .B1(_144_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__xnor2_1 _339_ (
    .A(_142_),
    .B(_146_),
    .Y(Sum[28])
  );
  sky130_fd_sc_hd__nor2_1 _340_ (
    .A(B[29]),
    .B(A[29]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _341_ (
    .A(B[29]),
    .B(A[29]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2b_1 _342_ (
    .A(_147_),
    .B_N(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(_134_),
    .B(_141_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _344_ (
    .A1(_139_),
    .A2(_150_),
    .B1(_140_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o211ai_1 _345_ (
    .A1(_139_),
    .A2(_150_),
    .B1(_149_),
    .C1(_140_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__xnor2_1 _346_ (
    .A(_149_),
    .B(_151_),
    .Y(Sum[29])
  );
  sky130_fd_sc_hd__o21ai_0 _347_ (
    .A1(_141_),
    .A2(_147_),
    .B1(_148_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a41oi_1 _348_ (
    .A1(_140_),
    .A2(_141_),
    .A3(_146_),
    .A4(_149_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(B[30]),
    .B(A[30]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(B[30]),
    .B(A[30]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2b_1 _351_ (
    .A(_155_),
    .B_N(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _352_ (
    .A(_154_),
    .B(_157_),
    .Y(Sum[30])
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(B[31]),
    .B(A[31]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xnor2_1 _354_ (
    .A(B[31]),
    .B(A[31]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a31oi_1 _355_ (
    .A1(_148_),
    .A2(_152_),
    .A3(_156_),
    .B1(_155_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__xnor2_1 _356_ (
    .A(_159_),
    .B(_160_),
    .Y(Sum[31])
  );
  sky130_fd_sc_hd__o211ai_1 _357_ (
    .A1(_154_),
    .A2(_155_),
    .B1(_156_),
    .C1(_158_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o21a_1 _358_ (
    .A1(B[31]),
    .A2(A[31]),
    .B1(_161_),
    .X(Cout)
  );
  assign { C[32], C[0] } = { Cout, Cin };
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000000010 (a0, a1, a2, s, co);
  input [1:0] a0;
  wire [1:0] a0;
  input [1:0] a1;
  wire [1:0] a1;
  input [1:0] a2;
  wire [1:0] a2;
  output [1:0] s;
  wire [1:0] s;
  output [1:0] co;
  wire [1:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000000100 (a0, a1, a2, s, co);
  input [3:0] a0;
  wire [3:0] a0;
  input [3:0] a1;
  wire [3:0] a1;
  input [3:0] a2;
  wire [3:0] a2;
  output [3:0] s;
  wire [3:0] s;
  output [3:0] co;
  wire [3:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000000110 (a0, a1, a2, s, co);
  input [5:0] a0;
  wire [5:0] a0;
  input [5:0] a1;
  wire [5:0] a1;
  input [5:0] a2;
  wire [5:0] a2;
  output [5:0] s;
  wire [5:0] s;
  output [5:0] co;
  wire [5:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000001000 (a0, a1, a2, s, co);
  input [7:0] a0;
  wire [7:0] a0;
  input [7:0] a1;
  wire [7:0] a1;
  input [7:0] a2;
  wire [7:0] a2;
  output [7:0] s;
  wire [7:0] s;
  output [7:0] co;
  wire [7:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000001010 (a0, a1, a2, s, co);
  input [9:0] a0;
  wire [9:0] a0;
  input [9:0] a1;
  wire [9:0] a1;
  input [9:0] a2;
  wire [9:0] a2;
  output [9:0] s;
  wire [9:0] s;
  output [9:0] co;
  wire [9:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000001100 (a0, a1, a2, s, co);
  input [11:0] a0;
  wire [11:0] a0;
  input [11:0] a1;
  wire [11:0] a1;
  input [11:0] a2;
  wire [11:0] a2;
  output [11:0] s;
  wire [11:0] s;
  output [11:0] co;
  wire [11:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[10].fa0  (
    .a(a0[10]),
    .b(a1[10]),
    .c(a2[10]),
    .ca(co[10]),
    .s(s[10])
  );
  fa \fa_array[11].fa0  (
    .a(a0[11]),
    .b(a1[11]),
    .c(a2[11]),
    .ca(co[11]),
    .s(s[11])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000001110 (a0, a1, a2, s, co);
  input [13:0] a0;
  wire [13:0] a0;
  input [13:0] a1;
  wire [13:0] a1;
  input [13:0] a2;
  wire [13:0] a2;
  output [13:0] s;
  wire [13:0] s;
  output [13:0] co;
  wire [13:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[10].fa0  (
    .a(a0[10]),
    .b(a1[10]),
    .c(a2[10]),
    .ca(co[10]),
    .s(s[10])
  );
  fa \fa_array[11].fa0  (
    .a(a0[11]),
    .b(a1[11]),
    .c(a2[11]),
    .ca(co[11]),
    .s(s[11])
  );
  fa \fa_array[12].fa0  (
    .a(a0[12]),
    .b(a1[12]),
    .c(a2[12]),
    .ca(co[12]),
    .s(s[12])
  );
  fa \fa_array[13].fa0  (
    .a(a0[13]),
    .b(a1[13]),
    .c(a2[13]),
    .ca(co[13]),
    .s(s[13])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000010010 (a0, a1, a2, s, co);
  input [17:0] a0;
  wire [17:0] a0;
  input [17:0] a1;
  wire [17:0] a1;
  input [17:0] a2;
  wire [17:0] a2;
  output [17:0] s;
  wire [17:0] s;
  output [17:0] co;
  wire [17:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[10].fa0  (
    .a(a0[10]),
    .b(a1[10]),
    .c(a2[10]),
    .ca(co[10]),
    .s(s[10])
  );
  fa \fa_array[11].fa0  (
    .a(a0[11]),
    .b(a1[11]),
    .c(a2[11]),
    .ca(co[11]),
    .s(s[11])
  );
  fa \fa_array[12].fa0  (
    .a(a0[12]),
    .b(a1[12]),
    .c(a2[12]),
    .ca(co[12]),
    .s(s[12])
  );
  fa \fa_array[13].fa0  (
    .a(a0[13]),
    .b(a1[13]),
    .c(a2[13]),
    .ca(co[13]),
    .s(s[13])
  );
  fa \fa_array[14].fa0  (
    .a(a0[14]),
    .b(a1[14]),
    .c(a2[14]),
    .ca(co[14]),
    .s(s[14])
  );
  fa \fa_array[15].fa0  (
    .a(a0[15]),
    .b(a1[15]),
    .c(a2[15]),
    .ca(co[15]),
    .s(s[15])
  );
  fa \fa_array[16].fa0  (
    .a(a0[16]),
    .b(a1[16]),
    .c(a2[16]),
    .ca(co[16]),
    .s(s[16])
  );
  fa \fa_array[17].fa0  (
    .a(a0[17]),
    .b(a1[17]),
    .c(a2[17]),
    .ca(co[17]),
    .s(s[17])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000010011 (a0, a1, a2, s, co);
  input [18:0] a0;
  wire [18:0] a0;
  input [18:0] a1;
  wire [18:0] a1;
  input [18:0] a2;
  wire [18:0] a2;
  output [18:0] s;
  wire [18:0] s;
  output [18:0] co;
  wire [18:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[10].fa0  (
    .a(a0[10]),
    .b(a1[10]),
    .c(a2[10]),
    .ca(co[10]),
    .s(s[10])
  );
  fa \fa_array[11].fa0  (
    .a(a0[11]),
    .b(a1[11]),
    .c(a2[11]),
    .ca(co[11]),
    .s(s[11])
  );
  fa \fa_array[12].fa0  (
    .a(a0[12]),
    .b(a1[12]),
    .c(a2[12]),
    .ca(co[12]),
    .s(s[12])
  );
  fa \fa_array[13].fa0  (
    .a(a0[13]),
    .b(a1[13]),
    .c(a2[13]),
    .ca(co[13]),
    .s(s[13])
  );
  fa \fa_array[14].fa0  (
    .a(a0[14]),
    .b(a1[14]),
    .c(a2[14]),
    .ca(co[14]),
    .s(s[14])
  );
  fa \fa_array[15].fa0  (
    .a(a0[15]),
    .b(a1[15]),
    .c(a2[15]),
    .ca(co[15]),
    .s(s[15])
  );
  fa \fa_array[16].fa0  (
    .a(a0[16]),
    .b(a1[16]),
    .c(a2[16]),
    .ca(co[16]),
    .s(s[16])
  );
  fa \fa_array[17].fa0  (
    .a(a0[17]),
    .b(a1[17]),
    .c(a2[17]),
    .ca(co[17]),
    .s(s[17])
  );
  fa \fa_array[18].fa0  (
    .a(a0[18]),
    .b(a1[18]),
    .c(a2[18]),
    .ca(co[18]),
    .s(s[18])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000010100 (a0, a1, a2, s, co);
  input [19:0] a0;
  wire [19:0] a0;
  input [19:0] a1;
  wire [19:0] a1;
  input [19:0] a2;
  wire [19:0] a2;
  output [19:0] s;
  wire [19:0] s;
  output [19:0] co;
  wire [19:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[10].fa0  (
    .a(a0[10]),
    .b(a1[10]),
    .c(a2[10]),
    .ca(co[10]),
    .s(s[10])
  );
  fa \fa_array[11].fa0  (
    .a(a0[11]),
    .b(a1[11]),
    .c(a2[11]),
    .ca(co[11]),
    .s(s[11])
  );
  fa \fa_array[12].fa0  (
    .a(a0[12]),
    .b(a1[12]),
    .c(a2[12]),
    .ca(co[12]),
    .s(s[12])
  );
  fa \fa_array[13].fa0  (
    .a(a0[13]),
    .b(a1[13]),
    .c(a2[13]),
    .ca(co[13]),
    .s(s[13])
  );
  fa \fa_array[14].fa0  (
    .a(a0[14]),
    .b(a1[14]),
    .c(a2[14]),
    .ca(co[14]),
    .s(s[14])
  );
  fa \fa_array[15].fa0  (
    .a(a0[15]),
    .b(a1[15]),
    .c(a2[15]),
    .ca(co[15]),
    .s(s[15])
  );
  fa \fa_array[16].fa0  (
    .a(a0[16]),
    .b(a1[16]),
    .c(a2[16]),
    .ca(co[16]),
    .s(s[16])
  );
  fa \fa_array[17].fa0  (
    .a(a0[17]),
    .b(a1[17]),
    .c(a2[17]),
    .ca(co[17]),
    .s(s[17])
  );
  fa \fa_array[18].fa0  (
    .a(a0[18]),
    .b(a1[18]),
    .c(a2[18]),
    .ca(co[18]),
    .s(s[18])
  );
  fa \fa_array[19].fa0  (
    .a(a0[19]),
    .b(a1[19]),
    .c(a2[19]),
    .ca(co[19]),
    .s(s[19])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000011000 (a0, a1, a2, s, co);
  input [23:0] a0;
  wire [23:0] a0;
  input [23:0] a1;
  wire [23:0] a1;
  input [23:0] a2;
  wire [23:0] a2;
  output [23:0] s;
  wire [23:0] s;
  output [23:0] co;
  wire [23:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[10].fa0  (
    .a(a0[10]),
    .b(a1[10]),
    .c(a2[10]),
    .ca(co[10]),
    .s(s[10])
  );
  fa \fa_array[11].fa0  (
    .a(a0[11]),
    .b(a1[11]),
    .c(a2[11]),
    .ca(co[11]),
    .s(s[11])
  );
  fa \fa_array[12].fa0  (
    .a(a0[12]),
    .b(a1[12]),
    .c(a2[12]),
    .ca(co[12]),
    .s(s[12])
  );
  fa \fa_array[13].fa0  (
    .a(a0[13]),
    .b(a1[13]),
    .c(a2[13]),
    .ca(co[13]),
    .s(s[13])
  );
  fa \fa_array[14].fa0  (
    .a(a0[14]),
    .b(a1[14]),
    .c(a2[14]),
    .ca(co[14]),
    .s(s[14])
  );
  fa \fa_array[15].fa0  (
    .a(a0[15]),
    .b(a1[15]),
    .c(a2[15]),
    .ca(co[15]),
    .s(s[15])
  );
  fa \fa_array[16].fa0  (
    .a(a0[16]),
    .b(a1[16]),
    .c(a2[16]),
    .ca(co[16]),
    .s(s[16])
  );
  fa \fa_array[17].fa0  (
    .a(a0[17]),
    .b(a1[17]),
    .c(a2[17]),
    .ca(co[17]),
    .s(s[17])
  );
  fa \fa_array[18].fa0  (
    .a(a0[18]),
    .b(a1[18]),
    .c(a2[18]),
    .ca(co[18]),
    .s(s[18])
  );
  fa \fa_array[19].fa0  (
    .a(a0[19]),
    .b(a1[19]),
    .c(a2[19]),
    .ca(co[19]),
    .s(s[19])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[20].fa0  (
    .a(a0[20]),
    .b(a1[20]),
    .c(a2[20]),
    .ca(co[20]),
    .s(s[20])
  );
  fa \fa_array[21].fa0  (
    .a(a0[21]),
    .b(a1[21]),
    .c(a2[21]),
    .ca(co[21]),
    .s(s[21])
  );
  fa \fa_array[22].fa0  (
    .a(a0[22]),
    .b(a1[22]),
    .c(a2[22]),
    .ca(co[22]),
    .s(s[22])
  );
  fa \fa_array[23].fa0  (
    .a(a0[23]),
    .b(a1[23]),
    .c(a2[23]),
    .ca(co[23]),
    .s(s[23])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000011001 (a0, a1, a2, s, co);
  input [24:0] a0;
  wire [24:0] a0;
  input [24:0] a1;
  wire [24:0] a1;
  input [24:0] a2;
  wire [24:0] a2;
  output [24:0] s;
  wire [24:0] s;
  output [24:0] co;
  wire [24:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[10].fa0  (
    .a(a0[10]),
    .b(a1[10]),
    .c(a2[10]),
    .ca(co[10]),
    .s(s[10])
  );
  fa \fa_array[11].fa0  (
    .a(a0[11]),
    .b(a1[11]),
    .c(a2[11]),
    .ca(co[11]),
    .s(s[11])
  );
  fa \fa_array[12].fa0  (
    .a(a0[12]),
    .b(a1[12]),
    .c(a2[12]),
    .ca(co[12]),
    .s(s[12])
  );
  fa \fa_array[13].fa0  (
    .a(a0[13]),
    .b(a1[13]),
    .c(a2[13]),
    .ca(co[13]),
    .s(s[13])
  );
  fa \fa_array[14].fa0  (
    .a(a0[14]),
    .b(a1[14]),
    .c(a2[14]),
    .ca(co[14]),
    .s(s[14])
  );
  fa \fa_array[15].fa0  (
    .a(a0[15]),
    .b(a1[15]),
    .c(a2[15]),
    .ca(co[15]),
    .s(s[15])
  );
  fa \fa_array[16].fa0  (
    .a(a0[16]),
    .b(a1[16]),
    .c(a2[16]),
    .ca(co[16]),
    .s(s[16])
  );
  fa \fa_array[17].fa0  (
    .a(a0[17]),
    .b(a1[17]),
    .c(a2[17]),
    .ca(co[17]),
    .s(s[17])
  );
  fa \fa_array[18].fa0  (
    .a(a0[18]),
    .b(a1[18]),
    .c(a2[18]),
    .ca(co[18]),
    .s(s[18])
  );
  fa \fa_array[19].fa0  (
    .a(a0[19]),
    .b(a1[19]),
    .c(a2[19]),
    .ca(co[19]),
    .s(s[19])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[20].fa0  (
    .a(a0[20]),
    .b(a1[20]),
    .c(a2[20]),
    .ca(co[20]),
    .s(s[20])
  );
  fa \fa_array[21].fa0  (
    .a(a0[21]),
    .b(a1[21]),
    .c(a2[21]),
    .ca(co[21]),
    .s(s[21])
  );
  fa \fa_array[22].fa0  (
    .a(a0[22]),
    .b(a1[22]),
    .c(a2[22]),
    .ca(co[22]),
    .s(s[22])
  );
  fa \fa_array[23].fa0  (
    .a(a0[23]),
    .b(a1[23]),
    .c(a2[23]),
    .ca(co[23]),
    .s(s[23])
  );
  fa \fa_array[24].fa0  (
    .a(a0[24]),
    .b(a1[24]),
    .c(a2[24]),
    .ca(co[24]),
    .s(s[24])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setfa\N=s32'00000000000000000000000000011010 (a0, a1, a2, s, co);
  input [25:0] a0;
  wire [25:0] a0;
  input [25:0] a1;
  wire [25:0] a1;
  input [25:0] a2;
  wire [25:0] a2;
  output [25:0] s;
  wire [25:0] s;
  output [25:0] co;
  wire [25:0] co;
  fa \fa_array[0].fa0  (
    .a(a0[0]),
    .b(a1[0]),
    .c(a2[0]),
    .ca(co[0]),
    .s(s[0])
  );
  fa \fa_array[10].fa0  (
    .a(a0[10]),
    .b(a1[10]),
    .c(a2[10]),
    .ca(co[10]),
    .s(s[10])
  );
  fa \fa_array[11].fa0  (
    .a(a0[11]),
    .b(a1[11]),
    .c(a2[11]),
    .ca(co[11]),
    .s(s[11])
  );
  fa \fa_array[12].fa0  (
    .a(a0[12]),
    .b(a1[12]),
    .c(a2[12]),
    .ca(co[12]),
    .s(s[12])
  );
  fa \fa_array[13].fa0  (
    .a(a0[13]),
    .b(a1[13]),
    .c(a2[13]),
    .ca(co[13]),
    .s(s[13])
  );
  fa \fa_array[14].fa0  (
    .a(a0[14]),
    .b(a1[14]),
    .c(a2[14]),
    .ca(co[14]),
    .s(s[14])
  );
  fa \fa_array[15].fa0  (
    .a(a0[15]),
    .b(a1[15]),
    .c(a2[15]),
    .ca(co[15]),
    .s(s[15])
  );
  fa \fa_array[16].fa0  (
    .a(a0[16]),
    .b(a1[16]),
    .c(a2[16]),
    .ca(co[16]),
    .s(s[16])
  );
  fa \fa_array[17].fa0  (
    .a(a0[17]),
    .b(a1[17]),
    .c(a2[17]),
    .ca(co[17]),
    .s(s[17])
  );
  fa \fa_array[18].fa0  (
    .a(a0[18]),
    .b(a1[18]),
    .c(a2[18]),
    .ca(co[18]),
    .s(s[18])
  );
  fa \fa_array[19].fa0  (
    .a(a0[19]),
    .b(a1[19]),
    .c(a2[19]),
    .ca(co[19]),
    .s(s[19])
  );
  fa \fa_array[1].fa0  (
    .a(a0[1]),
    .b(a1[1]),
    .c(a2[1]),
    .ca(co[1]),
    .s(s[1])
  );
  fa \fa_array[20].fa0  (
    .a(a0[20]),
    .b(a1[20]),
    .c(a2[20]),
    .ca(co[20]),
    .s(s[20])
  );
  fa \fa_array[21].fa0  (
    .a(a0[21]),
    .b(a1[21]),
    .c(a2[21]),
    .ca(co[21]),
    .s(s[21])
  );
  fa \fa_array[22].fa0  (
    .a(a0[22]),
    .b(a1[22]),
    .c(a2[22]),
    .ca(co[22]),
    .s(s[22])
  );
  fa \fa_array[23].fa0  (
    .a(a0[23]),
    .b(a1[23]),
    .c(a2[23]),
    .ca(co[23]),
    .s(s[23])
  );
  fa \fa_array[24].fa0  (
    .a(a0[24]),
    .b(a1[24]),
    .c(a2[24]),
    .ca(co[24]),
    .s(s[24])
  );
  fa \fa_array[25].fa0  (
    .a(a0[25]),
    .b(a1[25]),
    .c(a2[25]),
    .ca(co[25]),
    .s(s[25])
  );
  fa \fa_array[2].fa0  (
    .a(a0[2]),
    .b(a1[2]),
    .c(a2[2]),
    .ca(co[2]),
    .s(s[2])
  );
  fa \fa_array[3].fa0  (
    .a(a0[3]),
    .b(a1[3]),
    .c(a2[3]),
    .ca(co[3]),
    .s(s[3])
  );
  fa \fa_array[4].fa0  (
    .a(a0[4]),
    .b(a1[4]),
    .c(a2[4]),
    .ca(co[4]),
    .s(s[4])
  );
  fa \fa_array[5].fa0  (
    .a(a0[5]),
    .b(a1[5]),
    .c(a2[5]),
    .ca(co[5]),
    .s(s[5])
  );
  fa \fa_array[6].fa0  (
    .a(a0[6]),
    .b(a1[6]),
    .c(a2[6]),
    .ca(co[6]),
    .s(s[6])
  );
  fa \fa_array[7].fa0  (
    .a(a0[7]),
    .b(a1[7]),
    .c(a2[7]),
    .ca(co[7]),
    .s(s[7])
  );
  fa \fa_array[8].fa0  (
    .a(a0[8]),
    .b(a1[8]),
    .c(a2[8]),
    .ca(co[8]),
    .s(s[8])
  );
  fa \fa_array[9].fa0  (
    .a(a0[9]),
    .b(a1[9]),
    .c(a2[9]),
    .ca(co[9]),
    .s(s[9])
  );
endmodule

module \$paramod\setha\N=s32'00000000000000000000000000000011 (a0, a1, s, co);
  input [2:0] a0;
  wire [2:0] a0;
  input [2:0] a1;
  wire [2:0] a1;
  output [2:0] s;
  wire [2:0] s;
  output [2:0] co;
  wire [2:0] co;
  ha \ha_array[0].ha0  (
    .a(a0[0]),
    .b(a1[0]),
    .ca(co[0]),
    .s(s[0])
  );
  ha \ha_array[1].ha0  (
    .a(a0[1]),
    .b(a1[1]),
    .ca(co[1]),
    .s(s[1])
  );
  ha \ha_array[2].ha0  (
    .a(a0[2]),
    .b(a1[2]),
    .ca(co[2]),
    .s(s[2])
  );
endmodule

module \$paramod\setha\N=s32'00000000000000000000000000001000 (a0, a1, s, co);
  input [7:0] a0;
  wire [7:0] a0;
  input [7:0] a1;
  wire [7:0] a1;
  output [7:0] s;
  wire [7:0] s;
  output [7:0] co;
  wire [7:0] co;
  ha \ha_array[0].ha0  (
    .a(a0[0]),
    .b(a1[0]),
    .ca(co[0]),
    .s(s[0])
  );
  ha \ha_array[1].ha0  (
    .a(a0[1]),
    .b(a1[1]),
    .ca(co[1]),
    .s(s[1])
  );
  ha \ha_array[2].ha0  (
    .a(a0[2]),
    .b(a1[2]),
    .ca(co[2]),
    .s(s[2])
  );
  ha \ha_array[3].ha0  (
    .a(a0[3]),
    .b(a1[3]),
    .ca(co[3]),
    .s(s[3])
  );
  ha \ha_array[4].ha0  (
    .a(a0[4]),
    .b(a1[4]),
    .ca(co[4]),
    .s(s[4])
  );
  ha \ha_array[5].ha0  (
    .a(a0[5]),
    .b(a1[5]),
    .ca(co[5]),
    .s(s[5])
  );
  ha \ha_array[6].ha0  (
    .a(a0[6]),
    .b(a1[6]),
    .ca(co[6]),
    .s(s[6])
  );
  ha \ha_array[7].ha0  (
    .a(a0[7]),
    .b(a1[7]),
    .ca(co[7]),
    .s(s[7])
  );
endmodule

module KSA32(A, B, Cin, Sum, Cout);
  input [31:0] A;
  wire [31:0] A;
  input [31:0] B;
  wire [31:0] B;
  input Cin;
  wire Cin;
  output [31:0] Sum;
  wire [31:0] Sum;
  output Cout;
  wire Cout;
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000100000  ksa32 (
    .A(A),
    .B(B),
    .Cin(Cin),
    .Cout(Cout),
    .Sum(Sum)
  );
endmodule

module dadda1(a, b, out);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  output [31:0] out;
  wire [31:0] out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire [15:0] abs_a;
  wire [15:0] abs_b;
  wire [11:0] c0;
  wire [43:0] c1;
  wire [53:0] c2;
  wire [45:0] c3;
  wire [25:0] c4;
  wire [27:0] c5;
  wire [31:0] nextinp;
  wire [15:0] \p[0] ;
  wire [15:0] \p[10] ;
  wire [15:0] \p[11] ;
  wire [15:0] \p[12] ;
  wire [15:0] \p[13] ;
  wire [15:0] \p[14] ;
  wire [15:0] \p[15] ;
  wire [15:0] \p[1] ;
  wire [15:0] \p[2] ;
  wire [15:0] \p[3] ;
  wire [15:0] \p[4] ;
  wire [15:0] \p[5] ;
  wire [15:0] \p[6] ;
  wire [15:0] \p[7] ;
  wire [15:0] \p[8] ;
  wire [15:0] \p[9] ;
  wire [11:0] s0;
  wire [43:0] s1;
  wire [53:0] s2;
  wire [45:0] s3;
  wire [25:0] s4;
  wire [27:0] s5;
  wire [31:0] s6;
  wire sign;
  sky130_fd_sc_hd__clkinv_1 _107_ (
    .A(b[15]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _108_ (
    .A(a[15]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xor2_1 _109_ (
    .A(b[15]),
    .B(a[15]),
    .X(sign)
  );
  sky130_fd_sc_hd__and2_0 _110_ (
    .A(b[0]),
    .B(a[0]),
    .X(\p[0] [0])
  );
  sky130_fd_sc_hd__o21ai_0 _111_ (
    .A1(a[0]),
    .A2(a[1]),
    .B1(a[15]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21oi_1 _112_ (
    .A1(a[0]),
    .A2(a[1]),
    .B1(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a21oi_1 _113_ (
    .A1(_001_),
    .A2(a[1]),
    .B1(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _114_ (
    .A(b[0]),
    .SLEEP(_004_),
    .X(\p[0] [1])
  );
  sky130_fd_sc_hd__xor2_1 _115_ (
    .A(a[2]),
    .B(_002_),
    .X(_005_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _116_ (
    .A(b[0]),
    .SLEEP(_005_),
    .X(\p[0] [2])
  );
  sky130_fd_sc_hd__o31ai_1 _117_ (
    .A1(a[0]),
    .A2(a[1]),
    .A3(a[2]),
    .B1(a[15]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _118_ (
    .A(a[3]),
    .B(_006_),
    .X(_007_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _119_ (
    .A(b[0]),
    .SLEEP(_007_),
    .X(\p[0] [3])
  );
  sky130_fd_sc_hd__or4_1 _120_ (
    .A(a[0]),
    .B(a[1]),
    .C(a[2]),
    .D(a[3]),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(a[15]),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _122_ (
    .A(a[4]),
    .B(_009_),
    .X(_010_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _123_ (
    .A(b[0]),
    .SLEEP(_010_),
    .X(\p[0] [4])
  );
  sky130_fd_sc_hd__o21ai_0 _124_ (
    .A1(a[4]),
    .A2(_008_),
    .B1(a[15]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xor2_1 _125_ (
    .A(a[5]),
    .B(_011_),
    .X(_012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _126_ (
    .A(b[0]),
    .SLEEP(_012_),
    .X(\p[0] [5])
  );
  sky130_fd_sc_hd__o31ai_1 _127_ (
    .A1(a[4]),
    .A2(a[5]),
    .A3(_008_),
    .B1(a[15]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xor2_1 _128_ (
    .A(a[6]),
    .B(_013_),
    .X(_014_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _129_ (
    .A(b[0]),
    .SLEEP(_014_),
    .X(\p[0] [6])
  );
  sky130_fd_sc_hd__nor4_1 _130_ (
    .A(a[4]),
    .B(a[5]),
    .C(a[6]),
    .D(_008_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _131_ (
    .A(_001_),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _132_ (
    .A(a[7]),
    .B(_016_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _133_ (
    .A(b[0]),
    .SLEEP(_017_),
    .X(\p[0] [7])
  );
  sky130_fd_sc_hd__nand2b_1 _134_ (
    .A_N(a[7]),
    .B(_015_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _135_ (
    .A(a[15]),
    .B(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _136_ (
    .A(a[8]),
    .B(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _137_ (
    .A(b[0]),
    .SLEEP(_020_),
    .X(\p[0] [8])
  );
  sky130_fd_sc_hd__o21ai_0 _138_ (
    .A1(a[8]),
    .A2(_018_),
    .B1(a[15]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xor2_1 _139_ (
    .A(a[9]),
    .B(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _140_ (
    .A(b[0]),
    .SLEEP(_022_),
    .X(\p[0] [9])
  );
  sky130_fd_sc_hd__o31ai_1 _141_ (
    .A1(a[8]),
    .A2(a[9]),
    .A3(_018_),
    .B1(a[15]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xor2_1 _142_ (
    .A(a[10]),
    .B(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _143_ (
    .A(b[0]),
    .SLEEP(_024_),
    .X(\p[0] [10])
  );
  sky130_fd_sc_hd__or4_1 _144_ (
    .A(a[8]),
    .B(a[9]),
    .C(a[10]),
    .D(_018_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _145_ (
    .A(a[15]),
    .B(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xor2_1 _146_ (
    .A(a[11]),
    .B(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _147_ (
    .A(b[0]),
    .SLEEP(_027_),
    .X(\p[0] [11])
  );
  sky130_fd_sc_hd__o21ai_0 _148_ (
    .A1(a[11]),
    .A2(_025_),
    .B1(a[15]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__xor2_1 _149_ (
    .A(a[12]),
    .B(_028_),
    .X(_029_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _150_ (
    .A(b[0]),
    .SLEEP(_029_),
    .X(\p[0] [12])
  );
  sky130_fd_sc_hd__o31ai_1 _151_ (
    .A1(a[11]),
    .A2(a[12]),
    .A3(_025_),
    .B1(a[15]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xor2_1 _152_ (
    .A(a[13]),
    .B(_030_),
    .X(_031_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _153_ (
    .A(b[0]),
    .SLEEP(_031_),
    .X(\p[0] [13])
  );
  sky130_fd_sc_hd__or4_1 _154_ (
    .A(a[11]),
    .B(a[12]),
    .C(a[13]),
    .D(_025_),
    .X(_032_)
  );
  sky130_fd_sc_hd__o41ai_1 _155_ (
    .A1(a[11]),
    .A2(a[12]),
    .A3(a[13]),
    .A4(_025_),
    .B1(a[15]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xor2_1 _156_ (
    .A(a[14]),
    .B(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _157_ (
    .A(b[0]),
    .SLEEP(_034_),
    .X(\p[0] [14])
  );
  sky130_fd_sc_hd__or3_1 _158_ (
    .A(_001_),
    .B(a[14]),
    .C(_032_),
    .X(_035_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _159_ (
    .A(b[0]),
    .SLEEP(_035_),
    .X(\p[0] [15])
  );
  sky130_fd_sc_hd__o21ai_0 _160_ (
    .A1(b[0]),
    .A2(b[1]),
    .B1(b[15]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21oi_1 _161_ (
    .A1(b[0]),
    .A2(b[1]),
    .B1(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a21oi_1 _162_ (
    .A1(_000_),
    .A2(b[1]),
    .B1(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _163_ (
    .A(a[0]),
    .SLEEP(_038_),
    .X(\p[1] [0])
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(_004_),
    .B(_038_),
    .Y(\p[1] [1])
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(_005_),
    .B(_038_),
    .Y(\p[1] [2])
  );
  sky130_fd_sc_hd__nor2_1 _166_ (
    .A(_007_),
    .B(_038_),
    .Y(\p[1] [3])
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(_010_),
    .B(_038_),
    .Y(\p[1] [4])
  );
  sky130_fd_sc_hd__nor2_1 _168_ (
    .A(_012_),
    .B(_038_),
    .Y(\p[1] [5])
  );
  sky130_fd_sc_hd__nor2_1 _169_ (
    .A(_014_),
    .B(_038_),
    .Y(\p[1] [6])
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(_017_),
    .B(_038_),
    .Y(\p[1] [7])
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(_020_),
    .B(_038_),
    .Y(\p[1] [8])
  );
  sky130_fd_sc_hd__nor2_1 _172_ (
    .A(_022_),
    .B(_038_),
    .Y(\p[1] [9])
  );
  sky130_fd_sc_hd__nor2_1 _173_ (
    .A(_024_),
    .B(_038_),
    .Y(\p[1] [10])
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(_027_),
    .B(_038_),
    .Y(\p[1] [11])
  );
  sky130_fd_sc_hd__nor2_1 _175_ (
    .A(_029_),
    .B(_038_),
    .Y(\p[1] [12])
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(_031_),
    .B(_038_),
    .Y(\p[1] [13])
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(_034_),
    .B(_038_),
    .Y(\p[1] [14])
  );
  sky130_fd_sc_hd__nor2_1 _178_ (
    .A(_035_),
    .B(_038_),
    .Y(\p[1] [15])
  );
  sky130_fd_sc_hd__xor2_1 _179_ (
    .A(b[2]),
    .B(_036_),
    .X(_039_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _180_ (
    .A(a[0]),
    .SLEEP(_039_),
    .X(\p[2] [0])
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_004_),
    .B(_039_),
    .Y(\p[2] [1])
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(_005_),
    .B(_039_),
    .Y(\p[2] [2])
  );
  sky130_fd_sc_hd__nor2_1 _183_ (
    .A(_007_),
    .B(_039_),
    .Y(\p[2] [3])
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(_010_),
    .B(_039_),
    .Y(\p[2] [4])
  );
  sky130_fd_sc_hd__nor2_1 _185_ (
    .A(_012_),
    .B(_039_),
    .Y(\p[2] [5])
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(_014_),
    .B(_039_),
    .Y(\p[2] [6])
  );
  sky130_fd_sc_hd__nor2_1 _187_ (
    .A(_017_),
    .B(_039_),
    .Y(\p[2] [7])
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(_020_),
    .B(_039_),
    .Y(\p[2] [8])
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(_022_),
    .B(_039_),
    .Y(\p[2] [9])
  );
  sky130_fd_sc_hd__nor2_1 _190_ (
    .A(_024_),
    .B(_039_),
    .Y(\p[2] [10])
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(_027_),
    .B(_039_),
    .Y(\p[2] [11])
  );
  sky130_fd_sc_hd__nor2_1 _192_ (
    .A(_029_),
    .B(_039_),
    .Y(\p[2] [12])
  );
  sky130_fd_sc_hd__nor2_1 _193_ (
    .A(_031_),
    .B(_039_),
    .Y(\p[2] [13])
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(_034_),
    .B(_039_),
    .Y(\p[2] [14])
  );
  sky130_fd_sc_hd__nor2_1 _195_ (
    .A(_035_),
    .B(_039_),
    .Y(\p[2] [15])
  );
  sky130_fd_sc_hd__o31ai_1 _196_ (
    .A1(b[0]),
    .A2(b[1]),
    .A3(b[2]),
    .B1(b[15]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xor2_1 _197_ (
    .A(b[3]),
    .B(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _198_ (
    .A(a[0]),
    .SLEEP(_041_),
    .X(\p[3] [0])
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(_004_),
    .B(_041_),
    .Y(\p[3] [1])
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(_005_),
    .B(_041_),
    .Y(\p[3] [2])
  );
  sky130_fd_sc_hd__nor2_1 _201_ (
    .A(_007_),
    .B(_041_),
    .Y(\p[3] [3])
  );
  sky130_fd_sc_hd__nor2_1 _202_ (
    .A(_010_),
    .B(_041_),
    .Y(\p[3] [4])
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(_012_),
    .B(_041_),
    .Y(\p[3] [5])
  );
  sky130_fd_sc_hd__nor2_1 _204_ (
    .A(_014_),
    .B(_041_),
    .Y(\p[3] [6])
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(_017_),
    .B(_041_),
    .Y(\p[3] [7])
  );
  sky130_fd_sc_hd__nor2_1 _206_ (
    .A(_020_),
    .B(_041_),
    .Y(\p[3] [8])
  );
  sky130_fd_sc_hd__nor2_1 _207_ (
    .A(_022_),
    .B(_041_),
    .Y(\p[3] [9])
  );
  sky130_fd_sc_hd__nor2_1 _208_ (
    .A(_024_),
    .B(_041_),
    .Y(\p[3] [10])
  );
  sky130_fd_sc_hd__nor2_1 _209_ (
    .A(_027_),
    .B(_041_),
    .Y(\p[3] [11])
  );
  sky130_fd_sc_hd__nor2_1 _210_ (
    .A(_029_),
    .B(_041_),
    .Y(\p[3] [12])
  );
  sky130_fd_sc_hd__nor2_1 _211_ (
    .A(_031_),
    .B(_041_),
    .Y(\p[3] [13])
  );
  sky130_fd_sc_hd__nor2_1 _212_ (
    .A(_034_),
    .B(_041_),
    .Y(\p[3] [14])
  );
  sky130_fd_sc_hd__nor2_1 _213_ (
    .A(_035_),
    .B(_041_),
    .Y(\p[3] [15])
  );
  sky130_fd_sc_hd__or4_1 _214_ (
    .A(b[0]),
    .B(b[1]),
    .C(b[2]),
    .D(b[3]),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(b[15]),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _216_ (
    .A(b[4]),
    .B(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _217_ (
    .A(a[0]),
    .SLEEP(_044_),
    .X(\p[4] [0])
  );
  sky130_fd_sc_hd__nor2_1 _218_ (
    .A(_004_),
    .B(_044_),
    .Y(\p[4] [1])
  );
  sky130_fd_sc_hd__nor2_1 _219_ (
    .A(_005_),
    .B(_044_),
    .Y(\p[4] [2])
  );
  sky130_fd_sc_hd__nor2_1 _220_ (
    .A(_007_),
    .B(_044_),
    .Y(\p[4] [3])
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(_010_),
    .B(_044_),
    .Y(\p[4] [4])
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_012_),
    .B(_044_),
    .Y(\p[4] [5])
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(_014_),
    .B(_044_),
    .Y(\p[4] [6])
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(_017_),
    .B(_044_),
    .Y(\p[4] [7])
  );
  sky130_fd_sc_hd__nor2_1 _225_ (
    .A(_020_),
    .B(_044_),
    .Y(\p[4] [8])
  );
  sky130_fd_sc_hd__nor2_1 _226_ (
    .A(_022_),
    .B(_044_),
    .Y(\p[4] [9])
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(_024_),
    .B(_044_),
    .Y(\p[4] [10])
  );
  sky130_fd_sc_hd__nor2_1 _228_ (
    .A(_027_),
    .B(_044_),
    .Y(\p[4] [11])
  );
  sky130_fd_sc_hd__nor2_1 _229_ (
    .A(_029_),
    .B(_044_),
    .Y(\p[4] [12])
  );
  sky130_fd_sc_hd__nor2_1 _230_ (
    .A(_031_),
    .B(_044_),
    .Y(\p[4] [13])
  );
  sky130_fd_sc_hd__nor2_1 _231_ (
    .A(_034_),
    .B(_044_),
    .Y(\p[4] [14])
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(_035_),
    .B(_044_),
    .Y(\p[4] [15])
  );
  sky130_fd_sc_hd__o21ai_0 _233_ (
    .A1(b[4]),
    .A2(_042_),
    .B1(b[15]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _234_ (
    .A(b[5]),
    .B(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _235_ (
    .A(a[0]),
    .SLEEP(_046_),
    .X(\p[5] [0])
  );
  sky130_fd_sc_hd__nor2_1 _236_ (
    .A(_004_),
    .B(_046_),
    .Y(\p[5] [1])
  );
  sky130_fd_sc_hd__nor2_1 _237_ (
    .A(_005_),
    .B(_046_),
    .Y(\p[5] [2])
  );
  sky130_fd_sc_hd__nor2_1 _238_ (
    .A(_007_),
    .B(_046_),
    .Y(\p[5] [3])
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(_010_),
    .B(_046_),
    .Y(\p[5] [4])
  );
  sky130_fd_sc_hd__nor2_1 _240_ (
    .A(_012_),
    .B(_046_),
    .Y(\p[5] [5])
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_014_),
    .B(_046_),
    .Y(\p[5] [6])
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(_017_),
    .B(_046_),
    .Y(\p[5] [7])
  );
  sky130_fd_sc_hd__nor2_1 _243_ (
    .A(_020_),
    .B(_046_),
    .Y(\p[5] [8])
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(_022_),
    .B(_046_),
    .Y(\p[5] [9])
  );
  sky130_fd_sc_hd__nor2_1 _245_ (
    .A(_024_),
    .B(_046_),
    .Y(\p[5] [10])
  );
  sky130_fd_sc_hd__nor2_1 _246_ (
    .A(_027_),
    .B(_046_),
    .Y(\p[5] [11])
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(_029_),
    .B(_046_),
    .Y(\p[5] [12])
  );
  sky130_fd_sc_hd__nor2_1 _248_ (
    .A(_031_),
    .B(_046_),
    .Y(\p[5] [13])
  );
  sky130_fd_sc_hd__nor2_1 _249_ (
    .A(_034_),
    .B(_046_),
    .Y(\p[5] [14])
  );
  sky130_fd_sc_hd__nor2_1 _250_ (
    .A(_035_),
    .B(_046_),
    .Y(\p[5] [15])
  );
  sky130_fd_sc_hd__o31ai_1 _251_ (
    .A1(b[4]),
    .A2(b[5]),
    .A3(_042_),
    .B1(b[15]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xor2_1 _252_ (
    .A(b[6]),
    .B(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _253_ (
    .A(a[0]),
    .SLEEP(_048_),
    .X(\p[6] [0])
  );
  sky130_fd_sc_hd__nor2_1 _254_ (
    .A(_004_),
    .B(_048_),
    .Y(\p[6] [1])
  );
  sky130_fd_sc_hd__nor2_1 _255_ (
    .A(_005_),
    .B(_048_),
    .Y(\p[6] [2])
  );
  sky130_fd_sc_hd__nor2_1 _256_ (
    .A(_007_),
    .B(_048_),
    .Y(\p[6] [3])
  );
  sky130_fd_sc_hd__nor2_1 _257_ (
    .A(_010_),
    .B(_048_),
    .Y(\p[6] [4])
  );
  sky130_fd_sc_hd__nor2_1 _258_ (
    .A(_012_),
    .B(_048_),
    .Y(\p[6] [5])
  );
  sky130_fd_sc_hd__nor2_1 _259_ (
    .A(_014_),
    .B(_048_),
    .Y(\p[6] [6])
  );
  sky130_fd_sc_hd__nor2_1 _260_ (
    .A(_017_),
    .B(_048_),
    .Y(\p[6] [7])
  );
  sky130_fd_sc_hd__nor2_1 _261_ (
    .A(_020_),
    .B(_048_),
    .Y(\p[6] [8])
  );
  sky130_fd_sc_hd__nor2_1 _262_ (
    .A(_022_),
    .B(_048_),
    .Y(\p[6] [9])
  );
  sky130_fd_sc_hd__nor2_1 _263_ (
    .A(_024_),
    .B(_048_),
    .Y(\p[6] [10])
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(_027_),
    .B(_048_),
    .Y(\p[6] [11])
  );
  sky130_fd_sc_hd__nor2_1 _265_ (
    .A(_029_),
    .B(_048_),
    .Y(\p[6] [12])
  );
  sky130_fd_sc_hd__nor2_1 _266_ (
    .A(_031_),
    .B(_048_),
    .Y(\p[6] [13])
  );
  sky130_fd_sc_hd__nor2_1 _267_ (
    .A(_034_),
    .B(_048_),
    .Y(\p[6] [14])
  );
  sky130_fd_sc_hd__nor2_1 _268_ (
    .A(_035_),
    .B(_048_),
    .Y(\p[6] [15])
  );
  sky130_fd_sc_hd__nor4_1 _269_ (
    .A(b[4]),
    .B(b[5]),
    .C(b[6]),
    .D(_042_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _270_ (
    .A(_000_),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__xnor2_1 _271_ (
    .A(b[7]),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _272_ (
    .A(a[0]),
    .SLEEP(_051_),
    .X(\p[7] [0])
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(_004_),
    .B(_051_),
    .Y(\p[7] [1])
  );
  sky130_fd_sc_hd__nor2_1 _274_ (
    .A(_005_),
    .B(_051_),
    .Y(\p[7] [2])
  );
  sky130_fd_sc_hd__nor2_1 _275_ (
    .A(_007_),
    .B(_051_),
    .Y(\p[7] [3])
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(_010_),
    .B(_051_),
    .Y(\p[7] [4])
  );
  sky130_fd_sc_hd__nor2_1 _277_ (
    .A(_012_),
    .B(_051_),
    .Y(\p[7] [5])
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(_014_),
    .B(_051_),
    .Y(\p[7] [6])
  );
  sky130_fd_sc_hd__nor2_1 _279_ (
    .A(_017_),
    .B(_051_),
    .Y(\p[7] [7])
  );
  sky130_fd_sc_hd__nor2_1 _280_ (
    .A(_020_),
    .B(_051_),
    .Y(\p[7] [8])
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(_022_),
    .B(_051_),
    .Y(\p[7] [9])
  );
  sky130_fd_sc_hd__nor2_1 _282_ (
    .A(_024_),
    .B(_051_),
    .Y(\p[7] [10])
  );
  sky130_fd_sc_hd__nor2_1 _283_ (
    .A(_027_),
    .B(_051_),
    .Y(\p[7] [11])
  );
  sky130_fd_sc_hd__nor2_1 _284_ (
    .A(_029_),
    .B(_051_),
    .Y(\p[7] [12])
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_031_),
    .B(_051_),
    .Y(\p[7] [13])
  );
  sky130_fd_sc_hd__nor2_1 _286_ (
    .A(_034_),
    .B(_051_),
    .Y(\p[7] [14])
  );
  sky130_fd_sc_hd__nor2_1 _287_ (
    .A(_035_),
    .B(_051_),
    .Y(\p[7] [15])
  );
  sky130_fd_sc_hd__nand2b_1 _288_ (
    .A_N(b[7]),
    .B(_049_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(b[15]),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xor2_1 _290_ (
    .A(b[8]),
    .B(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _291_ (
    .A(a[0]),
    .SLEEP(_054_),
    .X(\p[8] [0])
  );
  sky130_fd_sc_hd__nor2_1 _292_ (
    .A(_004_),
    .B(_054_),
    .Y(\p[8] [1])
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_005_),
    .B(_054_),
    .Y(\p[8] [2])
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(_007_),
    .B(_054_),
    .Y(\p[8] [3])
  );
  sky130_fd_sc_hd__nor2_1 _295_ (
    .A(_010_),
    .B(_054_),
    .Y(\p[8] [4])
  );
  sky130_fd_sc_hd__nor2_1 _296_ (
    .A(_012_),
    .B(_054_),
    .Y(\p[8] [5])
  );
  sky130_fd_sc_hd__nor2_1 _297_ (
    .A(_014_),
    .B(_054_),
    .Y(\p[8] [6])
  );
  sky130_fd_sc_hd__nor2_1 _298_ (
    .A(_017_),
    .B(_054_),
    .Y(\p[8] [7])
  );
  sky130_fd_sc_hd__nor2_1 _299_ (
    .A(_020_),
    .B(_054_),
    .Y(\p[8] [8])
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(_022_),
    .B(_054_),
    .Y(\p[8] [9])
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(_024_),
    .B(_054_),
    .Y(\p[8] [10])
  );
  sky130_fd_sc_hd__nor2_1 _302_ (
    .A(_027_),
    .B(_054_),
    .Y(\p[8] [11])
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(_029_),
    .B(_054_),
    .Y(\p[8] [12])
  );
  sky130_fd_sc_hd__nor2_1 _304_ (
    .A(_031_),
    .B(_054_),
    .Y(\p[8] [13])
  );
  sky130_fd_sc_hd__nor2_1 _305_ (
    .A(_034_),
    .B(_054_),
    .Y(\p[8] [14])
  );
  sky130_fd_sc_hd__nor2_1 _306_ (
    .A(_035_),
    .B(_054_),
    .Y(\p[8] [15])
  );
  sky130_fd_sc_hd__o21ai_0 _307_ (
    .A1(b[8]),
    .A2(_052_),
    .B1(b[15]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__xor2_1 _308_ (
    .A(b[9]),
    .B(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _309_ (
    .A(a[0]),
    .SLEEP(_056_),
    .X(\p[9] [0])
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(_004_),
    .B(_056_),
    .Y(\p[9] [1])
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(_005_),
    .B(_056_),
    .Y(\p[9] [2])
  );
  sky130_fd_sc_hd__nor2_1 _312_ (
    .A(_007_),
    .B(_056_),
    .Y(\p[9] [3])
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(_010_),
    .B(_056_),
    .Y(\p[9] [4])
  );
  sky130_fd_sc_hd__nor2_1 _314_ (
    .A(_012_),
    .B(_056_),
    .Y(\p[9] [5])
  );
  sky130_fd_sc_hd__nor2_1 _315_ (
    .A(_014_),
    .B(_056_),
    .Y(\p[9] [6])
  );
  sky130_fd_sc_hd__nor2_1 _316_ (
    .A(_017_),
    .B(_056_),
    .Y(\p[9] [7])
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_020_),
    .B(_056_),
    .Y(\p[9] [8])
  );
  sky130_fd_sc_hd__nor2_1 _318_ (
    .A(_022_),
    .B(_056_),
    .Y(\p[9] [9])
  );
  sky130_fd_sc_hd__nor2_1 _319_ (
    .A(_024_),
    .B(_056_),
    .Y(\p[9] [10])
  );
  sky130_fd_sc_hd__nor2_1 _320_ (
    .A(_027_),
    .B(_056_),
    .Y(\p[9] [11])
  );
  sky130_fd_sc_hd__nor2_1 _321_ (
    .A(_029_),
    .B(_056_),
    .Y(\p[9] [12])
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(_031_),
    .B(_056_),
    .Y(\p[9] [13])
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(_034_),
    .B(_056_),
    .Y(\p[9] [14])
  );
  sky130_fd_sc_hd__nor2_1 _324_ (
    .A(_035_),
    .B(_056_),
    .Y(\p[9] [15])
  );
  sky130_fd_sc_hd__o31ai_1 _325_ (
    .A1(b[8]),
    .A2(b[9]),
    .A3(_052_),
    .B1(b[15]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xor2_1 _326_ (
    .A(b[10]),
    .B(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _327_ (
    .A(a[0]),
    .SLEEP(_058_),
    .X(\p[10] [0])
  );
  sky130_fd_sc_hd__nor2_1 _328_ (
    .A(_004_),
    .B(_058_),
    .Y(\p[10] [1])
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_005_),
    .B(_058_),
    .Y(\p[10] [2])
  );
  sky130_fd_sc_hd__nor2_1 _330_ (
    .A(_007_),
    .B(_058_),
    .Y(\p[10] [3])
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_010_),
    .B(_058_),
    .Y(\p[10] [4])
  );
  sky130_fd_sc_hd__nor2_1 _332_ (
    .A(_012_),
    .B(_058_),
    .Y(\p[10] [5])
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(_014_),
    .B(_058_),
    .Y(\p[10] [6])
  );
  sky130_fd_sc_hd__nor2_1 _334_ (
    .A(_017_),
    .B(_058_),
    .Y(\p[10] [7])
  );
  sky130_fd_sc_hd__nor2_1 _335_ (
    .A(_020_),
    .B(_058_),
    .Y(\p[10] [8])
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(_022_),
    .B(_058_),
    .Y(\p[10] [9])
  );
  sky130_fd_sc_hd__nor2_1 _337_ (
    .A(_024_),
    .B(_058_),
    .Y(\p[10] [10])
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(_027_),
    .B(_058_),
    .Y(\p[10] [11])
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(_029_),
    .B(_058_),
    .Y(\p[10] [12])
  );
  sky130_fd_sc_hd__nor2_1 _340_ (
    .A(_031_),
    .B(_058_),
    .Y(\p[10] [13])
  );
  sky130_fd_sc_hd__nor2_1 _341_ (
    .A(_034_),
    .B(_058_),
    .Y(\p[10] [14])
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(_035_),
    .B(_058_),
    .Y(\p[10] [15])
  );
  sky130_fd_sc_hd__or4_1 _343_ (
    .A(b[8]),
    .B(b[9]),
    .C(b[10]),
    .D(_052_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(b[15]),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__xor2_1 _345_ (
    .A(b[11]),
    .B(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _346_ (
    .A(a[0]),
    .SLEEP(_061_),
    .X(\p[11] [0])
  );
  sky130_fd_sc_hd__nor2_1 _347_ (
    .A(_004_),
    .B(_061_),
    .Y(\p[11] [1])
  );
  sky130_fd_sc_hd__nor2_1 _348_ (
    .A(_005_),
    .B(_061_),
    .Y(\p[11] [2])
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(_007_),
    .B(_061_),
    .Y(\p[11] [3])
  );
  sky130_fd_sc_hd__nor2_1 _350_ (
    .A(_010_),
    .B(_061_),
    .Y(\p[11] [4])
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(_012_),
    .B(_061_),
    .Y(\p[11] [5])
  );
  sky130_fd_sc_hd__nor2_1 _352_ (
    .A(_014_),
    .B(_061_),
    .Y(\p[11] [6])
  );
  sky130_fd_sc_hd__nor2_1 _353_ (
    .A(_017_),
    .B(_061_),
    .Y(\p[11] [7])
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(_020_),
    .B(_061_),
    .Y(\p[11] [8])
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(_022_),
    .B(_061_),
    .Y(\p[11] [9])
  );
  sky130_fd_sc_hd__nor2_1 _356_ (
    .A(_024_),
    .B(_061_),
    .Y(\p[11] [10])
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(_027_),
    .B(_061_),
    .Y(\p[11] [11])
  );
  sky130_fd_sc_hd__nor2_1 _358_ (
    .A(_029_),
    .B(_061_),
    .Y(\p[11] [12])
  );
  sky130_fd_sc_hd__nor2_1 _359_ (
    .A(_031_),
    .B(_061_),
    .Y(\p[11] [13])
  );
  sky130_fd_sc_hd__nor2_1 _360_ (
    .A(_034_),
    .B(_061_),
    .Y(\p[11] [14])
  );
  sky130_fd_sc_hd__nor2_1 _361_ (
    .A(_035_),
    .B(_061_),
    .Y(\p[11] [15])
  );
  sky130_fd_sc_hd__o21ai_0 _362_ (
    .A1(b[11]),
    .A2(_059_),
    .B1(b[15]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xor2_1 _363_ (
    .A(b[12]),
    .B(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _364_ (
    .A(a[0]),
    .SLEEP(_063_),
    .X(\p[12] [0])
  );
  sky130_fd_sc_hd__nor2_1 _365_ (
    .A(_004_),
    .B(_063_),
    .Y(\p[12] [1])
  );
  sky130_fd_sc_hd__nor2_1 _366_ (
    .A(_005_),
    .B(_063_),
    .Y(\p[12] [2])
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(_007_),
    .B(_063_),
    .Y(\p[12] [3])
  );
  sky130_fd_sc_hd__nor2_1 _368_ (
    .A(_010_),
    .B(_063_),
    .Y(\p[12] [4])
  );
  sky130_fd_sc_hd__nor2_1 _369_ (
    .A(_012_),
    .B(_063_),
    .Y(\p[12] [5])
  );
  sky130_fd_sc_hd__nor2_1 _370_ (
    .A(_014_),
    .B(_063_),
    .Y(\p[12] [6])
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(_017_),
    .B(_063_),
    .Y(\p[12] [7])
  );
  sky130_fd_sc_hd__nor2_1 _372_ (
    .A(_020_),
    .B(_063_),
    .Y(\p[12] [8])
  );
  sky130_fd_sc_hd__nor2_1 _373_ (
    .A(_022_),
    .B(_063_),
    .Y(\p[12] [9])
  );
  sky130_fd_sc_hd__nor2_1 _374_ (
    .A(_024_),
    .B(_063_),
    .Y(\p[12] [10])
  );
  sky130_fd_sc_hd__nor2_1 _375_ (
    .A(_027_),
    .B(_063_),
    .Y(\p[12] [11])
  );
  sky130_fd_sc_hd__nor2_1 _376_ (
    .A(_029_),
    .B(_063_),
    .Y(\p[12] [12])
  );
  sky130_fd_sc_hd__nor2_1 _377_ (
    .A(_031_),
    .B(_063_),
    .Y(\p[12] [13])
  );
  sky130_fd_sc_hd__nor2_1 _378_ (
    .A(_034_),
    .B(_063_),
    .Y(\p[12] [14])
  );
  sky130_fd_sc_hd__nor2_1 _379_ (
    .A(_035_),
    .B(_063_),
    .Y(\p[12] [15])
  );
  sky130_fd_sc_hd__o31ai_1 _380_ (
    .A1(b[11]),
    .A2(b[12]),
    .A3(_059_),
    .B1(b[15]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xor2_1 _381_ (
    .A(b[13]),
    .B(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _382_ (
    .A(a[0]),
    .SLEEP(_065_),
    .X(\p[13] [0])
  );
  sky130_fd_sc_hd__nor2_1 _383_ (
    .A(_004_),
    .B(_065_),
    .Y(\p[13] [1])
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(_005_),
    .B(_065_),
    .Y(\p[13] [2])
  );
  sky130_fd_sc_hd__nor2_1 _385_ (
    .A(_007_),
    .B(_065_),
    .Y(\p[13] [3])
  );
  sky130_fd_sc_hd__nor2_1 _386_ (
    .A(_010_),
    .B(_065_),
    .Y(\p[13] [4])
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(_012_),
    .B(_065_),
    .Y(\p[13] [5])
  );
  sky130_fd_sc_hd__nor2_1 _388_ (
    .A(_014_),
    .B(_065_),
    .Y(\p[13] [6])
  );
  sky130_fd_sc_hd__nor2_1 _389_ (
    .A(_017_),
    .B(_065_),
    .Y(\p[13] [7])
  );
  sky130_fd_sc_hd__nor2_1 _390_ (
    .A(_020_),
    .B(_065_),
    .Y(\p[13] [8])
  );
  sky130_fd_sc_hd__nor2_1 _391_ (
    .A(_022_),
    .B(_065_),
    .Y(\p[13] [9])
  );
  sky130_fd_sc_hd__nor2_1 _392_ (
    .A(_024_),
    .B(_065_),
    .Y(\p[13] [10])
  );
  sky130_fd_sc_hd__nor2_1 _393_ (
    .A(_027_),
    .B(_065_),
    .Y(\p[13] [11])
  );
  sky130_fd_sc_hd__nor2_1 _394_ (
    .A(_029_),
    .B(_065_),
    .Y(\p[13] [12])
  );
  sky130_fd_sc_hd__nor2_1 _395_ (
    .A(_031_),
    .B(_065_),
    .Y(\p[13] [13])
  );
  sky130_fd_sc_hd__nor2_1 _396_ (
    .A(_034_),
    .B(_065_),
    .Y(\p[13] [14])
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(_035_),
    .B(_065_),
    .Y(\p[13] [15])
  );
  sky130_fd_sc_hd__or4_1 _398_ (
    .A(b[11]),
    .B(b[12]),
    .C(b[13]),
    .D(_059_),
    .X(_066_)
  );
  sky130_fd_sc_hd__o41ai_1 _399_ (
    .A1(b[11]),
    .A2(b[12]),
    .A3(b[13]),
    .A4(_059_),
    .B1(b[15]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xor2_1 _400_ (
    .A(b[14]),
    .B(_067_),
    .X(_068_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _401_ (
    .A(a[0]),
    .SLEEP(_068_),
    .X(\p[14] [0])
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(_004_),
    .B(_068_),
    .Y(\p[14] [1])
  );
  sky130_fd_sc_hd__nor2_1 _403_ (
    .A(_005_),
    .B(_068_),
    .Y(\p[14] [2])
  );
  sky130_fd_sc_hd__nor2_1 _404_ (
    .A(_007_),
    .B(_068_),
    .Y(\p[14] [3])
  );
  sky130_fd_sc_hd__nor2_1 _405_ (
    .A(_010_),
    .B(_068_),
    .Y(\p[14] [4])
  );
  sky130_fd_sc_hd__nor2_1 _406_ (
    .A(_012_),
    .B(_068_),
    .Y(\p[14] [5])
  );
  sky130_fd_sc_hd__nor2_1 _407_ (
    .A(_014_),
    .B(_068_),
    .Y(\p[14] [6])
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(_017_),
    .B(_068_),
    .Y(\p[14] [7])
  );
  sky130_fd_sc_hd__nor2_1 _409_ (
    .A(_020_),
    .B(_068_),
    .Y(\p[14] [8])
  );
  sky130_fd_sc_hd__nor2_1 _410_ (
    .A(_022_),
    .B(_068_),
    .Y(\p[14] [9])
  );
  sky130_fd_sc_hd__nor2_1 _411_ (
    .A(_024_),
    .B(_068_),
    .Y(\p[14] [10])
  );
  sky130_fd_sc_hd__nor2_1 _412_ (
    .A(_027_),
    .B(_068_),
    .Y(\p[14] [11])
  );
  sky130_fd_sc_hd__nor2_1 _413_ (
    .A(_029_),
    .B(_068_),
    .Y(\p[14] [12])
  );
  sky130_fd_sc_hd__nor2_1 _414_ (
    .A(_031_),
    .B(_068_),
    .Y(\p[14] [13])
  );
  sky130_fd_sc_hd__nor2_1 _415_ (
    .A(_034_),
    .B(_068_),
    .Y(\p[14] [14])
  );
  sky130_fd_sc_hd__nor2_1 _416_ (
    .A(_035_),
    .B(_068_),
    .Y(\p[14] [15])
  );
  sky130_fd_sc_hd__or3_1 _417_ (
    .A(_000_),
    .B(b[14]),
    .C(_066_),
    .X(_069_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _418_ (
    .A(a[0]),
    .SLEEP(_069_),
    .X(\p[15] [0])
  );
  sky130_fd_sc_hd__nor2_1 _419_ (
    .A(_004_),
    .B(_069_),
    .Y(\p[15] [1])
  );
  sky130_fd_sc_hd__nor2_1 _420_ (
    .A(_005_),
    .B(_069_),
    .Y(\p[15] [2])
  );
  sky130_fd_sc_hd__nor2_1 _421_ (
    .A(_007_),
    .B(_069_),
    .Y(\p[15] [3])
  );
  sky130_fd_sc_hd__nor2_1 _422_ (
    .A(_010_),
    .B(_069_),
    .Y(\p[15] [4])
  );
  sky130_fd_sc_hd__nor2_1 _423_ (
    .A(_012_),
    .B(_069_),
    .Y(\p[15] [5])
  );
  sky130_fd_sc_hd__nor2_1 _424_ (
    .A(_014_),
    .B(_069_),
    .Y(\p[15] [6])
  );
  sky130_fd_sc_hd__nor2_1 _425_ (
    .A(_017_),
    .B(_069_),
    .Y(\p[15] [7])
  );
  sky130_fd_sc_hd__nor2_1 _426_ (
    .A(_020_),
    .B(_069_),
    .Y(\p[15] [8])
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(_022_),
    .B(_069_),
    .Y(\p[15] [9])
  );
  sky130_fd_sc_hd__nor2_1 _428_ (
    .A(_024_),
    .B(_069_),
    .Y(\p[15] [10])
  );
  sky130_fd_sc_hd__nor2_1 _429_ (
    .A(_027_),
    .B(_069_),
    .Y(\p[15] [11])
  );
  sky130_fd_sc_hd__nor2_1 _430_ (
    .A(_029_),
    .B(_069_),
    .Y(\p[15] [12])
  );
  sky130_fd_sc_hd__nor2_1 _431_ (
    .A(_031_),
    .B(_069_),
    .Y(\p[15] [13])
  );
  sky130_fd_sc_hd__nor2_1 _432_ (
    .A(_034_),
    .B(_069_),
    .Y(\p[15] [14])
  );
  sky130_fd_sc_hd__nor2_1 _433_ (
    .A(_035_),
    .B(_069_),
    .Y(\p[15] [15])
  );
  sky130_fd_sc_hd__conb_1 _434_ (
    .LO(_070_)
  );
  sky130_fd_sc_hd__conb_1 _435_ (
    .LO(_071_)
  );
  sky130_fd_sc_hd__conb_1 _436_ (
    .LO(_072_)
  );
  sky130_fd_sc_hd__conb_1 _437_ (
    .LO(_073_)
  );
  sky130_fd_sc_hd__conb_1 _438_ (
    .LO(_074_)
  );
  sky130_fd_sc_hd__conb_1 _439_ (
    .LO(_075_)
  );
  sky130_fd_sc_hd__conb_1 _440_ (
    .LO(_076_)
  );
  sky130_fd_sc_hd__conb_1 _441_ (
    .LO(_077_)
  );
  sky130_fd_sc_hd__conb_1 _442_ (
    .LO(_078_)
  );
  sky130_fd_sc_hd__conb_1 _443_ (
    .LO(_079_)
  );
  sky130_fd_sc_hd__conb_1 _444_ (
    .LO(_080_)
  );
  sky130_fd_sc_hd__conb_1 _445_ (
    .LO(_081_)
  );
  sky130_fd_sc_hd__conb_1 _446_ (
    .LO(_082_)
  );
  sky130_fd_sc_hd__conb_1 _447_ (
    .LO(_083_)
  );
  sky130_fd_sc_hd__conb_1 _448_ (
    .LO(_084_)
  );
  sky130_fd_sc_hd__conb_1 _449_ (
    .LO(_085_)
  );
  sky130_fd_sc_hd__conb_1 _450_ (
    .LO(_086_)
  );
  sky130_fd_sc_hd__conb_1 _451_ (
    .LO(_087_)
  );
  sky130_fd_sc_hd__conb_1 _452_ (
    .LO(_088_)
  );
  sky130_fd_sc_hd__conb_1 _453_ (
    .LO(_089_)
  );
  sky130_fd_sc_hd__conb_1 _454_ (
    .LO(_090_)
  );
  sky130_fd_sc_hd__conb_1 _455_ (
    .LO(_091_)
  );
  sky130_fd_sc_hd__conb_1 _456_ (
    .LO(_092_)
  );
  sky130_fd_sc_hd__conb_1 _457_ (
    .LO(_093_)
  );
  sky130_fd_sc_hd__conb_1 _458_ (
    .LO(_094_)
  );
  sky130_fd_sc_hd__conb_1 _459_ (
    .LO(_095_)
  );
  sky130_fd_sc_hd__conb_1 _460_ (
    .LO(_096_)
  );
  sky130_fd_sc_hd__conb_1 _461_ (
    .LO(_097_)
  );
  sky130_fd_sc_hd__conb_1 _462_ (
    .LO(_098_)
  );
  sky130_fd_sc_hd__conb_1 _463_ (
    .LO(_099_)
  );
  sky130_fd_sc_hd__conb_1 _464_ (
    .LO(_100_)
  );
  sky130_fd_sc_hd__conb_1 _465_ (
    .LO(_101_)
  );
  sky130_fd_sc_hd__conb_1 _466_ (
    .LO(_102_)
  );
  sky130_fd_sc_hd__conb_1 _467_ (
    .LO(_103_)
  );
  sky130_fd_sc_hd__conb_1 _468_ (
    .LO(_104_)
  );
  sky130_fd_sc_hd__conb_1 _469_ (
    .LO(_105_)
  );
  sky130_fd_sc_hd__conb_1 _470_ (
    .LO(_106_)
  );
  KSA32 finaladder32bit (
    .A({ _070_, \p[15] [15], s5, \p[0] [1:0] }),
    .B({ _073_, c5, _072_, \p[1] [0], _071_ }),
    .Cin(_074_),
    .Sum(s6)
  );
  inv32bits inv0 (
    .i(s6),
    .o(nextinp),
    .sign(sign)
  );
  KSA32 lastadder (
    .A(nextinp),
    .B({ _106_, _105_, _104_, _103_, _102_, _101_, _100_, _099_, _098_, _097_, _096_, _095_, _094_, _093_, _092_, _091_, _090_, _089_, _088_, _087_, _086_, _085_, _084_, _083_, _082_, _081_, _080_, _079_, _078_, _077_, _076_, _075_ }),
    .Cin(sign),
    .Sum(out)
  );
  \$paramod\setfa\N=s32'00000000000000000000000000000110  s0fa0 (
    .a0({ \p[3] [15], \p[2] [15], \p[1] [15], \p[0] [15:13] }),
    .a1({ \p[4] [14], \p[3] [14], \p[2] [14], \p[1] [14:12] }),
    .a2({ \p[5] [13], \p[4] [13], \p[3] [13], \p[2] [13:11] }),
    .co(c0[5:0]),
    .s(s0[5:0])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000000100  s0fa1 (
    .a0({ \p[5] [12], \p[4] [12], \p[3] [12:11] }),
    .a1({ \p[6] [11], \p[5] [11], \p[4] [11:10] }),
    .a2({ \p[7] [10], \p[6] [10], \p[5] [10:9] }),
    .co(c0[9:6]),
    .s(s0[9:6])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000000010  s0fa2 (
    .a0({ \p[7] [9], \p[6] [9] }),
    .a1({ \p[8] [8], \p[7] [8] }),
    .a2({ \p[9] [7], \p[8] [7] }),
    .co(c0[11:10]),
    .s(s0[11:10])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000001110  s1fa0 (
    .a0({ \p[7] [15], \p[6] [15], \p[5] [15], c0[5], s0[5:0], \p[0] [12:9] }),
    .a1({ \p[8] [14], \p[7] [14], \p[6] [14], \p[4] [15], c0[4:0], \p[3] [10], \p[1] [11:8] }),
    .a2({ \p[9] [13], \p[8] [13], \p[7] [13], \p[5] [14], c0[9], s0[9:6], \p[4] [9], \p[2] [10:7] }),
    .co(c1[13:0]),
    .s(s1[13:0])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000001100  s1fa1 (
    .a0({ \p[9] [12], \p[8] [12], \p[6] [13:12], c0[8:6], \p[6] [8], \p[5] [8], \p[3] [9:7] }),
    .a1({ \p[10] [11], \p[9] [11], \p[7] [12:11], c0[11], s0[11:10], \p[7] [7], \p[6] [7], \p[4] [8:6] }),
    .a2({ \p[11] [10], \p[10] [10], \p[8] [11:9], c0[10], \p[9] [6], \p[8] [6], \p[7] [6], \p[5] [7:5] }),
    .co(c1[25:14]),
    .s(s1[25:14])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000001010  s1fa2 (
    .a0({ \p[11] [9], \p[9] [10:8], \p[10] [6:5], \p[9] [5], \p[8] [5], \p[6] [6:5] }),
    .a1({ \p[12] [8], \p[10] [9:7], \p[11] [5:4], \p[10] [4], \p[9] [4], \p[7] [5:4] }),
    .a2({ \p[13] [7], \p[11] [8:6], \p[12] [4:3], \p[11] [3], \p[10] [3], \p[8] [4:3] }),
    .co(c1[35:26]),
    .s(s1[35:26])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000001000  s1fa3 (
    .a0({ \p[12] [7:5], \p[13] [3:2], \p[12] [2], \p[11] [2], \p[9] [3] }),
    .a1({ \p[13] [6:4], \p[14] [2:1], \p[13] [1], \p[12] [1], \p[10] [2] }),
    .a2({ \p[14] [5:3], \p[15] [1:0], \p[14] [0], \p[13] [0], \p[11] [1] }),
    .co(c1[43:36]),
    .s(s1[43:36])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000010100  s2fa0 (
    .a0({ \p[10] [15], \p[9] [15], c1[13], s1[13:0], \p[0] [8:6] }),
    .a1({ \p[11] [14], \p[10] [14], \p[8] [15], c1[12:0], \p[3] [6], \p[1] [7:5] }),
    .a2({ \p[12] [13], \p[11] [13], \p[9] [14], c1[25], s1[25:14], \p[4] [5], \p[2] [6:4] }),
    .co(c2[19:0]),
    .s(s2[19:0])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000010010  s2fa1 (
    .a0({ \p[12] [12], \p[10] [13:12], c1[24:14], \p[6] [4], \p[5] [4], \p[3] [5:4] }),
    .a1({ \p[13] [11], \p[11] [12:11], c1[35], s1[35:26], \p[7] [3], \p[6] [3], \p[4] [4:3] }),
    .a2({ \p[14] [10], \p[12] [11:9], c1[34:26], \p[9] [2], \p[8] [2], \p[7] [2], \p[5] [3:2] }),
    .co(c2[37:20]),
    .s(s2[37:20])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000001000  s2fa2 (
    .a0({ \p[13] [10:8], c1[43], s1[43:41], \p[6] [2] }),
    .a1({ \p[14] [9:6], c1[42:40], \p[7] [1] }),
    .a2({ \p[15] [8:2], \p[8] [0] }),
    .co({ c2[53:47], c2[38] }),
    .s({ s2[53:47], s2[38] })
  );
  \$paramod\setha\N=s32'00000000000000000000000000001000  s2ha0 (
    .a0({ s1[40:36], \p[10] [1], \p[9] [1], \p[8] [1] }),
    .a1({ c1[39:36], \p[12] [0], \p[11] [0], \p[10] [0], \p[9] [0] }),
    .co(c2[46:39]),
    .s(s2[46:39])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000011000  s3fa0 (
    .a0({ \p[12] [15], c2[19], s2[19:0], \p[0] [5:4] }),
    .a1({ \p[13] [14], \p[11] [15], c2[18:0], \p[3] [3], \p[1] [4:3] }),
    .a2({ \p[14] [13], \p[12] [14], c2[37], s2[37:20], \p[4] [2], \p[2] [3:2] }),
    .co(c3[23:0]),
    .s(s3[23:0])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000010011  s3fa1 (
    .a0({ \p[13] [13:12], c2[36:21], \p[3] [2] }),
    .a1({ \p[14] [12:11], c2[53], s2[53:39], \p[4] [1] }),
    .a2({ \p[15] [11:9], c2[52:38], \p[5] [0] }),
    .co({ c3[45:28], c3[24] }),
    .s({ s3[45:28], s3[24] })
  );
  \$paramod\setha\N=s32'00000000000000000000000000000011  s3ha0 (
    .a0({ c2[20], \p[6] [1], \p[5] [1] }),
    .a1({ s2[38], \p[7] [0], \p[6] [0] }),
    .co(c3[27:25]),
    .s(s3[27:25])
  );
  \$paramod\setfa\N=s32'00000000000000000000000000011010  s4fa0 (
    .a0({ \p[13] [15], s3[23:0], \p[0] [3] }),
    .a1({ c3[23:0], \p[3] [1], \p[1] [2] }),
    .a2({ \p[14] [14], c3[45], s3[45:24], \p[4] [0], \p[2] [1] }),
    .co(c4),
    .s(s4)
  );
  \$paramod\setfa\N=s32'00000000000000000000000000011001  s5fa0 (
    .a0({ c4[25], s4[25:3], \p[0] [2] }),
    .a1({ \p[14] [15], c4[24:2], \p[1] [1] }),
    .a2({ \p[15] [14:12], c3[44:24], \p[2] [0] }),
    .co({ c5[27:4], c5[0] }),
    .s({ s5[27:4], s5[0] })
  );
  \$paramod\setha\N=s32'00000000000000000000000000000011  s5ha0 (
    .a0(s4[2:0]),
    .a1({ c4[1:0], \p[3] [0] }),
    .co(c5[3:1]),
    .s(s5[3:1])
  );
  assign abs_a[0] = a[0];
  assign abs_b[0] = b[0];
endmodule

module fa(a, b, c, s, ca);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output s;
  wire s;
  output ca;
  wire ca;
  sky130_fd_sc_hd__maj3_1 _0_ (
    .A(b),
    .B(a),
    .C(c),
    .X(ca)
  );
  sky130_fd_sc_hd__xor3_1 _1_ (
    .A(b),
    .B(a),
    .C(c),
    .X(s)
  );
endmodule

module ha(a, b, s, ca);
  input a;
  wire a;
  input b;
  wire b;
  output s;
  wire s;
  output ca;
  wire ca;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(b),
    .B(a),
    .X(ca)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(b),
    .B(a),
    .X(s)
  );
endmodule

module inv32bits(i, sign, o);
  input [31:0] i;
  wire [31:0] i;
  input sign;
  wire sign;
  output [31:0] o;
  wire [31:0] o;
  sky130_fd_sc_hd__xor2_1 _00_ (
    .A(sign),
    .B(i[0]),
    .X(o[0])
  );
  sky130_fd_sc_hd__xor2_1 _01_ (
    .A(sign),
    .B(i[1]),
    .X(o[1])
  );
  sky130_fd_sc_hd__xor2_1 _02_ (
    .A(sign),
    .B(i[2]),
    .X(o[2])
  );
  sky130_fd_sc_hd__xor2_1 _03_ (
    .A(sign),
    .B(i[3]),
    .X(o[3])
  );
  sky130_fd_sc_hd__xor2_1 _04_ (
    .A(sign),
    .B(i[4]),
    .X(o[4])
  );
  sky130_fd_sc_hd__xor2_1 _05_ (
    .A(sign),
    .B(i[5]),
    .X(o[5])
  );
  sky130_fd_sc_hd__xor2_1 _06_ (
    .A(sign),
    .B(i[6]),
    .X(o[6])
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(sign),
    .B(i[7]),
    .X(o[7])
  );
  sky130_fd_sc_hd__xor2_1 _08_ (
    .A(sign),
    .B(i[8]),
    .X(o[8])
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(sign),
    .B(i[9]),
    .X(o[9])
  );
  sky130_fd_sc_hd__xor2_1 _10_ (
    .A(sign),
    .B(i[10]),
    .X(o[10])
  );
  sky130_fd_sc_hd__xor2_1 _11_ (
    .A(sign),
    .B(i[11]),
    .X(o[11])
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(sign),
    .B(i[12]),
    .X(o[12])
  );
  sky130_fd_sc_hd__xor2_1 _13_ (
    .A(sign),
    .B(i[13]),
    .X(o[13])
  );
  sky130_fd_sc_hd__xor2_1 _14_ (
    .A(sign),
    .B(i[14]),
    .X(o[14])
  );
  sky130_fd_sc_hd__xor2_1 _15_ (
    .A(sign),
    .B(i[15]),
    .X(o[15])
  );
  sky130_fd_sc_hd__xor2_1 _16_ (
    .A(sign),
    .B(i[16]),
    .X(o[16])
  );
  sky130_fd_sc_hd__xor2_1 _17_ (
    .A(sign),
    .B(i[17]),
    .X(o[17])
  );
  sky130_fd_sc_hd__xor2_1 _18_ (
    .A(sign),
    .B(i[18]),
    .X(o[18])
  );
  sky130_fd_sc_hd__xor2_1 _19_ (
    .A(sign),
    .B(i[19]),
    .X(o[19])
  );
  sky130_fd_sc_hd__xor2_1 _20_ (
    .A(sign),
    .B(i[20]),
    .X(o[20])
  );
  sky130_fd_sc_hd__xor2_1 _21_ (
    .A(sign),
    .B(i[21]),
    .X(o[21])
  );
  sky130_fd_sc_hd__xor2_1 _22_ (
    .A(sign),
    .B(i[22]),
    .X(o[22])
  );
  sky130_fd_sc_hd__xor2_1 _23_ (
    .A(sign),
    .B(i[23]),
    .X(o[23])
  );
  sky130_fd_sc_hd__xor2_1 _24_ (
    .A(sign),
    .B(i[24]),
    .X(o[24])
  );
  sky130_fd_sc_hd__xor2_1 _25_ (
    .A(sign),
    .B(i[25]),
    .X(o[25])
  );
  sky130_fd_sc_hd__xor2_1 _26_ (
    .A(sign),
    .B(i[26]),
    .X(o[26])
  );
  sky130_fd_sc_hd__xor2_1 _27_ (
    .A(sign),
    .B(i[27]),
    .X(o[27])
  );
  sky130_fd_sc_hd__xor2_1 _28_ (
    .A(sign),
    .B(i[28]),
    .X(o[28])
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(sign),
    .B(i[29]),
    .X(o[29])
  );
  sky130_fd_sc_hd__xor2_1 _30_ (
    .A(sign),
    .B(i[30]),
    .X(o[30])
  );
  sky130_fd_sc_hd__xor2_1 _31_ (
    .A(sign),
    .B(i[31]),
    .X(o[31])
  );
endmodule
