/* Generated by Yosys 0.57+125 (git sha1 d5053033e, g++ 11.5.0 -fPIC -O3) */

module \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000000100 (A, B, Cin, Sum, Cout);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  input Cin;
  wire Cin;
  output [3:0] Sum;
  wire [3:0] Sum;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [4:0] C;
  sky130_fd_sc_hd__xnor2_1 _07_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _08_ (
    .A(Cin),
    .B(_00_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _09_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _10_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _11_ (
    .A(_01_),
    .B(_02_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__maj3_1 _12_ (
    .A(B[1]),
    .B(A[1]),
    .C(_01_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _14_ (
    .A(_03_),
    .B(_04_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__maj3_1 _15_ (
    .A(B[2]),
    .B(A[2]),
    .C(_03_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(_05_),
    .B(_06_),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__maj3_1 _18_ (
    .A(B[3]),
    .B(A[3]),
    .C(_05_),
    .X(Cout)
  );
  assign { C[4], C[0] } = { Cout, Cin };
endmodule

module \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000000110 (A, B, Cin, Sum, Cout);
  input [5:0] A;
  wire [5:0] A;
  input [5:0] B;
  wire [5:0] B;
  input Cin;
  wire Cin;
  output [5:0] Sum;
  wire [5:0] Sum;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire [6:0] C;
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _20_ (
    .A(Cin),
    .B(_00_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _21_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _22_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _23_ (
    .A(_01_),
    .B(_02_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__maj3_1 _24_ (
    .A(B[1]),
    .B(A[1]),
    .C(_01_),
    .X(_03_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _25_ (
    .A(B[2]),
    .SLEEP(A[2]),
    .X(_04_)
  );
  sky130_fd_sc_hd__and2_0 _26_ (
    .A(B[2]),
    .B(A[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _27_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nand2_1 _28_ (
    .A(_04_),
    .B(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _29_ (
    .A(_03_),
    .B(_07_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__nand2_1 _30_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__xor2_1 _31_ (
    .A(B[3]),
    .B(A[3]),
    .X(_09_)
  );
  sky130_fd_sc_hd__o21ai_0 _32_ (
    .A1(_03_),
    .A2(_05_),
    .B1(_04_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(_09_),
    .B(_10_),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand2_1 _35_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2b_1 _36_ (
    .A_N(_11_),
    .B(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o221ai_1 _37_ (
    .A1(B[3]),
    .A2(A[3]),
    .B1(_03_),
    .B2(_05_),
    .C1(_04_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(_08_),
    .A2(_14_),
    .B1(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__and3_1 _39_ (
    .A(_08_),
    .B(_13_),
    .C(_14_),
    .X(_16_)
  );
  sky130_fd_sc_hd__nor2_1 _40_ (
    .A(_15_),
    .B(_16_),
    .Y(Sum[4])
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a31oi_1 _42_ (
    .A1(_08_),
    .A2(_12_),
    .A3(_14_),
    .B1(_11_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(_17_),
    .B(_18_),
    .Y(Sum[5])
  );
  sky130_fd_sc_hd__maj3_1 _44_ (
    .A(B[5]),
    .B(A[5]),
    .C(_18_),
    .X(Cout)
  );
  assign { C[6], C[0] } = { Cout, Cin };
endmodule

module \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000001000 (A, B, Cin, Sum, Cout);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  input Cin;
  wire Cin;
  output [7:0] Sum;
  wire [7:0] Sum;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [8:0] C;
  sky130_fd_sc_hd__xnor2_1 _27_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(Cin),
    .B(_00_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _29_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _30_ (
    .A(B[1]),
    .SLEEP(A[1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__and2_0 _31_ (
    .A(B[1]),
    .B(A[1]),
    .X(_03_)
  );
  sky130_fd_sc_hd__nand2_1 _32_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(_02_),
    .B(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(_01_),
    .B(_05_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__nand2_1 _35_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xor2_1 _36_ (
    .A(B[2]),
    .B(A[2]),
    .X(_07_)
  );
  sky130_fd_sc_hd__o21ai_0 _37_ (
    .A1(_01_),
    .A2(_03_),
    .B1(_02_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(_07_),
    .B(_08_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__nor2_1 _39_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _40_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor2b_1 _41_ (
    .A(_09_),
    .B_N(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o221ai_1 _42_ (
    .A1(B[2]),
    .A2(A[2]),
    .B1(_01_),
    .B2(_03_),
    .C1(_02_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__and2_0 _43_ (
    .A(_06_),
    .B(_12_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_11_),
    .B(_13_),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__nor2_1 _45_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand2b_1 _47_ (
    .A_N(_14_),
    .B(_15_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a21oi_1 _48_ (
    .A1(_10_),
    .A2(_13_),
    .B1(_09_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _49_ (
    .A(_16_),
    .B(_17_),
    .Y(Sum[4])
  );
  sky130_fd_sc_hd__a311o_1 _50_ (
    .A1(_06_),
    .A2(_10_),
    .A3(_12_),
    .B1(_14_),
    .C1(_09_),
    .X(_18_)
  );
  sky130_fd_sc_hd__nand2_1 _51_ (
    .A(_15_),
    .B(_18_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nand2_1 _52_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _53_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a31oi_1 _54_ (
    .A1(_15_),
    .A2(_18_),
    .A3(_20_),
    .B1(_21_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a21bo_1 _55_ (
    .A1(_20_),
    .A2(_22_),
    .B1_N(_19_),
    .X(_23_)
  );
  sky130_fd_sc_hd__o21ai_0 _56_ (
    .A1(_21_),
    .A2(_22_),
    .B1(_23_),
    .Y(Sum[5])
  );
  sky130_fd_sc_hd__xnor2_1 _57_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__xnor2_1 _58_ (
    .A(_22_),
    .B(_24_),
    .Y(Sum[6])
  );
  sky130_fd_sc_hd__xnor2_1 _59_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__maj3_1 _60_ (
    .A(B[6]),
    .B(A[6]),
    .C(_22_),
    .X(_26_)
  );
  sky130_fd_sc_hd__xnor2_1 _61_ (
    .A(_25_),
    .B(_26_),
    .Y(Sum[7])
  );
  sky130_fd_sc_hd__maj3_1 _62_ (
    .A(B[7]),
    .B(A[7]),
    .C(_26_),
    .X(Cout)
  );
  assign { C[8], C[0] } = { Cout, Cin };
endmodule

module \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000001100 (A, B, Cin, Sum, Cout);
  input [11:0] A;
  wire [11:0] A;
  input [11:0] B;
  wire [11:0] B;
  input Cin;
  wire Cin;
  output [11:0] Sum;
  wire [11:0] Sum;
  output Cout;
  wire Cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire [12:0] C;
  sky130_fd_sc_hd__xnor2_1 _050_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xnor2_1 _051_ (
    .A(Cin),
    .B(_000_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _052_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _053_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _054_ (
    .A(_001_),
    .B(_002_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__maj3_1 _055_ (
    .A(B[1]),
    .B(A[1]),
    .C(_001_),
    .X(_003_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _056_ (
    .A(B[2]),
    .SLEEP(A[2]),
    .X(_004_)
  );
  sky130_fd_sc_hd__and2_0 _057_ (
    .A(B[2]),
    .B(A[2]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _058_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _059_ (
    .A(_004_),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _060_ (
    .A(_003_),
    .B(_007_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__nor2_1 _061_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _062_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _063_ (
    .A(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _064_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__o21ai_0 _065_ (
    .A1(_003_),
    .A2(_005_),
    .B1(_004_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _066_ (
    .A(_011_),
    .B(_012_),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _067_ (
    .A(B[4]),
    .SLEEP(A[4]),
    .X(_013_)
  );
  sky130_fd_sc_hd__and2_0 _068_ (
    .A(B[4]),
    .B(A[4]),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _069_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _070_ (
    .A(_013_),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o221a_1 _071_ (
    .A1(B[3]),
    .A2(A[3]),
    .B1(_003_),
    .B2(_005_),
    .C1(_004_),
    .X(_017_)
  );
  sky130_fd_sc_hd__a21oi_1 _072_ (
    .A1(_009_),
    .A2(_012_),
    .B1(_008_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _073_ (
    .A(_016_),
    .B(_018_),
    .Y(Sum[4])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _074_ (
    .A(B[5]),
    .SLEEP(A[5]),
    .X(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _075_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _076_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__o21ai_0 _077_ (
    .A1(_014_),
    .A2(_018_),
    .B1(_013_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xor2_1 _078_ (
    .A(_021_),
    .B(_022_),
    .X(Sum[5])
  );
  sky130_fd_sc_hd__nor2_1 _079_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _080_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2b_1 _081_ (
    .A(_023_),
    .B_N(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o311ai_0 _082_ (
    .A1(_010_),
    .A2(_014_),
    .A3(_017_),
    .B1(_019_),
    .C1(_013_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__and2_0 _083_ (
    .A(_020_),
    .B(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _084_ (
    .A(_025_),
    .B(_027_),
    .Y(Sum[6])
  );
  sky130_fd_sc_hd__nor2_1 _085_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__and2_0 _086_ (
    .A(B[7]),
    .B(A[7]),
    .X(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _087_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _088_ (
    .A1(_024_),
    .A2(_027_),
    .B1(_023_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xor2_1 _089_ (
    .A(_030_),
    .B(_031_),
    .X(Sum[7])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _090_ (
    .A(B[8]),
    .SLEEP(A[8]),
    .X(_032_)
  );
  sky130_fd_sc_hd__and2_0 _091_ (
    .A(B[8]),
    .B(A[8]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _092_ (
    .A(B[8]),
    .B(A[8]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _093_ (
    .A(_032_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a311oi_1 _094_ (
    .A1(_020_),
    .A2(_024_),
    .A3(_026_),
    .B1(_028_),
    .C1(_023_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _095_ (
    .A(_029_),
    .SLEEP(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__xnor2_1 _096_ (
    .A(_035_),
    .B(_037_),
    .Y(Sum[8])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _097_ (
    .A(B[9]),
    .SLEEP(A[9]),
    .X(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _098_ (
    .A(B[9]),
    .B(A[9]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _099_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _100_ (
    .A1(_033_),
    .A2(_037_),
    .B1(_032_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xor2_1 _101_ (
    .A(_040_),
    .B(_041_),
    .X(Sum[9])
  );
  sky130_fd_sc_hd__nor2_1 _102_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _103_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2b_1 _104_ (
    .A_N(_042_),
    .B(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o311ai_0 _105_ (
    .A1(_029_),
    .A2(_033_),
    .A3(_036_),
    .B1(_038_),
    .C1(_032_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a21oi_1 _106_ (
    .A1(_039_),
    .A2(_045_),
    .B1(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__and3_1 _107_ (
    .A(_039_),
    .B(_044_),
    .C(_045_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _108_ (
    .A(_046_),
    .B(_047_),
    .Y(Sum[10])
  );
  sky130_fd_sc_hd__xnor2_1 _109_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a31oi_1 _110_ (
    .A1(_039_),
    .A2(_043_),
    .A3(_045_),
    .B1(_042_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xnor2_1 _111_ (
    .A(_048_),
    .B(_049_),
    .Y(Sum[11])
  );
  sky130_fd_sc_hd__maj3_1 _112_ (
    .A(B[11]),
    .B(A[11]),
    .C(_049_),
    .X(Cout)
  );
  assign { C[12], C[0] } = { Cout, Cin };
endmodule

module \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000010000 (A, B, Cin, Sum, Cout);
  input [15:0] A;
  wire [15:0] A;
  input [15:0] B;
  wire [15:0] B;
  input Cin;
  wire Cin;
  output [15:0] Sum;
  wire [15:0] Sum;
  output Cout;
  wire Cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire [16:0] C;
  sky130_fd_sc_hd__xnor2_1 _070_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _071_ (
    .A(Cin),
    .B(_030_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _072_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_031_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _073_ (
    .A(B[1]),
    .SLEEP(A[1]),
    .X(_032_)
  );
  sky130_fd_sc_hd__and2_0 _074_ (
    .A(B[1]),
    .B(A[1]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _075_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _076_ (
    .A(_032_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xnor2_1 _077_ (
    .A(_031_),
    .B(_035_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__nand2_1 _078_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xor2_1 _079_ (
    .A(B[2]),
    .B(A[2]),
    .X(_037_)
  );
  sky130_fd_sc_hd__o21ai_0 _080_ (
    .A1(_031_),
    .A2(_033_),
    .B1(_032_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _081_ (
    .A(_037_),
    .B(_038_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__nor2_1 _082_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _083_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2b_1 _084_ (
    .A_N(_039_),
    .B(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o221ai_1 _085_ (
    .A1(B[2]),
    .A2(A[2]),
    .B1(_031_),
    .B2(_033_),
    .C1(_032_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _086_ (
    .A(_036_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xnor2_1 _087_ (
    .A(_041_),
    .B(_043_),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__nand2_1 _088_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__xnor2_1 _089_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a31oi_1 _090_ (
    .A1(_036_),
    .A2(_040_),
    .A3(_042_),
    .B1(_039_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a311oi_1 _091_ (
    .A1(_036_),
    .A2(_040_),
    .A3(_042_),
    .B1(_045_),
    .C1(_039_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _092_ (
    .A(_045_),
    .B(_046_),
    .Y(Sum[4])
  );
  sky130_fd_sc_hd__nor2_1 _093_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2b_1 _095_ (
    .A(_048_),
    .B_N(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _096_ (
    .A1(B[4]),
    .A2(A[4]),
    .B1(_047_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(_050_),
    .B(_051_),
    .Y(Sum[5])
  );
  sky130_fd_sc_hd__nand2_1 _098_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xor2_1 _099_ (
    .A(B[6]),
    .B(A[6]),
    .X(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _100_ (
    .A(_044_),
    .B(_049_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o21ai_0 _101_ (
    .A1(_048_),
    .A2(_051_),
    .B1(_049_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o221ai_1 _102_ (
    .A1(B[5]),
    .A2(A[5]),
    .B1(_047_),
    .B2(_054_),
    .C1(_053_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xor2_1 _103_ (
    .A(_053_),
    .B(_055_),
    .X(Sum[6])
  );
  sky130_fd_sc_hd__nor2_1 _104_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _105_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2b_1 _106_ (
    .A(_057_),
    .B_N(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__o211ai_1 _107_ (
    .A1(_048_),
    .A2(_051_),
    .B1(_052_),
    .C1(_049_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21ai_0 _108_ (
    .A1(B[6]),
    .A2(A[6]),
    .B1(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xnor2_1 _109_ (
    .A(_059_),
    .B(_061_),
    .Y(Sum[7])
  );
  sky130_fd_sc_hd__and2_0 _110_ (
    .A(B[8]),
    .B(A[8]),
    .X(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _111_ (
    .A(B[8]),
    .B(A[8]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a31oi_1 _112_ (
    .A1(_052_),
    .A2(_056_),
    .A3(_058_),
    .B1(_057_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a311oi_1 _113_ (
    .A1(_052_),
    .A2(_056_),
    .A3(_058_),
    .B1(_063_),
    .C1(_057_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _114_ (
    .A(_063_),
    .B(_064_),
    .Y(Sum[8])
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(B[9]),
    .B(A[9]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xor2_1 _116_ (
    .A(B[9]),
    .B(A[9]),
    .X(_067_)
  );
  sky130_fd_sc_hd__o21ai_0 _117_ (
    .A1(_062_),
    .A2(_065_),
    .B1(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor3_1 _118_ (
    .A(_062_),
    .B(_065_),
    .C(_067_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _119_ (
    .A(_068_),
    .SLEEP(_069_),
    .X(Sum[9])
  );
  sky130_fd_sc_hd__nor2_1 _120_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2b_1 _122_ (
    .A_N(_000_),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__o22ai_1 _123_ (
    .A1(B[9]),
    .A2(A[9]),
    .B1(_062_),
    .B2(_065_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(_066_),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21o_1 _125_ (
    .A1(_066_),
    .A2(_003_),
    .B1(_002_),
    .X(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _126_ (
    .A(_002_),
    .B(_004_),
    .Y(Sum[10])
  );
  sky130_fd_sc_hd__nor2_1 _127_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2b_1 _129_ (
    .A_N(_006_),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a31oi_1 _130_ (
    .A1(_066_),
    .A2(_068_),
    .A3(_001_),
    .B1(_000_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a311o_1 _131_ (
    .A1(_066_),
    .A2(_068_),
    .A3(_001_),
    .B1(_008_),
    .C1(_000_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _132_ (
    .A(_008_),
    .B(_009_),
    .Y(Sum[11])
  );
  sky130_fd_sc_hd__nor2_1 _133_ (
    .A(B[12]),
    .B(A[12]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(B[12]),
    .B(A[12]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2b_1 _135_ (
    .A_N(_011_),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a31oi_1 _136_ (
    .A1(_001_),
    .A2(_005_),
    .A3(_007_),
    .B1(_006_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a311o_1 _137_ (
    .A1(_001_),
    .A2(_005_),
    .A3(_007_),
    .B1(_013_),
    .C1(_006_),
    .X(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _138_ (
    .A(_013_),
    .B(_014_),
    .Y(Sum[12])
  );
  sky130_fd_sc_hd__nor2_1 _139_ (
    .A(B[13]),
    .B(A[13]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(B[13]),
    .B(A[13]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2b_1 _141_ (
    .A_N(_016_),
    .B(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a31oi_1 _142_ (
    .A1(_007_),
    .A2(_010_),
    .A3(_012_),
    .B1(_011_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a311oi_1 _143_ (
    .A1(_007_),
    .A2(_010_),
    .A3(_012_),
    .B1(_018_),
    .C1(_011_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _144_ (
    .A(_018_),
    .B(_019_),
    .Y(Sum[13])
  );
  sky130_fd_sc_hd__nand2_1 _145_ (
    .A(B[14]),
    .B(A[14]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _146_ (
    .A(B[14]),
    .B(A[14]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a31oi_1 _147_ (
    .A1(_012_),
    .A2(_015_),
    .A3(_017_),
    .B1(_016_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a311o_1 _148_ (
    .A1(_012_),
    .A2(_015_),
    .A3(_017_),
    .B1(_022_),
    .C1(_016_),
    .X(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _149_ (
    .A(_022_),
    .B(_023_),
    .Y(Sum[14])
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(B[15]),
    .B(A[15]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(B[15]),
    .B(A[15]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2b_1 _152_ (
    .A(_025_),
    .B_N(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _153_ (
    .A(_017_),
    .B(_021_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o22ai_1 _154_ (
    .A1(B[14]),
    .A2(A[14]),
    .B1(_020_),
    .B2(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(_027_),
    .B(_029_),
    .Y(Sum[15])
  );
  sky130_fd_sc_hd__a31oi_1 _156_ (
    .A1(_021_),
    .A2(_024_),
    .A3(_026_),
    .B1(_025_),
    .Y(Cout)
  );
  assign { C[16], C[0] } = { Cout, Cin };
endmodule

module \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000011000 (A, B, Cin, Sum, Cout);
  input [23:0] A;
  wire [23:0] A;
  input [23:0] B;
  wire [23:0] B;
  input Cin;
  wire Cin;
  output [23:0] Sum;
  wire [23:0] Sum;
  output Cout;
  wire Cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire [24:0] C;
  sky130_fd_sc_hd__xnor2_1 _113_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _114_ (
    .A(Cin),
    .B(_093_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _115_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_094_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _116_ (
    .A(B[1]),
    .SLEEP(A[1]),
    .X(_095_)
  );
  sky130_fd_sc_hd__and2_0 _117_ (
    .A(B[1]),
    .B(A[1]),
    .X(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _119_ (
    .A(_095_),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _120_ (
    .A(_094_),
    .B(_098_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__nor2_1 _121_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _122_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xor2_1 _123_ (
    .A(B[2]),
    .B(A[2]),
    .X(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _124_ (
    .A1(_094_),
    .A2(_096_),
    .B1(_095_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o211a_1 _125_ (
    .A1(_094_),
    .A2(_096_),
    .B1(_101_),
    .C1(_095_),
    .X(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _126_ (
    .A(_101_),
    .B(_102_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__nand2_1 _127_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__xnor2_1 _128_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21ai_0 _129_ (
    .A1(_099_),
    .A2(_102_),
    .B1(_100_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xnor2_1 _130_ (
    .A(_105_),
    .B(_106_),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _131_ (
    .A(B[4]),
    .SLEEP(A[4]),
    .X(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _132_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _133_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(_100_),
    .B(_104_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o22a_1 _135_ (
    .A1(B[3]),
    .A2(A[3]),
    .B1(_103_),
    .B2(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__xnor2_1 _136_ (
    .A(_109_),
    .B(_111_),
    .Y(Sum[4])
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _138_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2b_1 _139_ (
    .A_N(_112_),
    .B(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o221ai_1 _140_ (
    .A1(B[3]),
    .A2(A[3]),
    .B1(_103_),
    .B2(_110_),
    .C1(_107_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _141_ (
    .A(_108_),
    .B(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xnor2_1 _142_ (
    .A(_001_),
    .B(_003_),
    .Y(Sum[5])
  );
  sky130_fd_sc_hd__nor2_1 _143_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _144_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2b_1 _145_ (
    .A(_004_),
    .B_N(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _146_ (
    .A(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_0 _147_ (
    .A1(B[5]),
    .A2(A[5]),
    .B1(_003_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _148_ (
    .A(_000_),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a311o_1 _149_ (
    .A1(_108_),
    .A2(_000_),
    .A3(_002_),
    .B1(_007_),
    .C1(_112_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _150_ (
    .A(_007_),
    .B(_009_),
    .Y(Sum[6])
  );
  sky130_fd_sc_hd__nor2_1 _151_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _152_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a31oi_1 _153_ (
    .A1(_000_),
    .A2(_005_),
    .A3(_008_),
    .B1(_004_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xnor2_1 _154_ (
    .A(_012_),
    .B(_013_),
    .Y(Sum[7])
  );
  sky130_fd_sc_hd__nand2_1 _155_ (
    .A(B[8]),
    .B(A[8]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(B[8]),
    .B(A[8]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a22oi_1 _157_ (
    .A1(B[6]),
    .A2(A[6]),
    .B1(B[7]),
    .B2(A[7]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a21oi_1 _158_ (
    .A1(_010_),
    .A2(_016_),
    .B1(_011_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a211oi_1 _159_ (
    .A1(_010_),
    .A2(_016_),
    .B1(_015_),
    .C1(_011_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _160_ (
    .A(_015_),
    .B(_017_),
    .Y(Sum[8])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _161_ (
    .A(B[9]),
    .SLEEP(A[9]),
    .X(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(B[9]),
    .B(A[9]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__and2_0 _163_ (
    .A(_019_),
    .B(_020_),
    .X(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _164_ (
    .A1(B[8]),
    .A2(A[8]),
    .B1(_018_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _165_ (
    .A(_021_),
    .B(_022_),
    .Y(Sum[9])
  );
  sky130_fd_sc_hd__nand2_1 _166_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xor2_1 _167_ (
    .A(B[10]),
    .B(A[10]),
    .X(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(_014_),
    .B(_020_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o21ai_0 _169_ (
    .A1(_018_),
    .A2(_025_),
    .B1(_019_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o211ai_1 _170_ (
    .A1(_018_),
    .A2(_025_),
    .B1(_024_),
    .C1(_019_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _171_ (
    .A(_024_),
    .B(_026_),
    .Y(Sum[10])
  );
  sky130_fd_sc_hd__nor2_1 _172_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _173_ (
    .A(B[11]),
    .SLEEP(A[11]),
    .X(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _174_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(_023_),
    .B(_027_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xnor2_1 _177_ (
    .A(_031_),
    .B(_032_),
    .Y(Sum[11])
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(B[12]),
    .B(A[12]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xnor2_1 _179_ (
    .A(B[12]),
    .B(A[12]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__and2_0 _180_ (
    .A(_023_),
    .B(_030_),
    .X(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(_027_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(_029_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a211oi_1 _183_ (
    .A1(_027_),
    .A2(_035_),
    .B1(_034_),
    .C1(_028_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xor2_1 _184_ (
    .A(_034_),
    .B(_037_),
    .X(Sum[12])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _185_ (
    .A(B[13]),
    .SLEEP(A[13]),
    .X(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(B[13]),
    .B(A[13]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__and2_0 _187_ (
    .A(_039_),
    .B(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _188_ (
    .A1(B[12]),
    .A2(A[12]),
    .B1(_038_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xnor2_1 _189_ (
    .A(_041_),
    .B(_042_),
    .Y(Sum[13])
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(B[14]),
    .B(A[14]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _191_ (
    .A(B[14]),
    .B(A[14]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(_033_),
    .B(_040_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o21ai_0 _193_ (
    .A1(_038_),
    .A2(_045_),
    .B1(_039_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o211ai_1 _194_ (
    .A1(_038_),
    .A2(_045_),
    .B1(_044_),
    .C1(_039_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _195_ (
    .A(_044_),
    .B(_046_),
    .Y(Sum[14])
  );
  sky130_fd_sc_hd__nand2_1 _196_ (
    .A(B[15]),
    .B(A[15]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _197_ (
    .A(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(B[15]),
    .B(A[15]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _199_ (
    .A1(_043_),
    .A2(_047_),
    .B1(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand3_1 _200_ (
    .A(_043_),
    .B(_047_),
    .C(_050_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2b_1 _201_ (
    .A(_051_),
    .B_N(_052_),
    .Y(Sum[15])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _202_ (
    .A(B[16]),
    .SLEEP(A[16]),
    .X(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(B[16]),
    .B(A[16]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(_049_),
    .B(_051_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21bai_1 _206_ (
    .A1(_049_),
    .A2(_051_),
    .B1_N(_055_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xor2_1 _207_ (
    .A(_055_),
    .B(_056_),
    .X(Sum[16])
  );
  sky130_fd_sc_hd__nor2_1 _208_ (
    .A(B[17]),
    .B(A[17]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(B[17]),
    .B(A[17]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2b_1 _210_ (
    .A(_058_),
    .B_N(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(_048_),
    .B(_054_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o21ai_0 _212_ (
    .A1(_051_),
    .A2(_061_),
    .B1(_053_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o211ai_1 _213_ (
    .A1(_051_),
    .A2(_061_),
    .B1(_060_),
    .C1(_053_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor2_1 _214_ (
    .A(_060_),
    .B(_062_),
    .Y(Sum[17])
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(B[18]),
    .B(A[18]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(B[18]),
    .B(A[18]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2b_1 _217_ (
    .A_N(_064_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a31oi_1 _218_ (
    .A1(_054_),
    .A2(_057_),
    .A3(_059_),
    .B1(_058_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a311o_1 _219_ (
    .A1(_054_),
    .A2(_057_),
    .A3(_059_),
    .B1(_066_),
    .C1(_058_),
    .X(_068_)
  );
  sky130_fd_sc_hd__xnor2_1 _220_ (
    .A(_066_),
    .B(_067_),
    .Y(Sum[18])
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(B[19]),
    .B(A[19]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(B[19]),
    .B(A[19]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2b_1 _223_ (
    .A_N(_069_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a31oi_1 _224_ (
    .A1(_059_),
    .A2(_063_),
    .A3(_065_),
    .B1(_064_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a311oi_1 _225_ (
    .A1(_059_),
    .A2(_063_),
    .A3(_065_),
    .B1(_071_),
    .C1(_064_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__xnor2_1 _226_ (
    .A(_071_),
    .B(_072_),
    .Y(Sum[19])
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(B[20]),
    .B(A[20]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xnor2_1 _228_ (
    .A(B[20]),
    .B(A[20]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a31oi_1 _229_ (
    .A1(_065_),
    .A2(_068_),
    .A3(_070_),
    .B1(_069_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a311o_1 _230_ (
    .A1(_065_),
    .A2(_068_),
    .A3(_070_),
    .B1(_075_),
    .C1(_069_),
    .X(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _231_ (
    .A(_075_),
    .B(_076_),
    .Y(Sum[20])
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(B[21]),
    .B(A[21]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(B[21]),
    .B(A[21]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2b_1 _234_ (
    .A(_078_),
    .B_N(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(_070_),
    .B(_074_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o22ai_1 _236_ (
    .A1(B[20]),
    .A2(A[20]),
    .B1(_073_),
    .B2(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o221ai_1 _237_ (
    .A1(B[20]),
    .A2(A[20]),
    .B1(_073_),
    .B2(_081_),
    .C1(_080_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xnor2_1 _238_ (
    .A(_080_),
    .B(_082_),
    .Y(Sum[21])
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(B[22]),
    .B(A[22]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(B[22]),
    .B(A[22]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2b_1 _241_ (
    .A_N(_084_),
    .B(_085_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a31oi_1 _242_ (
    .A1(_074_),
    .A2(_077_),
    .A3(_079_),
    .B1(_078_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a311o_1 _243_ (
    .A1(_074_),
    .A2(_077_),
    .A3(_079_),
    .B1(_086_),
    .C1(_078_),
    .X(_088_)
  );
  sky130_fd_sc_hd__xnor2_1 _244_ (
    .A(_086_),
    .B(_087_),
    .Y(Sum[22])
  );
  sky130_fd_sc_hd__nor2_1 _245_ (
    .A(B[23]),
    .B(A[23]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(B[23]),
    .B(A[23]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2b_1 _247_ (
    .A_N(_089_),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a31oi_1 _248_ (
    .A1(_079_),
    .A2(_083_),
    .A3(_085_),
    .B1(_084_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _249_ (
    .A(_091_),
    .B(_092_),
    .Y(Sum[23])
  );
  sky130_fd_sc_hd__a31oi_1 _250_ (
    .A1(_085_),
    .A2(_088_),
    .A3(_090_),
    .B1(_089_),
    .Y(Cout)
  );
  assign { C[24], C[0] } = { Cout, Cin };
endmodule

module \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000100000 (A, B, Cin, Sum, Cout);
  input [31:0] A;
  wire [31:0] A;
  input [31:0] B;
  wire [31:0] B;
  input Cin;
  wire Cin;
  output [31:0] Sum;
  wire [31:0] Sum;
  output Cout;
  wire Cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire [32:0] C;
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__xnor2_1 _164_ (
    .A(Cin),
    .B(_162_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _165_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_000_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _166_ (
    .A(B[1]),
    .SLEEP(A[1]),
    .X(_001_)
  );
  sky130_fd_sc_hd__and2_0 _167_ (
    .A(B[1]),
    .B(A[1]),
    .X(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _169_ (
    .A(_001_),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _170_ (
    .A(_000_),
    .B(_004_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xor2_1 _172_ (
    .A(B[2]),
    .B(A[2]),
    .X(_006_)
  );
  sky130_fd_sc_hd__a21oi_1 _173_ (
    .A1(_000_),
    .A2(_001_),
    .B1(_002_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _174_ (
    .A(_006_),
    .B(_007_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _176_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a221oi_1 _177_ (
    .A1(B[2]),
    .A2(A[2]),
    .B1(_000_),
    .B2(_001_),
    .C1(_002_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o21a_1 _178_ (
    .A1(_005_),
    .A2(_010_),
    .B1(_009_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nor3_1 _179_ (
    .A(_005_),
    .B(_009_),
    .C(_010_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(_011_),
    .B(_012_),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _181_ (
    .A(B[4]),
    .SLEEP(A[4]),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _184_ (
    .A1(B[3]),
    .A2(A[3]),
    .B1(_012_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xor2_1 _185_ (
    .A(_015_),
    .B(_016_),
    .X(Sum[4])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _186_ (
    .A(B[5]),
    .SLEEP(A[5]),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_0 _187_ (
    .A(B[5]),
    .B(A[5]),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(_017_),
    .B(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o311ai_0 _190_ (
    .A1(_005_),
    .A2(_009_),
    .A3(_010_),
    .B1(_014_),
    .C1(_008_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__and2_0 _191_ (
    .A(_013_),
    .B(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _192_ (
    .A(_020_),
    .B(_022_),
    .Y(Sum[5])
  );
  sky130_fd_sc_hd__a21oi_1 _193_ (
    .A1(_017_),
    .A2(_022_),
    .B1(_018_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__and2_0 _195_ (
    .A(B[6]),
    .B(A[6]),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _196_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _197_ (
    .A(_023_),
    .B(_026_),
    .Y(Sum[6])
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2b_1 _200_ (
    .A_N(_027_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a311oi_1 _201_ (
    .A1(_013_),
    .A2(_017_),
    .A3(_021_),
    .B1(_025_),
    .C1(_018_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _202_ (
    .A(_024_),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _203_ (
    .A(_029_),
    .B(_031_),
    .Y(Sum[7])
  );
  sky130_fd_sc_hd__nor2_1 _204_ (
    .A(B[8]),
    .B(A[8]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__and2_0 _205_ (
    .A(B[8]),
    .B(A[8]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(B[8]),
    .B(A[8]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o31a_1 _207_ (
    .A1(_024_),
    .A2(_027_),
    .A3(_030_),
    .B1(_028_),
    .X(_035_)
  );
  sky130_fd_sc_hd__or3_1 _208_ (
    .A(_032_),
    .B(_033_),
    .C(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__o21ai_0 _209_ (
    .A1(_032_),
    .A2(_033_),
    .B1(_035_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__and2_0 _210_ (
    .A(_036_),
    .B(_037_),
    .X(Sum[8])
  );
  sky130_fd_sc_hd__nor2_1 _211_ (
    .A(B[9]),
    .B(A[9]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(B[9]),
    .B(A[9]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2b_1 _213_ (
    .A(_038_),
    .B_N(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o311a_1 _214_ (
    .A1(_024_),
    .A2(_027_),
    .A3(_030_),
    .B1(_034_),
    .C1(_028_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(_032_),
    .B(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xor2_1 _216_ (
    .A(_040_),
    .B(_042_),
    .X(Sum[9])
  );
  sky130_fd_sc_hd__nor2_1 _217_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(B[10]),
    .B(A[10]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2b_1 _219_ (
    .A_N(_043_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a31oi_1 _220_ (
    .A1(_034_),
    .A2(_036_),
    .A3(_039_),
    .B1(_038_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2b_1 _221_ (
    .A_N(_045_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _222_ (
    .A(_045_),
    .B(_046_),
    .Y(Sum[10])
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(B[11]),
    .B(A[11]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2b_1 _225_ (
    .A_N(_048_),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o311a_1 _226_ (
    .A1(_032_),
    .A2(_038_),
    .A3(_041_),
    .B1(_044_),
    .C1(_039_),
    .X(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(_043_),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xnor2_1 _228_ (
    .A(_050_),
    .B(_052_),
    .Y(Sum[11])
  );
  sky130_fd_sc_hd__nor2_1 _229_ (
    .A(B[12]),
    .B(A[12]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(B[12]),
    .B(A[12]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2b_1 _231_ (
    .A(_053_),
    .B_N(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _232_ (
    .A(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a31oi_1 _233_ (
    .A1(_044_),
    .A2(_047_),
    .A3(_049_),
    .B1(_048_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _234_ (
    .A(_056_),
    .B(_057_),
    .Y(Sum[12])
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(B[13]),
    .B(A[13]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(B[13]),
    .B(A[13]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2b_1 _237_ (
    .A(_058_),
    .B_N(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21o_1 _238_ (
    .A1(_049_),
    .A2(_054_),
    .B1(_053_),
    .X(_061_)
  );
  sky130_fd_sc_hd__o41ai_1 _239_ (
    .A1(_043_),
    .A2(_050_),
    .A3(_051_),
    .A4(_056_),
    .B1(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xor2_1 _240_ (
    .A(_060_),
    .B(_062_),
    .X(Sum[13])
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(B[14]),
    .B(A[14]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(B[14]),
    .B(A[14]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2b_1 _243_ (
    .A(_063_),
    .B_N(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21ai_0 _244_ (
    .A1(_054_),
    .A2(_058_),
    .B1(_059_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a31oi_1 _245_ (
    .A1(_055_),
    .A2(_057_),
    .A3(_060_),
    .B1(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xnor2_1 _246_ (
    .A(_065_),
    .B(_067_),
    .Y(Sum[14])
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(B[15]),
    .B(A[15]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(B[15]),
    .B(A[15]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2b_1 _249_ (
    .A(_068_),
    .B_N(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a21oi_1 _250_ (
    .A1(_059_),
    .A2(_064_),
    .B1(_063_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a31oi_1 _251_ (
    .A1(_060_),
    .A2(_062_),
    .A3(_065_),
    .B1(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _252_ (
    .A(_070_),
    .B(_072_),
    .Y(Sum[15])
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(B[16]),
    .B(A[16]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(B[16]),
    .B(A[16]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2b_1 _255_ (
    .A(_073_),
    .B_N(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o211ai_1 _256_ (
    .A1(_063_),
    .A2(_067_),
    .B1(_069_),
    .C1(_064_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o21ai_0 _257_ (
    .A1(B[15]),
    .A2(A[15]),
    .B1(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _258_ (
    .A(_075_),
    .B(_077_),
    .Y(Sum[16])
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(B[17]),
    .B(A[17]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xnor2_1 _260_ (
    .A(B[17]),
    .B(A[17]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o211a_1 _261_ (
    .A1(_068_),
    .A2(_072_),
    .B1(_074_),
    .C1(_069_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _262_ (
    .A(_073_),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor3_1 _263_ (
    .A(_073_),
    .B(_079_),
    .C(_080_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xnor2_1 _264_ (
    .A(_079_),
    .B(_081_),
    .Y(Sum[17])
  );
  sky130_fd_sc_hd__nor2_1 _265_ (
    .A(B[18]),
    .B(A[18]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _266_ (
    .A(B[18]),
    .B(A[18]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2b_1 _267_ (
    .A(_083_),
    .B_N(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o31a_1 _268_ (
    .A1(_073_),
    .A2(_079_),
    .A3(_080_),
    .B1(_078_),
    .X(_086_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_085_),
    .B(_086_),
    .Y(Sum[18])
  );
  sky130_fd_sc_hd__nor2_1 _270_ (
    .A(B[19]),
    .B(A[19]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xor2_1 _271_ (
    .A(B[19]),
    .B(A[19]),
    .X(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(_078_),
    .B(_084_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o21ai_0 _273_ (
    .A1(_083_),
    .A2(_086_),
    .B1(_084_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o221ai_1 _274_ (
    .A1(B[18]),
    .A2(A[18]),
    .B1(_082_),
    .B2(_089_),
    .C1(_088_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xor2_1 _275_ (
    .A(_088_),
    .B(_090_),
    .X(Sum[19])
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(B[20]),
    .B(A[20]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(B[20]),
    .B(A[20]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2b_1 _278_ (
    .A_N(_092_),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _279_ (
    .A(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(_085_),
    .B(_088_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(_084_),
    .B(_087_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _282_ (
    .A1(B[19]),
    .A2(A[19]),
    .B1(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o21ai_0 _283_ (
    .A1(_086_),
    .A2(_096_),
    .B1(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__xnor2_1 _284_ (
    .A(_094_),
    .B(_099_),
    .Y(Sum[20])
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(B[21]),
    .B(A[21]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _286_ (
    .A(B[21]),
    .B(A[21]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2b_1 _287_ (
    .A(_100_),
    .B_N(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _288_ (
    .A(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a22oi_1 _289_ (
    .A1(B[19]),
    .A2(A[19]),
    .B1(B[20]),
    .B2(A[20]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a21oi_1 _290_ (
    .A1(_091_),
    .A2(_104_),
    .B1(_092_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(_102_),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a211oi_1 _292_ (
    .A1(_091_),
    .A2(_104_),
    .B1(_103_),
    .C1(_092_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_106_),
    .B(_107_),
    .Y(Sum[21])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _294_ (
    .A(B[22]),
    .SLEEP(A[22]),
    .X(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(B[22]),
    .B(A[22]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__and2_0 _296_ (
    .A(_108_),
    .B(_109_),
    .X(_110_)
  );
  sky130_fd_sc_hd__o21ai_0 _297_ (
    .A1(_093_),
    .A2(_100_),
    .B1(_101_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a31oi_1 _298_ (
    .A1(_095_),
    .A2(_099_),
    .A3(_102_),
    .B1(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _299_ (
    .A(_110_),
    .B(_112_),
    .Y(Sum[22])
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(B[23]),
    .B(A[23]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xor2_1 _301_ (
    .A(B[23]),
    .B(A[23]),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(_101_),
    .B(_109_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o21ai_0 _303_ (
    .A1(_107_),
    .A2(_115_),
    .B1(_108_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o211a_1 _304_ (
    .A1(_107_),
    .A2(_115_),
    .B1(_114_),
    .C1(_108_),
    .X(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _305_ (
    .A(_114_),
    .B(_116_),
    .Y(Sum[23])
  );
  sky130_fd_sc_hd__xor2_1 _306_ (
    .A(B[24]),
    .B(A[24]),
    .X(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(_110_),
    .B(_114_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _308_ (
    .A(_109_),
    .B(_113_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21oi_1 _309_ (
    .A1(B[23]),
    .A2(A[23]),
    .B1(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o21a_1 _310_ (
    .A1(_112_),
    .A2(_119_),
    .B1(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _311_ (
    .A(_118_),
    .B(_122_),
    .Y(Sum[24])
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(B[25]),
    .B(A[25]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xor2_1 _313_ (
    .A(B[25]),
    .B(A[25]),
    .X(_124_)
  );
  sky130_fd_sc_hd__a22o_1 _314_ (
    .A1(B[23]),
    .A2(A[23]),
    .B1(B[24]),
    .B2(A[24]),
    .X(_125_)
  );
  sky130_fd_sc_hd__o22ai_1 _315_ (
    .A1(B[24]),
    .A2(A[24]),
    .B1(_117_),
    .B2(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o221ai_1 _316_ (
    .A1(B[24]),
    .A2(A[24]),
    .B1(_117_),
    .B2(_125_),
    .C1(_124_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _317_ (
    .A(_124_),
    .B(_126_),
    .Y(Sum[25])
  );
  sky130_fd_sc_hd__o211ai_1 _318_ (
    .A1(B[25]),
    .A2(A[25]),
    .B1(B[24]),
    .C1(A[24]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _319_ (
    .A(_118_),
    .B(_124_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o211a_1 _320_ (
    .A1(_122_),
    .A2(_129_),
    .B1(_128_),
    .C1(_123_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nor2_1 _321_ (
    .A(B[26]),
    .B(A[26]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(B[26]),
    .B(A[26]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2b_1 _323_ (
    .A(_131_),
    .B_N(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xnor2_1 _324_ (
    .A(_130_),
    .B(_133_),
    .Y(Sum[26])
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(B[27]),
    .B(A[27]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _326_ (
    .A(B[27]),
    .B(A[27]),
    .X(_135_)
  );
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a31oi_1 _328_ (
    .A1(_123_),
    .A2(_127_),
    .A3(_132_),
    .B1(_131_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_135_),
    .B(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a311oi_1 _330_ (
    .A1(_123_),
    .A2(_127_),
    .A3(_132_),
    .B1(_136_),
    .C1(_131_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_138_),
    .B(_139_),
    .Y(Sum[27])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _332_ (
    .A(B[28]),
    .SLEEP(A[28]),
    .X(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(B[28]),
    .B(A[28]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(_132_),
    .B(_134_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21ai_0 _336_ (
    .A1(B[27]),
    .A2(A[27]),
    .B1(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(_133_),
    .B(_135_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _338_ (
    .A1(_130_),
    .A2(_145_),
    .B1(_144_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__xnor2_1 _339_ (
    .A(_142_),
    .B(_146_),
    .Y(Sum[28])
  );
  sky130_fd_sc_hd__nor2_1 _340_ (
    .A(B[29]),
    .B(A[29]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _341_ (
    .A(B[29]),
    .B(A[29]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2b_1 _342_ (
    .A(_147_),
    .B_N(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(_134_),
    .B(_141_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _344_ (
    .A1(_139_),
    .A2(_150_),
    .B1(_140_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o211ai_1 _345_ (
    .A1(_139_),
    .A2(_150_),
    .B1(_149_),
    .C1(_140_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__xnor2_1 _346_ (
    .A(_149_),
    .B(_151_),
    .Y(Sum[29])
  );
  sky130_fd_sc_hd__o21ai_0 _347_ (
    .A1(_141_),
    .A2(_147_),
    .B1(_148_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a41oi_1 _348_ (
    .A1(_140_),
    .A2(_141_),
    .A3(_146_),
    .A4(_149_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(B[30]),
    .B(A[30]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(B[30]),
    .B(A[30]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2b_1 _351_ (
    .A(_155_),
    .B_N(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _352_ (
    .A(_154_),
    .B(_157_),
    .Y(Sum[30])
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(B[31]),
    .B(A[31]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xnor2_1 _354_ (
    .A(B[31]),
    .B(A[31]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a31oi_1 _355_ (
    .A1(_148_),
    .A2(_152_),
    .A3(_156_),
    .B1(_155_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__xnor2_1 _356_ (
    .A(_159_),
    .B(_160_),
    .Y(Sum[31])
  );
  sky130_fd_sc_hd__o211ai_1 _357_ (
    .A1(_154_),
    .A2(_155_),
    .B1(_156_),
    .C1(_158_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o21a_1 _358_ (
    .A1(B[31]),
    .A2(A[31]),
    .B1(_161_),
    .X(Cout)
  );
  assign { C[32], C[0] } = { Cout, Cin };
endmodule

module KSA32(A, B, Cin, Sum, Cout);
  input [31:0] A;
  wire [31:0] A;
  input [31:0] B;
  wire [31:0] B;
  input Cin;
  wire Cin;
  output [31:0] Sum;
  wire [31:0] Sum;
  output Cout;
  wire Cout;
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000100000  ksa32 (
    .A(A),
    .B(B),
    .Cin(Cin),
    .Cout(Cout),
    .Sum(Sum)
  );
endmodule

module ha(a, b, s, ca);
  input a;
  wire a;
  input b;
  wire b;
  output s;
  wire s;
  output ca;
  wire ca;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(b),
    .B(a),
    .X(ca)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(b),
    .B(a),
    .X(s)
  );
endmodule

module inv32bits(i, sign, o);
  input [31:0] i;
  wire [31:0] i;
  input sign;
  wire sign;
  output [31:0] o;
  wire [31:0] o;
  sky130_fd_sc_hd__xor2_1 _00_ (
    .A(sign),
    .B(i[0]),
    .X(o[0])
  );
  sky130_fd_sc_hd__xor2_1 _01_ (
    .A(sign),
    .B(i[1]),
    .X(o[1])
  );
  sky130_fd_sc_hd__xor2_1 _02_ (
    .A(sign),
    .B(i[2]),
    .X(o[2])
  );
  sky130_fd_sc_hd__xor2_1 _03_ (
    .A(sign),
    .B(i[3]),
    .X(o[3])
  );
  sky130_fd_sc_hd__xor2_1 _04_ (
    .A(sign),
    .B(i[4]),
    .X(o[4])
  );
  sky130_fd_sc_hd__xor2_1 _05_ (
    .A(sign),
    .B(i[5]),
    .X(o[5])
  );
  sky130_fd_sc_hd__xor2_1 _06_ (
    .A(sign),
    .B(i[6]),
    .X(o[6])
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(sign),
    .B(i[7]),
    .X(o[7])
  );
  sky130_fd_sc_hd__xor2_1 _08_ (
    .A(sign),
    .B(i[8]),
    .X(o[8])
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(sign),
    .B(i[9]),
    .X(o[9])
  );
  sky130_fd_sc_hd__xor2_1 _10_ (
    .A(sign),
    .B(i[10]),
    .X(o[10])
  );
  sky130_fd_sc_hd__xor2_1 _11_ (
    .A(sign),
    .B(i[11]),
    .X(o[11])
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(sign),
    .B(i[12]),
    .X(o[12])
  );
  sky130_fd_sc_hd__xor2_1 _13_ (
    .A(sign),
    .B(i[13]),
    .X(o[13])
  );
  sky130_fd_sc_hd__xor2_1 _14_ (
    .A(sign),
    .B(i[14]),
    .X(o[14])
  );
  sky130_fd_sc_hd__xor2_1 _15_ (
    .A(sign),
    .B(i[15]),
    .X(o[15])
  );
  sky130_fd_sc_hd__xor2_1 _16_ (
    .A(sign),
    .B(i[16]),
    .X(o[16])
  );
  sky130_fd_sc_hd__xor2_1 _17_ (
    .A(sign),
    .B(i[17]),
    .X(o[17])
  );
  sky130_fd_sc_hd__xor2_1 _18_ (
    .A(sign),
    .B(i[18]),
    .X(o[18])
  );
  sky130_fd_sc_hd__xor2_1 _19_ (
    .A(sign),
    .B(i[19]),
    .X(o[19])
  );
  sky130_fd_sc_hd__xor2_1 _20_ (
    .A(sign),
    .B(i[20]),
    .X(o[20])
  );
  sky130_fd_sc_hd__xor2_1 _21_ (
    .A(sign),
    .B(i[21]),
    .X(o[21])
  );
  sky130_fd_sc_hd__xor2_1 _22_ (
    .A(sign),
    .B(i[22]),
    .X(o[22])
  );
  sky130_fd_sc_hd__xor2_1 _23_ (
    .A(sign),
    .B(i[23]),
    .X(o[23])
  );
  sky130_fd_sc_hd__xor2_1 _24_ (
    .A(sign),
    .B(i[24]),
    .X(o[24])
  );
  sky130_fd_sc_hd__xor2_1 _25_ (
    .A(sign),
    .B(i[25]),
    .X(o[25])
  );
  sky130_fd_sc_hd__xor2_1 _26_ (
    .A(sign),
    .B(i[26]),
    .X(o[26])
  );
  sky130_fd_sc_hd__xor2_1 _27_ (
    .A(sign),
    .B(i[27]),
    .X(o[27])
  );
  sky130_fd_sc_hd__xor2_1 _28_ (
    .A(sign),
    .B(i[28]),
    .X(o[28])
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(sign),
    .B(i[29]),
    .X(o[29])
  );
  sky130_fd_sc_hd__xor2_1 _30_ (
    .A(sign),
    .B(i[30]),
    .X(o[30])
  );
  sky130_fd_sc_hd__xor2_1 _31_ (
    .A(sign),
    .B(i[31]),
    .X(o[31])
  );
endmodule

module vedic1(a, b, c);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  output [31:0] c;
  wire [31:0] c;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire [15:0] abs_a;
  wire [15:0] abs_b;
  wire [31:0] nextinp;
  wire sign;
  wire [31:0] unsign;
  sky130_fd_sc_hd__clkinv_1 _072_ (
    .A(a[1]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _073_ (
    .A(b[1]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o21ai_0 _074_ (
    .A1(a[0]),
    .A2(a[1]),
    .B1(a[15]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21o_1 _075_ (
    .A1(a[0]),
    .A2(a[1]),
    .B1(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__o21ai_0 _076_ (
    .A1(_019_),
    .A2(a[15]),
    .B1(_022_),
    .Y(abs_a[1])
  );
  sky130_fd_sc_hd__xnor2_1 _077_ (
    .A(a[2]),
    .B(_021_),
    .Y(abs_a[2])
  );
  sky130_fd_sc_hd__o31ai_1 _078_ (
    .A1(a[0]),
    .A2(a[1]),
    .A3(a[2]),
    .B1(a[15]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _079_ (
    .A(a[3]),
    .B(_023_),
    .Y(abs_a[3])
  );
  sky130_fd_sc_hd__or4_1 _080_ (
    .A(a[0]),
    .B(a[1]),
    .C(a[2]),
    .D(a[3]),
    .X(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _081_ (
    .A(a[15]),
    .B(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__xnor2_1 _082_ (
    .A(a[4]),
    .B(_025_),
    .Y(abs_a[4])
  );
  sky130_fd_sc_hd__o21ai_0 _083_ (
    .A1(a[4]),
    .A2(_024_),
    .B1(a[15]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _084_ (
    .A(a[5]),
    .B(_026_),
    .Y(abs_a[5])
  );
  sky130_fd_sc_hd__o31ai_1 _085_ (
    .A1(a[4]),
    .A2(a[5]),
    .A3(_024_),
    .B1(a[15]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _086_ (
    .A(a[6]),
    .B(_027_),
    .Y(abs_a[6])
  );
  sky130_fd_sc_hd__nor4_1 _087_ (
    .A(a[4]),
    .B(a[5]),
    .C(a[6]),
    .D(_024_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2b_1 _088_ (
    .A_N(_028_),
    .B(a[15]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xnor2_1 _089_ (
    .A(a[7]),
    .B(_029_),
    .Y(abs_a[7])
  );
  sky130_fd_sc_hd__nand2b_1 _090_ (
    .A_N(a[7]),
    .B(_028_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _091_ (
    .A(a[15]),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _092_ (
    .A(a[8]),
    .B(_031_),
    .Y(abs_a[8])
  );
  sky130_fd_sc_hd__o21ai_0 _093_ (
    .A1(a[8]),
    .A2(_030_),
    .B1(a[15]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xnor2_1 _094_ (
    .A(a[9]),
    .B(_032_),
    .Y(abs_a[9])
  );
  sky130_fd_sc_hd__o31ai_1 _095_ (
    .A1(a[8]),
    .A2(a[9]),
    .A3(_030_),
    .B1(a[15]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xnor2_1 _096_ (
    .A(a[10]),
    .B(_033_),
    .Y(abs_a[10])
  );
  sky130_fd_sc_hd__or4_1 _097_ (
    .A(a[8]),
    .B(a[9]),
    .C(a[10]),
    .D(_030_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _098_ (
    .A(a[15]),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xnor2_1 _099_ (
    .A(a[11]),
    .B(_035_),
    .Y(abs_a[11])
  );
  sky130_fd_sc_hd__o21ai_0 _100_ (
    .A1(a[11]),
    .A2(_034_),
    .B1(a[15]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _101_ (
    .A(a[12]),
    .B(_036_),
    .Y(abs_a[12])
  );
  sky130_fd_sc_hd__nor3_1 _102_ (
    .A(a[11]),
    .B(a[12]),
    .C(_034_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__o31ai_1 _103_ (
    .A1(a[11]),
    .A2(a[12]),
    .A3(_034_),
    .B1(a[15]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _104_ (
    .A(a[13]),
    .B(_038_),
    .Y(abs_a[13])
  );
  sky130_fd_sc_hd__o41ai_1 _105_ (
    .A1(a[11]),
    .A2(a[12]),
    .A3(a[13]),
    .A4(_034_),
    .B1(a[15]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xnor2_1 _106_ (
    .A(a[14]),
    .B(_039_),
    .Y(abs_a[14])
  );
  sky130_fd_sc_hd__nor4bb_1 _107_ (
    .A(a[13]),
    .B(a[14]),
    .C_N(_037_),
    .D_N(a[15]),
    .Y(abs_a[15])
  );
  sky130_fd_sc_hd__o21ai_0 _108_ (
    .A1(b[0]),
    .A2(b[1]),
    .B1(b[15]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a21o_1 _109_ (
    .A1(b[0]),
    .A2(b[1]),
    .B1(_000_),
    .X(_001_)
  );
  sky130_fd_sc_hd__o21ai_0 _110_ (
    .A1(_020_),
    .A2(b[15]),
    .B1(_001_),
    .Y(abs_b[1])
  );
  sky130_fd_sc_hd__xnor2_1 _111_ (
    .A(b[2]),
    .B(_000_),
    .Y(abs_b[2])
  );
  sky130_fd_sc_hd__o31ai_1 _112_ (
    .A1(b[0]),
    .A2(b[1]),
    .A3(b[2]),
    .B1(b[15]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _113_ (
    .A(b[3]),
    .B(_002_),
    .Y(abs_b[3])
  );
  sky130_fd_sc_hd__or4_1 _114_ (
    .A(b[0]),
    .B(b[1]),
    .C(b[2]),
    .D(b[3]),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(b[15]),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _116_ (
    .A(b[4]),
    .B(_004_),
    .Y(abs_b[4])
  );
  sky130_fd_sc_hd__o21ai_0 _117_ (
    .A1(b[4]),
    .A2(_003_),
    .B1(b[15]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(b[5]),
    .B(_005_),
    .Y(abs_b[5])
  );
  sky130_fd_sc_hd__o31ai_1 _119_ (
    .A1(b[4]),
    .A2(b[5]),
    .A3(_003_),
    .B1(b[15]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xnor2_1 _120_ (
    .A(b[6]),
    .B(_006_),
    .Y(abs_b[6])
  );
  sky130_fd_sc_hd__nor4_1 _121_ (
    .A(b[4]),
    .B(b[5]),
    .C(b[6]),
    .D(_003_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2b_1 _122_ (
    .A_N(_007_),
    .B(b[15]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _123_ (
    .A(b[7]),
    .B(_008_),
    .Y(abs_b[7])
  );
  sky130_fd_sc_hd__nand2b_1 _124_ (
    .A_N(b[7]),
    .B(_007_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _125_ (
    .A(b[15]),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _126_ (
    .A(b[8]),
    .B(_010_),
    .Y(abs_b[8])
  );
  sky130_fd_sc_hd__o21ai_0 _127_ (
    .A1(b[8]),
    .A2(_009_),
    .B1(b[15]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _128_ (
    .A(b[9]),
    .B(_011_),
    .Y(abs_b[9])
  );
  sky130_fd_sc_hd__o31ai_1 _129_ (
    .A1(b[8]),
    .A2(b[9]),
    .A3(_009_),
    .B1(b[15]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _130_ (
    .A(b[10]),
    .B(_012_),
    .Y(abs_b[10])
  );
  sky130_fd_sc_hd__or4_1 _131_ (
    .A(b[8]),
    .B(b[9]),
    .C(b[10]),
    .D(_009_),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _132_ (
    .A(b[15]),
    .B(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _133_ (
    .A(b[11]),
    .B(_014_),
    .Y(abs_b[11])
  );
  sky130_fd_sc_hd__o21ai_0 _134_ (
    .A1(b[11]),
    .A2(_013_),
    .B1(b[15]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _135_ (
    .A(b[12]),
    .B(_015_),
    .Y(abs_b[12])
  );
  sky130_fd_sc_hd__nor3_1 _136_ (
    .A(b[11]),
    .B(b[12]),
    .C(_013_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o31ai_1 _137_ (
    .A1(b[11]),
    .A2(b[12]),
    .A3(_013_),
    .B1(b[15]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _138_ (
    .A(b[13]),
    .B(_017_),
    .Y(abs_b[13])
  );
  sky130_fd_sc_hd__o41ai_1 _139_ (
    .A1(b[11]),
    .A2(b[12]),
    .A3(b[13]),
    .A4(_013_),
    .B1(b[15]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _140_ (
    .A(b[14]),
    .B(_018_),
    .Y(abs_b[14])
  );
  sky130_fd_sc_hd__nor4bb_1 _141_ (
    .A(b[13]),
    .B(b[14]),
    .C_N(_016_),
    .D_N(b[15]),
    .Y(abs_b[15])
  );
  sky130_fd_sc_hd__xor2_1 _142_ (
    .A(a[15]),
    .B(b[15]),
    .X(sign)
  );
  sky130_fd_sc_hd__conb_1 _143_ (
    .LO(_040_)
  );
  sky130_fd_sc_hd__conb_1 _144_ (
    .LO(_041_)
  );
  sky130_fd_sc_hd__conb_1 _145_ (
    .LO(_042_)
  );
  sky130_fd_sc_hd__conb_1 _146_ (
    .LO(_043_)
  );
  sky130_fd_sc_hd__conb_1 _147_ (
    .LO(_044_)
  );
  sky130_fd_sc_hd__conb_1 _148_ (
    .LO(_045_)
  );
  sky130_fd_sc_hd__conb_1 _149_ (
    .LO(_046_)
  );
  sky130_fd_sc_hd__conb_1 _150_ (
    .LO(_047_)
  );
  sky130_fd_sc_hd__conb_1 _151_ (
    .LO(_048_)
  );
  sky130_fd_sc_hd__conb_1 _152_ (
    .LO(_049_)
  );
  sky130_fd_sc_hd__conb_1 _153_ (
    .LO(_050_)
  );
  sky130_fd_sc_hd__conb_1 _154_ (
    .LO(_051_)
  );
  sky130_fd_sc_hd__conb_1 _155_ (
    .LO(_052_)
  );
  sky130_fd_sc_hd__conb_1 _156_ (
    .LO(_053_)
  );
  sky130_fd_sc_hd__conb_1 _157_ (
    .LO(_054_)
  );
  sky130_fd_sc_hd__conb_1 _158_ (
    .LO(_055_)
  );
  sky130_fd_sc_hd__conb_1 _159_ (
    .LO(_056_)
  );
  sky130_fd_sc_hd__conb_1 _160_ (
    .LO(_057_)
  );
  sky130_fd_sc_hd__conb_1 _161_ (
    .LO(_058_)
  );
  sky130_fd_sc_hd__conb_1 _162_ (
    .LO(_059_)
  );
  sky130_fd_sc_hd__conb_1 _163_ (
    .LO(_060_)
  );
  sky130_fd_sc_hd__conb_1 _164_ (
    .LO(_061_)
  );
  sky130_fd_sc_hd__conb_1 _165_ (
    .LO(_062_)
  );
  sky130_fd_sc_hd__conb_1 _166_ (
    .LO(_063_)
  );
  sky130_fd_sc_hd__conb_1 _167_ (
    .LO(_064_)
  );
  sky130_fd_sc_hd__conb_1 _168_ (
    .LO(_065_)
  );
  sky130_fd_sc_hd__conb_1 _169_ (
    .LO(_066_)
  );
  sky130_fd_sc_hd__conb_1 _170_ (
    .LO(_067_)
  );
  sky130_fd_sc_hd__conb_1 _171_ (
    .LO(_068_)
  );
  sky130_fd_sc_hd__conb_1 _172_ (
    .LO(_069_)
  );
  sky130_fd_sc_hd__conb_1 _173_ (
    .LO(_070_)
  );
  sky130_fd_sc_hd__conb_1 _174_ (
    .LO(_071_)
  );
  inv32bits inv0 (
    .i(unsign),
    .o(nextinp),
    .sign(sign)
  );
  KSA32 lastadder (
    .A(nextinp),
    .B({ _071_, _070_, _069_, _068_, _067_, _066_, _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_, _057_, _056_, _055_, _054_, _053_, _052_, _051_, _050_, _049_, _048_, _047_, _046_, _045_, _044_, _043_, _042_, _041_, _040_ }),
    .Cin(sign),
    .Sum(c)
  );
  vedic16x16 v0 (
    .a({ abs_a[15:1], a[0] }),
    .b({ abs_b[15:1], b[0] }),
    .c(unsign)
  );
  assign abs_a[0] = a[0];
  assign abs_b[0] = b[0];
endmodule

module vedic16x16(a, b, c);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  output [31:0] c;
  wire [31:0] c;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire [15:0] q0;
  wire [15:0] q1;
  wire [15:0] q2;
  wire [15:0] q3;
  wire [15:0] q4;
  wire [23:0] q5;
  wire [23:0] q6;
  wire [7:0] temp1;
  wire [23:0] temp2;
  wire [23:0] temp3;
  wire [23:0] temp4;
  sky130_fd_sc_hd__conb_1 _35_ (
    .LO(_00_)
  );
  sky130_fd_sc_hd__conb_1 _36_ (
    .LO(_01_)
  );
  sky130_fd_sc_hd__conb_1 _37_ (
    .LO(_02_)
  );
  sky130_fd_sc_hd__conb_1 _38_ (
    .LO(_03_)
  );
  sky130_fd_sc_hd__conb_1 _39_ (
    .LO(_04_)
  );
  sky130_fd_sc_hd__conb_1 _40_ (
    .LO(_05_)
  );
  sky130_fd_sc_hd__conb_1 _41_ (
    .LO(_06_)
  );
  sky130_fd_sc_hd__conb_1 _42_ (
    .LO(_07_)
  );
  sky130_fd_sc_hd__conb_1 _43_ (
    .LO(_08_)
  );
  sky130_fd_sc_hd__conb_1 _44_ (
    .LO(_09_)
  );
  sky130_fd_sc_hd__conb_1 _45_ (
    .LO(_10_)
  );
  sky130_fd_sc_hd__conb_1 _46_ (
    .LO(_11_)
  );
  sky130_fd_sc_hd__conb_1 _47_ (
    .LO(_12_)
  );
  sky130_fd_sc_hd__conb_1 _48_ (
    .LO(_13_)
  );
  sky130_fd_sc_hd__conb_1 _49_ (
    .LO(_14_)
  );
  sky130_fd_sc_hd__conb_1 _50_ (
    .LO(_15_)
  );
  sky130_fd_sc_hd__conb_1 _51_ (
    .LO(_16_)
  );
  sky130_fd_sc_hd__conb_1 _52_ (
    .LO(_17_)
  );
  sky130_fd_sc_hd__conb_1 _53_ (
    .LO(_18_)
  );
  sky130_fd_sc_hd__conb_1 _54_ (
    .LO(_19_)
  );
  sky130_fd_sc_hd__conb_1 _55_ (
    .LO(_20_)
  );
  sky130_fd_sc_hd__conb_1 _56_ (
    .LO(_21_)
  );
  sky130_fd_sc_hd__conb_1 _57_ (
    .LO(_22_)
  );
  sky130_fd_sc_hd__conb_1 _58_ (
    .LO(_23_)
  );
  sky130_fd_sc_hd__conb_1 _59_ (
    .LO(_24_)
  );
  sky130_fd_sc_hd__conb_1 _60_ (
    .LO(_25_)
  );
  sky130_fd_sc_hd__conb_1 _61_ (
    .LO(_26_)
  );
  sky130_fd_sc_hd__conb_1 _62_ (
    .LO(_27_)
  );
  sky130_fd_sc_hd__conb_1 _63_ (
    .LO(_28_)
  );
  sky130_fd_sc_hd__conb_1 _64_ (
    .LO(_29_)
  );
  sky130_fd_sc_hd__conb_1 _65_ (
    .LO(_30_)
  );
  sky130_fd_sc_hd__conb_1 _66_ (
    .LO(_31_)
  );
  sky130_fd_sc_hd__conb_1 _67_ (
    .LO(_32_)
  );
  sky130_fd_sc_hd__conb_1 _68_ (
    .LO(_33_)
  );
  sky130_fd_sc_hd__conb_1 _69_ (
    .LO(_34_)
  );
  vedic_8X8 z1 (
    .a(a[7:0]),
    .b(b[7:0]),
    .c(q0)
  );
  vedic_8X8 z2 (
    .a(a[15:8]),
    .b(b[7:0]),
    .c(q1)
  );
  vedic_8X8 z3 (
    .a(a[7:0]),
    .b(b[15:8]),
    .c(q2)
  );
  vedic_8X8 z4 (
    .a(a[15:8]),
    .b(b[15:8]),
    .c(q3)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000010000  z5 (
    .A(q1),
    .B({ _07_, _06_, _05_, _04_, _03_, _02_, _01_, _00_, q0[15:8] }),
    .Cin(_08_),
    .Sum(q4)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000011000  z6 (
    .A({ _16_, _15_, _14_, _13_, _12_, _11_, _10_, _09_, q2 }),
    .B({ q3, _24_, _23_, _22_, _21_, _20_, _19_, _18_, _17_ }),
    .Cin(_25_),
    .Sum(q5)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000011000  z7 (
    .A({ _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, q4 }),
    .B(q5),
    .Cin(_34_),
    .Sum(q6)
  );
  assign c = { q6, q0[7:0] };
  assign temp1 = q0[15:8];
  assign temp2[15:0] = q2;
  assign temp3[23:8] = q3;
  assign temp4[15:0] = q4;
endmodule

module vedic_2_x_2(a, b, c);
  input [1:0] a;
  wire [1:0] a;
  input [1:0] b;
  wire [1:0] b;
  output [3:0] c;
  wire [3:0] c;
  wire [3:0] temp;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(b[0]),
    .B(a[0]),
    .X(c[0])
  );
  sky130_fd_sc_hd__and2_0 _1_ (
    .A(b[0]),
    .B(a[1]),
    .X(temp[0])
  );
  sky130_fd_sc_hd__and2_0 _2_ (
    .A(a[0]),
    .B(b[1]),
    .X(temp[1])
  );
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(a[1]),
    .B(b[1]),
    .X(temp[2])
  );
  ha z1 (
    .a(temp[0]),
    .b(temp[1]),
    .ca(temp[3]),
    .s(c[1])
  );
  ha z2 (
    .a(temp[2]),
    .b(temp[3]),
    .ca(c[3]),
    .s(c[2])
  );
endmodule

module vedic_4_x_4(a, b, c);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [7:0] c;
  wire [7:0] c;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [3:0] q0;
  wire [3:0] q1;
  wire [3:0] q2;
  wire [3:0] q3;
  wire [3:0] q4;
  wire [5:0] q5;
  wire [5:0] q6;
  wire [1:0] temp1;
  wire [5:0] temp2;
  wire [5:0] temp3;
  wire [5:0] temp4;
  sky130_fd_sc_hd__conb_1 _11_ (
    .LO(_00_)
  );
  sky130_fd_sc_hd__conb_1 _12_ (
    .LO(_01_)
  );
  sky130_fd_sc_hd__conb_1 _13_ (
    .LO(_02_)
  );
  sky130_fd_sc_hd__conb_1 _14_ (
    .LO(_03_)
  );
  sky130_fd_sc_hd__conb_1 _15_ (
    .LO(_04_)
  );
  sky130_fd_sc_hd__conb_1 _16_ (
    .LO(_05_)
  );
  sky130_fd_sc_hd__conb_1 _17_ (
    .LO(_06_)
  );
  sky130_fd_sc_hd__conb_1 _18_ (
    .LO(_07_)
  );
  sky130_fd_sc_hd__conb_1 _19_ (
    .LO(_08_)
  );
  sky130_fd_sc_hd__conb_1 _20_ (
    .LO(_09_)
  );
  sky130_fd_sc_hd__conb_1 _21_ (
    .LO(_10_)
  );
  vedic_2_x_2 z1 (
    .a(a[1:0]),
    .b(b[1:0]),
    .c(q0)
  );
  vedic_2_x_2 z2 (
    .a(a[3:2]),
    .b(b[1:0]),
    .c(q1)
  );
  vedic_2_x_2 z3 (
    .a(a[1:0]),
    .b(b[3:2]),
    .c(q2)
  );
  vedic_2_x_2 z4 (
    .a(a[3:2]),
    .b(b[3:2]),
    .c(q3)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000000100  z5 (
    .A(q1),
    .B({ _01_, _00_, q0[3:2] }),
    .Cin(_02_),
    .Sum(q4)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000000110  z6 (
    .A({ _04_, _03_, q2 }),
    .B({ q3, _06_, _05_ }),
    .Cin(_07_),
    .Sum(q5)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000000110  z7 (
    .A({ _09_, _08_, q4 }),
    .B(q5),
    .Cin(_10_),
    .Sum(q6)
  );
  assign c = { q6, q0[1:0] };
  assign temp1 = q0[3:2];
  assign temp2[3:0] = q2;
  assign temp3[5:2] = q3;
  assign temp4[3:0] = q4;
endmodule

module vedic_8X8(a, b, c);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output [15:0] c;
  wire [15:0] c;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire [7:0] q0;
  wire [7:0] q1;
  wire [7:0] q2;
  wire [7:0] q3;
  wire [7:0] q4;
  wire [11:0] q5;
  wire [11:0] q6;
  wire [3:0] temp1;
  wire [11:0] temp2;
  wire [11:0] temp3;
  wire [11:0] temp4;
  sky130_fd_sc_hd__conb_1 _19_ (
    .LO(_00_)
  );
  sky130_fd_sc_hd__conb_1 _20_ (
    .LO(_01_)
  );
  sky130_fd_sc_hd__conb_1 _21_ (
    .LO(_02_)
  );
  sky130_fd_sc_hd__conb_1 _22_ (
    .LO(_03_)
  );
  sky130_fd_sc_hd__conb_1 _23_ (
    .LO(_04_)
  );
  sky130_fd_sc_hd__conb_1 _24_ (
    .LO(_05_)
  );
  sky130_fd_sc_hd__conb_1 _25_ (
    .LO(_06_)
  );
  sky130_fd_sc_hd__conb_1 _26_ (
    .LO(_07_)
  );
  sky130_fd_sc_hd__conb_1 _27_ (
    .LO(_08_)
  );
  sky130_fd_sc_hd__conb_1 _28_ (
    .LO(_09_)
  );
  sky130_fd_sc_hd__conb_1 _29_ (
    .LO(_10_)
  );
  sky130_fd_sc_hd__conb_1 _30_ (
    .LO(_11_)
  );
  sky130_fd_sc_hd__conb_1 _31_ (
    .LO(_12_)
  );
  sky130_fd_sc_hd__conb_1 _32_ (
    .LO(_13_)
  );
  sky130_fd_sc_hd__conb_1 _33_ (
    .LO(_14_)
  );
  sky130_fd_sc_hd__conb_1 _34_ (
    .LO(_15_)
  );
  sky130_fd_sc_hd__conb_1 _35_ (
    .LO(_16_)
  );
  sky130_fd_sc_hd__conb_1 _36_ (
    .LO(_17_)
  );
  sky130_fd_sc_hd__conb_1 _37_ (
    .LO(_18_)
  );
  vedic_4_x_4 z1 (
    .a(a[3:0]),
    .b(b[3:0]),
    .c(q0)
  );
  vedic_4_x_4 z2 (
    .a(a[7:4]),
    .b(b[3:0]),
    .c(q1)
  );
  vedic_4_x_4 z3 (
    .a(a[3:0]),
    .b(b[7:4]),
    .c(q2)
  );
  vedic_4_x_4 z4 (
    .a(a[7:4]),
    .b(b[7:4]),
    .c(q3)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000001000  z5 (
    .A(q1),
    .B({ _03_, _02_, _01_, _00_, q0[7:4] }),
    .Cin(_04_),
    .Sum(q4)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000001100  z6 (
    .A({ _08_, _07_, _06_, _05_, q2 }),
    .B({ q3, _12_, _11_, _10_, _09_ }),
    .Cin(_13_),
    .Sum(q5)
  );
  \$paramod\KoggeStoneAdder\WIDTH=s32'00000000000000000000000000001100  z7 (
    .A({ _17_, _16_, _15_, _14_, q4 }),
    .B(q5),
    .Cin(_18_),
    .Sum(q6)
  );
  assign c = { q6, q0[3:0] };
  assign temp1 = q0[7:4];
  assign temp2[7:0] = q2;
  assign temp3[11:4] = q3;
  assign temp4[7:0] = q4;
endmodule
